### PR TITLE
75% Silent Keyboard

### PR DESCRIPTION
**Pull request by MagiDarkPro**
## Describe your project in 1-3 sentences

I am building a 75% custom keyboard that will be made as quiet as possible. The point of this is to game without disrupting others or work on homework and type fast without making noise.

## Hack Club Slack handle

diglatte

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by exu3 — COMMENTED** [review]
Hi @MagiDarkPro, thanks for submitting a project proposal.

Unfortunately, this proposal doesn't quite meet the goals of the event.

The goal of Winter Hardware Wonderland is to make hardware hacking (creatively building things using the details of how electronics work) available to more people, but building a keyboard in the more mainstream sense (buying the keycaps, switches, PCB, case, then assembling them) doesn't really count. It just should be more lower level than plugging a few components together and uploading some premade firmware. Some customizations I might suggest: creating a custom layout, designing your own PCB, or compiling your own firmware.

For ideas, I'd highly recommend checking out the links in this Slack message: [hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499](https://hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499)

I'm going to close this pull request for now, but feel free to open a new one with a revised project proposal, or re-open this one if it's easier.

Let me know if you have any questions!

**Comment by MagiDarkPro** [comment]
Thank you for reviewing my project proposal. I have a question about what creating a custom layout means. Does creating a custom layout mean that I change the functions of specific keys?

**Comment by exu3** [comment]
@MagiDarkPro: by custom layout, I am referring to layout of the physical keys themselves. For example, https://kbd.news/Declarative-keyboard-design-with-Ergogen-v4.0-1814.html

**Comment by MagiDarkPro** [comment]
@exu3 ooh ok thank you

**Pull request closed without merging**
