### PR TITLE
Nature's Eye - A Bird Camera and Weather Monitor

### PR DESCRIPTION
**Pull request by VelocityDesign**
## Describe your project in 1-3 sentences

I am building a bird camera and weather monitor for a forest in my backyard. This system will connect to my Home Assistant instance and provide vital statistics about the weather and will stream video footage of the forest (and birds in it) back to the server. I'm also building a smart system for my RGB strips in my bedroom, which is also powered by Home Assistant.

## Hack Club Slack handle
I'm Judah Brown (`U033N1Y3YTB`) on the slack.

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by cfanoulis — COMMENTED** [review]
this is so cool! can't wait all the cool bird photos in #surroundings

just confirm one thing with me rq: you'll be documenting your progress during the 10-day period of making in Slack as well

**Comment by VelocityDesign** [comment]
Yes, sorry if that wasn't clear initially.
I'm intending to release a full blog post too for #100DaysToOffload on my (freshly designed) blog as well.

**Review by cfanoulis — APPROVED** [review]
Then I'm happy to say you're one step closer! A banker from @hackclub/bank-ops will be reaching our shortly to get you setup on da hack bank

**Comment by VelocityDesign** [comment]
Awesome, thanks so much!

**Review by daisybanks — APPROVED** [review]
Hi @VelocityDesign! I love this project idea - I love watching birds and grew up in woodsy areas and would watch the birds outside all the time. I especially love watching them in the snow and then looking at all of their little marks in the snow! I'm dming you now on Slack to talk about next steps for getting you on Bank and getting you your grant!

**Pull request merged**
