### PR TITLE
Tron Hoodie 

### PR DESCRIPTION
**Pull request by Mahak1729**
## Describe your project in 1-3 sentences

Building a Tron Hoodie that looks as if it is something from the future.

## Hack Club Slack handle

 @ Mahak Kumawat 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — APPROVED** [review]
hiii @Mahak1729 this is super cool!! for your next projects, i'd recommend looking at something that allows you to really play with electronics :)

an awesome member of @hackclub/bank-ops will be reaching out soon!

fyi: this grant is up to $250 so we'd only send you $50 (since that's the total of this project) and if you're interested in building more projects you'd have to include them in a PR by Jan 15th.

**Review by hackliv — APPROVED** [review]
Hey @Mahak1729 this sounds so so cool! I'm dming you now on Slack to set up some time to chat about receiving the grant through Hack Club Bank. 😃

**Review by Mahak1729 — COMMENTED** [review]
I understand I have kept a significant margin for spending. This is due to the fact that I will be building all this in Sitka, Alaska, and Not in Pune, India thus I am not ultra familiar with the stuff I am familiar with here. I will have a detailed account once I have taken significant steps toward the projects to inorder to help with the consolidation later on.

**Comment by hackliv** [comment]
> I understand I have kept a significant margin for spending. This is due to the fact that I will be building all this in Sitka, Alaska, and Not in Pune, India thus I am not ultra familiar with the stuff I am familiar with here. I will have a detailed account once I have taken significant steps toward the projects to inorder to help with the consolidation later on.

just dm'd you on Slack about updating your budget!

**Comment by Mahak1729** [comment]
Being an expert in Github /s, I had made changes in a branch I created yesterday and had forgotten to commit it to the main branch. I was scared for a moment when I could not recover the changes I did yesterday. 
You can see the additions I have made for the other projects along with the respective budgets. Let me know if you have any more questions or concerns from your side.

**Comment by bellesea** [comment]
> Being an expert in Github /s, I had made changes in a branch I created yesterday and had forgotten to commit it to the main branch. I was scared for a moment when I could not recover the changes I did yesterday. You can see the additions I have made for the other projects along with the respective budgets. Let me know if you have any more questions or concerns from your side.

@Mahak1729 thanks for pushing the changes! we're back on tomorrow and will start reviewing the changes :) at first glance, your mechanical keyboard project might not be the most suitable for this event/grant given that the goal of Winter Hardware Wonderland is to make hardware hacking (creatively building things using the details of how electronics work) available to more people, but building a keyboard in the more mainstream sense (buying the keycaps, switches, PCB, case, then assembling them) doesn't really count. It just should be more lower level than plugging a few components together and uploading some premade firmware. Some customizations I might suggest: creating a custom layout, designing your own PCB, or compiling your own firmware.

For ideas, I'd highly recommend checking out the links in this Slack message: [hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499](https://hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499)

I understand that you don't have that much experience, perhaps you could consider an alternative project too? thanks!

(the RGB bag looks cool!)

**Comment by bellesea** [comment]
hey @Mahak1729 it's been a few days since my message with feedback on your new projects :) i'm wondering, are you still interested in moving forward with expansions to your project? 

please respond within 48 hours if you'd like to move forward with expanding your budget and building more projects, otherwise you might not be able to get your parts in time for the event. thank you!

**Comment by cfanoulis** [comment]
Hello, it's been 48 hours so we'll be closing this proposal. If you wish to continue working on this, please answer in the next 24 hours.

**Comment by cfanoulis** [comment]
OH WHOOPS sorry! I didn't see you were approved for a grant! Keeping this open

**Comment by cfanoulis** [comment]
Heyyyy! As we haven't hear back from you for quite a while, we're only going to be covering your 1st project (__Tron Hoodie__), with a budget of 50$. I've gone ahead and updated your project proposal to indicate that - please make sure to get in touch with your banker (@hackliv) to get setup for your grant. Have fun :)

**Comment by cfanoulis** [comment]
Also, we'll need you to schedule your onboarding call within the next 48hrs, as time is running tight and we need to get you your project materials!

**Comment by hackliv** [comment]
> Also, we'll need you to schedule your onboarding call within the next 48hrs, as time is running tight and we need to get you your project materials!

hey @cfanoulis I'll merge this PR since they already have the grant $ on Bank. 😃

**Comment by cfanoulis** [comment]
merci liv!!

@Mahak1729 enjoy your grant!! (responsibly!)

**Comment by Mahak1729** [comment]
I just saw the messages now :( :( . I just moved from Pune, India to Sitka, Alaska and my life had just turned upside down for a long time. I have already gotten one grant so would start working on it soon. Too Bad I missed out on the opportunity to work on others. I again apologize for going MIA during such a crucial time and hope you are able to understand it. If there is still a shot I could get a grant by a miracle that is awesome if not then it is a lesson. Anyways I appreciate everyone's concern and thanks for taking me onto hack club community !

**Comment by hackliv** [comment]
> I just saw the messages now :( :( . I just moved from Pune, India to Sitka, Alaska and my life had just turned upside down for a long time. I have already gotten one grant so would start working on it soon. Too Bad I missed out on the opportunity to work on others. I again apologize for going MIA during such a crucial time and hope you are able to understand it. If there is still a shot I could get a grant by a miracle that is awesome if not then it is a lesson. Anyways I appreciate everyone's concern and thanks for taking me onto hack club community !

No worries at all Mahak! I hope your move went well, and I'm excited to see you build this hoodie! Feel free to dm me if you need any help with hardware purchases in AK. 😊

**Comment by Mahak1729** [comment]
It has been going well. I will dm you if I need any help with the hardware purchase for sure. Appreciate your help !

**Comment by Mahak1729** [comment]
Ordered all the parts/components! see you in slack soon!

**Comment by hackliv** [comment]
> Unable to Order parts/components required through Adafruit ! need some assistance , bcc bank@hackclub for it

just responded to your dm! could just be an issue with the billing section

**Pull request merged**
