### PR TITLE
Self driving electric bike

### PR DESCRIPTION
**Pull request by pranavnt**
## Describe your project in 1-3 sentences

We’re building an ebike that has full self cycling built in – you press the FSC button and the bike will automatically detect the lanes + edge of the trail, and cycle at ~8mph.

## Hack Club Slack handle
`pranav`, `ishan`

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in. thanks for your patience :)** 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

(note: this project looks super cool and we can't wait to review it!)

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — APPROVED** [review]
Vroom! Vroom! 🚴‍♂️💨

This sounds like good fun. Out of curiosity, what's the plan for the software?

**Comment by pranavnt** [comment]
from a high level: use OAK-D camera to detect the edges of the trail, go at ~8mph, and turn when required to stay on trail

**Review by MelSmith104 — COMMENTED** [review]
hey @pranavnt and @quackduck this is so cool! im so excited to see you ship this bike :) dm'ing you now on slack to get started with the grant!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
