### PR TITLE
Create vincent_doan

### PR DESCRIPTION
**Pull request by TheTsar8756**
## Describe your project in 1-3 sentences

Building VR Body Trackers that track specific parts of your body so you can see them while a headset is on a person.

## Checklist before submitting proposal:

- [✓] I am a current high school student (or younger).
- [✓] I have submitted an RSVP at <https://hackclub.com/winter>
- [✓ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✓] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: are you following any sort of guide for this? does your budget include shipping & taxes? and, can you please join the hack club slack? that's where the event will take place :))_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by TheTsar8756** [comment]
Yes, I am following this guide for making DIY VR trackers for the SlimeVr software ( https://docs.slimevr.dev ). I have also updated the commit to redo the budget with shipping included and also have joined the hack club slack.

**Comment by bellesea** [comment]
> Yes, I am following this guide for making DIY VR trackers for the SlimeVr software ( https://docs.slimevr.dev ). I have also updated the commit to redo the budget with shipping included and also have joined the hack club slack.

awesome! can you please add this to your file? sounds good, thanks! a heads up that we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by alhardwarehyde — APPROVED** [review]
Cool and interesting project! I think it's a great way to learn more about hardware! 

@hackclub/bank-ops

**Review by hackliv — APPROVED** [review]
WOW @TheTsar8756 I can't wait to see this project! 😊 I'm dming you now on Slack to chat more about next steps for the grant.

**Pull request merged**
