### PR TITLE
Create snoglobe.md

### PR DESCRIPTION
**Pull request by snoglobe**
## Describe your project in 1-3 sentences

I am building a beginner-friendly Arduino-like board meant to get young makers interested in simple electronics projects. The board is affordable ($5 to buy, approximately $3.08 per unit to produce)

## Hack Club Slack handle

@mason (username is @snwy)

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: oh wow this is incredibly cool! i'm wondering, do you have any references/ guides for this? can't wait to review it)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by snoglobe** [comment]
thank you! i kind of devised it on my own, but i'd love to make a blog post/something detailing how i designed it etc. and i'll also make a guide on how to build it ofc

**Comment by bellesea** [comment]
@snoglobe that sounds awesome!! we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by alhardwarehyde — APPROVED** [review]
This is a really cool project! and you've clearly already put a lot of work and thought into it. Can you link your designs for the schematic and PCBs? 

@hackclub/bank-ops for their review

**Comment by snoglobe** [comment]
Yes, I’ll do it once I get home

**Review by daisybanks — APPROVED** [review]
Hi @snoglobe! I really like how you're creating this and doing this project with the intent to get beginners involved! I'd love to chat more about your project! I'm dming you on /slack now to talk about the next steps in getting you your grant. :)

**Pull request merged**
