### PR TITLE
Raspberry Web Services (RWS) | DIY Homemade AWS Cloud

### PR DESCRIPTION
**Pull request by alialiwa2005**
## Describe your project in 1-3 sentences

Instead of hosting a site, Minecraft server, or web app on a cloud service like AWS, 
I'm excited to build a hackable (mini)-super-computer-powered cloud, while exploring redundancy, load-balancing, containers, orchestration, and physical networking, including from a large hands-on hardware perspective!

## Hack Club Slack handle

Ali A. Saleh

## Checklist before submitting a proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by alialiwa2005 — COMMENTED** [review]
I am excited to build this! 

I am sure that this will turn out to be an awesome and unique project, and I can't wait to start making it this winter!

While this project is about making, it is also an awesome learning opportunity for me, in terms of the hardware side of computing and cloud, such as physical networking, as well as the software side of dev-ops, 
such as using Kubernetes to manage separate pieces of hardware that make up a cluster in accomplishing tasks in unison... that is just mind-blowing to me!

What's even better is that unlike just deploying instances on the AWS dashboard, I get to actually build my own cloud, comparable to the actual Amazon Web Services, from scratch... starting with the hardware, inspecting the physical computer boards and chips, physically networking the nodes, even designing a stylish case for the cloud! :)

I always wanted to build a super-computer. I guess Winter of Making will finally make this dream a part of my New Year's Hacking bucket-list! Hooray!

**Review by bellesea — CHANGES_REQUESTED** [review]
@alialiwa2005 this looks sooo awesome!! are you building with the guidance of a guide or something like that? 

also, could you please add taxes/shipping to the calculation? i understand that it already exceeds $250 but would be helpful for record purposes + figuring out payment logistics later on :)

thank you!

**Comment by alialiwa2005** [comment]
> @alialiwa2005 this looks sooo awesome!! are you building with the guidance of a guide or something like that?
> 
> also, could you please add taxes/shipping to the calculation? i understand that it already exceeds $250 but would be helpful for record purposes + figuring out payment logistics later on :)
> 
> thank you!

@bellesea, I've added NYC Sales Tax (8.875%) to Total.

**Comment by alialiwa2005** [comment]
> @alialiwa2005 this looks sooo awesome!! are you building with the guidance of a guide or something like that?
> 

I was inspired by some tutorials, but the steps I wrote are original. For the steps were you add lines, like adding arm_64bit=1 to config.txt, I referenced the Raspberry Pi official documentation on how to enable 64 bit proccessing on the Pi's arm cpu, since by default the Pi runs in 32 bit mode.

I also referenced Kubernetes documentation, which gave me some requirements like 64bit, and enabling cgroup.

I also referred to different ways for headless network setup for the pi, as well as headless SSH by adding an ssh file (without a file extension), as per Raspberry Pi documentation.

I also used to have an older Pi3 (which just recently died), so I have experience with the basics of headless setup and ssh.

Through this project, I hope to learn more about linux, kubernetes, cluster computing, physical and cyber networking, loadbalancing, redundancy, and how a cloud, like Amazon Web Services (AWS) works by building my own cloud.

**Comment by bellesea** [comment]
> > @alialiwa2005 this looks sooo awesome!! are you building with the guidance of a guide or something like that?
> 
> Thank you, @bellesea!
> 
> I was inspired by a few of others' builds and AWS itself, but the steps I wrote are original.
> 
> For the steps were you add lines, like adding arm_64bit=1 to config.txt, I referenced the Raspberry Pi official documentation on how to enable 64 bit proccessing on the Pi's arm cpu, since by default the Pi runs in 32 bit mode.
> 
> I also referenced Kubernetes documentation, which gave me some requirements like 64bit, and enabling cgroup.
> 
> I also referred to different ways for headless network setup for the pi, as well as headless SSH by adding an ssh file (without a file extension), as per Raspberry Pi documentation.
> 
> So while I refered to multiple sources to ensure my steps are most likely function properly, I did so only as fundamentally neccessary, minimally.
> 
> I also used to have an older Pi3 (which just recently died), so I have experience with the basics of headless setup and ssh, and knowledge of some essential linux commands.
> 
> Through this project, I hope to learn more about linux, kubernetes, cluster computing, physical and cyber networking, loadbalancing, redundancy, and how a cloud, like Amazon Web Services (AWS), works by building my own cloud.

@alialiwa2005 thank you so so much for this comprehensive response hehe :) i asked because this is an insanely cool project and wanted to see if you had the necessary references/guides to help you pull it off hehe, love that you're learning straight from the documentation and varying your sources!

**Review by bellesea — APPROVED** [review]
@alialiwa2005 can't wait to see you work on this!! an awesome member of the @hackclub/bank-ops team will reach out w/ next steps :)

**Comment by hackliv** [comment]
Hey @alialiwa2005! I was so excited to see you wrote that this project is on your bucket list. 😃 I can't wait to see this in the 10 days of making on the Slack!! Btw, I'm dming you now on Slack to coordinate getting set up on Bank and receiving the grant.

**Review by hackliv — APPROVED** [review]

**Comment by alialiwa2005** [comment]
Updated material list: https://github.com/hackclub/winter/pull/191

**Pull request merged**
