### PR TITLE
Create Tanishqupmanu.md

### PR DESCRIPTION
**Pull request by Kaizeltech**
## Describe your project in 1-3 sentences

Building a drone, or an unmanned aerial vehicle (UAV), can be a thrilling and educative experience. It requires a combination of engineering, design, and programming skills, and the goal is to create a device that can perform a variety of tasks, depending on its design and purpose. The drone, typically controlled remotely by a pilot or through a pre-programmed flight path, can be used for a wide range of purposes, including surveillance, photography, mapping, delivery, and scientific research.

## Hack Club Slack handle

@Tanishq Upmanu

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey @Kaizeltech! Could you expand on this drone will differ from previous drones you've made?

**Comment by Kaizeltech** [comment]
> Hey @Kaizeltech! Could you expand on this drone will differ from previous drones you've made?

This drone is a successor to the previous drone that was presented at EPOCH India. It boasts a range of new, advanced features and is equipped with an array of sensors that enable it to perform a variety of tasks. Additionally, it has been designed with an emphasis on safety, making it a reliable and secure choice for various applications.

**Review by sampoder — APPROVED** [review]

**Comment by sampoder** [comment]
Looking forward to your project & joining you in a winter wonderland! ❄️ ☃️ ✨

**Review by MelSmith104 — COMMENTED** [review]
hi! since we've already moved to slack im just making a note of it here :)

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
