### PR TITLE
Create otto robot

### PR DESCRIPTION
**Pull request by chen98013**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by chen98013** [comment]
Most of this small four-legged robot is not difficult, but it is a simple module stacking. You only need to be proficient in the use of each module and make full use of resources such as the timer and external interrupt of the main control chip. In my actual production, it only took more time to debug the infrared communication. ★ 2. The key point is the design of the robot gait, which may take more time. The left and right turns are relatively simple, and it is difficult to move forward and backward. (Because the text and pictures are not well displayed, the gait I designed is not described in detail). ★ 3. Because the servo cannot be exactly the same, it needs to be finely debugged for each (including the space ratio corresponding to the angle range and the angle corresponding to the rotation), and because the quality of this servo is average, too much use will cause certain differences.

**Comment by chen98013** [comment]
Most of this small four-legged robot is not difficult, but it is a simple module stacking. You only need to be proficient in the use of each module and make full use of resources such as the timer and external interrupt of the main control chip. In my actual production, it only took more time to debug the infrared communication. ★ 2. The key point is the design of the robot gait, which may take more time. The left and right turns are relatively simple, and it is difficult to move forward and backward. (Because the text and pictures are not well displayed, the gait I designed is not described in detail). ★ 3. Because the servo cannot be exactly the same, it needs to be finely debugged for each (including the space ratio corresponding to the angle range and the angle corresponding to the rotation), and because the quality of this servo is average, too much use will cause certain differences.

**Comment by chen98013** [comment]
Most of this small four-legged robot is not difficult, but it is a simple module stacking. You only need to be proficient in the use of each module and make full use of resources such as the timer and external interrupt of the main control chip. In my actual production, it only took more time to debug the infrared communication. ★ 2. The key point is the design of the robot gait, which may take more time. The left and right turns are relatively simple, and it is difficult to move forward and backward. (Because the text and pictures are not well displayed, the gait I designed is not described in detail). ★ 3. Because the servo cannot be exactly the same, it needs to be finely debugged for each (including the space ratio corresponding to the angle range and the angle corresponding to the rotation), and because the quality of this servo is average, too much use will cause certain differences.

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project, could you please make sure that your file is formatted similar to the [template in the README](https://github.com/hackclub/winter#readme) and the information you commented would be awesome under plan! thanks :))_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey @chen98013! Just following up on:

> _(note: from a first glance of your project, could you please make sure that your file is formatted similar to the [template in the README](https://github.com/hackclub/winter#readme) and the information you commented would be awesome under plan! thanks :))_

**Comment by cfanoulis** [comment]
Heyoo! It's been a while since we last heard from you. If you're still interested in the grant, please reply to this PR (by email or GitHub) within the next 48 hours (that is, until Jan 26th) so that we can continue with the grant process - else we will be closing this request. If you have decided you will not be pursuing a grant, thank you for your time o7

**Comment by cfanoulis** [comment]
Hello! We unfortunately haven't heard back from you - so I'm closing this proposal. Thanks for taking the time to submit a winter wonderland grant request :)

**Pull request closed without merging**
