### PR TITLE
Add jianmin-chen.md

### PR DESCRIPTION
**Pull request by jianmin-chen**
## Describe your project in 1-3 sentences

I'm turning my bike into an electric bike!

## Hack Club Slack handle

`jc`

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by cfanoulis — CHANGES_REQUESTED** [review]
yesssss get that sweet revenge from the bike gods!

before you embark on your quest though
- Would your makerspace need the filament replaced? if so - pls include the cost of filament 
- Did you remember to include taxes&shipping???
- As I understand it rn, your project needs some degree of soldering (for the hall sensors->arduino etc). Do you have a soldering iron and related accessories (ie solder, wicks).
- Also, you got any cables to link this all up? I don't think I saw any

awaiting your replies

**Comment by jianmin-chen** [comment]
* My makerspace should be all good to go!
* Taxes + shipping are covered. Most of the stuff is coming from Amazon so I just put the total it gave me (shipping is free for the stuff HC is covering)
* Yep, I'm going to be doing some soldering - `Kevin Yang` in the Slack is going to be shipping me a soldering iron soon
* I got wires at home! Courtesy of the kit I got with my Arduino Nano.

**Comment by cfanoulis** [comment]
coolio! and uh... how will you charge this? I didn't see any chargers included (and I doubt this has USBC)

**Comment by jianmin-chen** [comment]
Oop... of all the things I could have forgotten. Updated in the section I'm paying for.

**Review by cfanoulis — APPROVED** [review]
And with that say, go get your revenge from the bike gods - for you shall have the coolest bike in the block

A banker will be in touch soon (after 01/17) to get you setup on hack bank. enjoy (responsibly)!

**Comment by cfanoulis** [comment]
(a banker from @hackclub/bank-ops might I add)

**Pull request merged**
