### PR TITLE
Budget Updated

### PR DESCRIPTION
**Pull request by AEZ314**
## Describe your project in 1-3 sentences

CO2 Laser cutter project.

## Hack Club Slack handle

U04FS65LKR8

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by shanecelis** [comment]
Ok. I was a little confused here, but this is a pull request to update the budget for an already approved project. Here's the [original pull request](https://github.com/hackclub/winter/pull/6).

**Comment by AEZ314** [comment]
> Ok. I was a little confused here, but this is a pull request to update the budget for an already approved project. Here's the [original pull request](https://github.com/hackclub/winter/pull/6).

Yes indeed.

**Comment by maxwofford** [comment]
Assigning @exu3 as the original reviewer on #6

**Review by exu3 — COMMENTED** [review]
Could you explain the proposed changes here? It looks like you changed some of the parts.

Also, it looks like the budget increased. Are you covering the remainder of the cost or are you working with a teammate? If so, could you have them complete the checklist to make sure they meet all requirements?

**Comment by AEZ314** [comment]
> Could you explain the proposed changes here? It looks like you changed some of the parts.
> 
> Also, it looks like the budget increased. Are you covering the remainder of the cost or are you working with a teammate? If so, could you have them complete the checklist to make sure they meet all requirements?

Of course.

**Comment by AEZ314** [comment]
> Could you explain the proposed changes here? It looks like you changed some of the parts.
> 
> Also, it looks like the budget increased. Are you covering the remainder of the cost or are you working with a teammate? If so, could you have them complete the checklist to make sure they meet all requirements?

Oh, also, yes. We're a team of 3. One of my classmates has recently met with Mel on zoom, and my other friend is on his way too.

**Review by exu3 — APPROVED** [review]
Ok great, the @hackclub/bank-ops team will review & follow up with next steps.

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
