### PR TITLE
Proposal for clock

### PR DESCRIPTION
**Pull request by CodeLongAndProsper90**
## Describe your project in 1-3 sentences

I want to build a bespoke clock: simple, easy, awesome; because just ok is not ok.

## Hack Club Slack handle

ellie

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@CodeLongAndProsper90 this is soooo cool! just to check, do you already have the materials you need to first breadboard this then eventually solder (eg. wires, soldering kit, breadboard, etc.)?

also, could you please include the cost w/ taxes and shipping in your budget?

thank you sm!

**Comment by bellesea** [comment]
> @CodeLongAndProsper90 this is soooo cool! just to check, do you already have the materials you need to first breadboard this then eventually solder (eg. wires, soldering kit, breadboard, etc.)?
> 
> also, could you please include the cost w/ taxes and shipping in your budget?
> 
> thank you sm!

heyy @CodeLongAndProsper90 hope you're doing awesome! checking in to see if you still interested in moving forward on this project?

**Comment by cfanoulis** [comment]
Hi @CodeLongAndProsper90! Thanks for your proposal. It's been a while since Belle's message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Hacky New Year!

**Comment by cfanoulis** [comment]
Hello! Unfortunately 2 days have passed, which means that I'll be closing this PR as stale. If you still wish to pursue a grant please let us know by replying to this PR before Jan. 15th

**Comment by CodeLongAndProsper90** [comment]
Yes, I would, I'm computing shipping right now

**Comment by bellesea** [comment]
> Yes, I would, I'm computing shipping right now

@CodeLongAndProsper90 great, thank you! could you please make another PR when you're ready for us to review this? you can tag me to request a review since i've already read it. thank you!

**Pull request closed without merging**
