### PR TITLE
Create  adithyakommi.md

### PR DESCRIPTION
**Pull request by adithyakommi**
## Describe your project in 1-3 sentences

Converting a cycle into an electric cycle by replacing it's rear hub with an electric hub.

## Hack Club Slack handle
kommiadithya

## Checklist before submitting proposal:

- [yes ] I am a current high school student (or younger).
- [yes ] I have submitted an RSVP at <https://hackclub.com/winter>
- [yes ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [yes ] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by adithyakommi** [comment]
I will be collaborating with Nishant Mekala(email-mrkickftw@gmail.com) in this project.

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: are you following any guides of sorts for this?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by adithyakommi** [comment]
Hey @bellesea ,
I haven't used any particular guide, but could try to share a similar video concerning the same. I'm aware of the process as I've helped my friend do the same
I have confirmed w/ a professional cycle mechanic about these parts.
Modifying would be slightly tough in this case mainly because -
1) With aliexpress and other similar retailers being banned in india and importing any motor/battery having issues related to customs, my options are limited. Also, certain motors have a weight capacity.

Please do let me know if you have more questions!

**Comment by bellesea** [comment]
@adithyakommi thank you! we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by alhardwarehyde — APPROVED** [review]
This is a great looking project! Love that you tied it to your love of cycling! @hackclub/bank-ops

**Review by hackliv — APPROVED** [review]
hey @adithyakommi this is so amazing! I loved the bit of background you shared too 😁🚲 I'm dming you now on Slack to see if we could find some time to meet and chat more about the grant!

**Comment by hackliv** [comment]
hey @adithyakommi I couldn't find you with that Slack handle! would you be able to share your user ID?

**Comment by adithyakommi** [comment]
> hey @adithyakommi I couldn't find you with that Slack handle! would you be able to share your user ID?

Hey @hackliv, sorry!, i've changed it, please try now

**Comment by hackliv** [comment]
> > hey @adithyakommi I couldn't find you with that Slack handle! would you be able to share your user ID?
> 
> Hey @hackliv, sorry!, i've changed it, please try now

I was still unable to find you. 😕 Is it still @ kommiadithya?

**Comment by adithyakommi** [comment]
Hey, yes it is.
I've dmed you!

**Comment by nishanthx0509** [comment]
Describe your project in 1-3 sentences

Converting a cycle into an electric cycle by replacing its rear hub with an electric hub.

Hack Club Slack handle

nishm0507

Checklist before submitting proposal:

[yes ] I am a current high school student (or younger).
[yes ] I have submitted an RSVP at https://hackclub.com/winter
[yes ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[yes ] I have self-reviewed my project proposal.

**Pull request merged**
