### PR TITLE
Cooking Range Heat Regulator

### PR DESCRIPTION
**Pull request by LexHarie**
## Describe your project in 1-3 sentences
I'm building a fire regulator for our cooking range so that I can cook rice and other food unsupervised.

## Hack Club Slack handle
`@Lex Harie Pisco`

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project it looks super cool but potentially dangerous haha, do you have any safety built into it? also, are you following any guides of sorts?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by LexHarie** [comment]
> heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on.
> 
> to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)
> 
> and fyi, we're looking for projects where/that:
> 
> * you can spend at least 10 days building (from Feb 14th to 23rd)
> * you are able to modify or make your own in some ways
> * you can learn something new from
> * involves working with electronics or software on a lower level than a pre-assembled kit of parts
> 
> and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits).
> 
> _(note: from a first glance of your project it looks super cool but potentially dangerous haha, do you have any safety built into it? also, are you following any guides of sorts?)_
> 
> our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR.
> 
> if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

I major in electricity in my high school, and we have safety equipment at school. It is convenient since the tools I need are in my school's electrical shop. Well, I have had experience with danger, I once almost burn an electrical shop on fire, when I short circuit my three-way distribution electrical circuit and it was traumatizing, so rest assured that I'm full safety mode.

**Comment by LexHarie** [comment]
Hello Belle,

I just replied on GitHub, lol. I don't know where to formally address this,
is it on Slack? Gmail? or GitHub. Anyways, I would love to get some
feedback right away.

Best,
Lex

**Comment by bellesea** [comment]
@LexHarie omg haha, but that's good to know! thanks :)

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey @LexHarie! Love the idea 👏

What's the thinking behind using a Pi 4 over a NodeMCU or a PicoW?

**Comment by LexHarie** [comment]
Hello Sam,

I'm not familiar with those, this is just what my friends have suggested. I
do know that I can utilize the hack club slack channel for more support or
to ask questions, I will do research about it.

Best,
Lex

**Comment by sampoder** [comment]
Sounds good! Want to circle back in 24hrs?

**Comment by LexHarie** [comment]
Alright, Let's go! Thanks for your consideration Sam.

**Comment by bellesea** [comment]
hey @LexHarie just checking in to see if you've made some progress with your research? thank you sm!

**Comment by LexHarie** [comment]
Hello @bellesea and @sampoder, sorry for the late reply. I did my research and I would go with either STM32 or NodeMCU. Not to be petty, but I compare my project to other people here, and I think my project is kinda basic. So it took me a long time to come up with something cooler, and I thought about having a remote-controlled balloon shaped like a dolphin. This dolphin would have a glider, and propeller, and would sense the temperature, humidity and the atmospheric pressure of the environment. The propeller and glider would help me control the balloon the balloon's altitude and direction. Then I would use STM32 or NodeMCU or Arduino UNO for my remote-controller. And for the temperature and humidity sensor, I can use the sensors I owned, and a NodeMCU to send the data of the environment. 

Should I stick with my original project or is the new one that I came up with is way cooler?

**Comment by sampoder** [comment]
Go with your gut TBH! They both sound great.

**Comment by bellesea** [comment]
hey @LexHarie i'm wondering, are you still interested in moving forward with this PR? if so, can you please try and update your PR by this Friday or latest this weekend? If not, we might not have enough time to move forward with the grant and allow you to get your parts in time for the event! thanks :)

**Comment by sampoder** [comment]
@LexHarie: this wasn't meant to close, it wasn't pointed to `main` however.

**Comment by sampoder** [comment]
Can you point your PR to the main branch?

**Pull request closed without merging**
