### PR TITLE
@wardecs - Keevan Leech grant application

### PR DESCRIPTION
**Pull request by wardecs**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by wardecs** [comment]
Note: please see the latest commit, updated the budget.

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @wardecs this is soooo awesome! i'm wondering, how do you plan on moving the position of the webcam with the servos? like are you creating some sort of custom mount or holder and how would the whole servo/webcam thing stay on top of your computer?

also, just to check do you already have the breadboard and jumper wires? also, could you please update the link for the heat shrink tubing? thank you sm!

**Comment by wardecs** [comment]
@bellesea 
Yeah, so I plan on making some sort of custom 3D printed mount for it, so I can place the mount on the motors to create a rotating mechanism. The webcam wouldn't actually clip onto my computer monitor. I have a shelf directly above my monitor which I will be putting the whole system on. I just double checked & I already have jumper wires and a breadboard. I just updated the new link for the shrink tubing!

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @wardecs thanks for the additional context! could you please add under plan what you wrote about designing and printing a custom holder + it being on another shelf? btw, what's the role of the USB C Hub?

thank you!

**Comment by wardecs** [comment]
Absolutely @bellesea I just updated my description. The USB-C hub is for me to connect the arduino to my macbook because I can't use any USB devices at the moment.

**Review by bellesea — APPROVED** [review]
@wardecs this is super awesome (& good luck with the hackathon)!!

an awesome member of @hackclub/bank-ops will be reaching out soon w/ next steps :)

**Review by daisybanks — APPROVED** [review]
Hi @wardecs! This project sounds wicked cool and I love how excited you are to create something that combines your interests and passions into something thats both unique and challenging as that's what this event is all about! I'm dming you now on Slack to talk abut next steps in getting you on Bank and getting you your grant. :)

**Pull request merged**
