### PR TITLE
IOT Display Device

### PR DESCRIPTION
**Pull request by CreNiruta**
## Describe your project in 1-3 sentences

 I am building a IOT based Display Device to display content from Internet

## Hack Club Slack handle
niruta dangi

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project, this looks awesome and i'm wondering: do you need a compatible power supply? are you referencing any sort of guide for this?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by Sheepy3 — CHANGES_REQUESTED** [review]
Hey! Interesting project :) but there's a couple issues I found:
- The E-Ink Displays are out of stock
- lack of Inclusion of shipping info

For the shipping info, what you can do is add everything to your cart, fill out your billing address information, and you'll get shipping prices on step 3. you can add that to this plan without proceeding.

Additionally, I have a few questions. What Rasberry PI do you have, and how do you intend to connect 3 E-ink displays all at once?

**Comment by bellesea** [comment]
hey @CreNiruta it's been a few days since sheepy3's request for changes :) i'm wondering, are you still interested in moving forward with this PR? we look forward to reviewing this soon so you can get your parts in time for the event! thanks :)

**Comment by CreNiruta** [comment]
Sure. i will update it today. Actually since the product is out of stock on adafruit, I am searching alternative store and store shipping to nepal is difficult to find. I will search more and update it by today.

**Comment by CreNiruta** [comment]
Hello. I searched a lot but couldn't get the E-Ink Display Hat for Raspberry Pi. Currently its out of stock on Adafruit and couldnt find elsewhere.. I only managed to get one product in stock from adafruit.
What shall I do ? Can you please assist me?

**Comment by bellesea** [comment]
hey @CreNiruta would you be able to change your display to a non-e-ink one?

**Comment by CreNiruta** [comment]
Yes sure but Can you help me find compatile Raspberry Pi Display?

**Comment by Sheepy3** [comment]
> Yes sure but Can you help me find compatible Raspberry Pi Display?

would either of these work?
[](https://www.amazon.com/waveshare-7-5inch-HAT-Raspberry-Consumption/dp/B075R4QY3L
[]()https://thepihut.com/collections/epaper-displays-for-raspberry-pi)

alternatively, you could try contacting this seller:
[](https://himalayansolution.com/product/raspberry-pi-7-inch-lcd)
[](https://himalayansolution.com/product/raspberry-pi-5-inch-lcd)

**Comment by CreNiruta** [comment]
Yes the PiHat Website has exactly what I need from the link you sent but i found that it doesn't ship to my country.
I think I had to switch to normal display instead of piHat EInk display from the local stores instead.

**Comment by CreNiruta** [comment]
I updated the product to get a normal pi display from normal store. Can you please have a look into it. I wanted to try E-Ink but none of the other sites shipped here so switched to another display.

**Review by Sheepy3 — APPROVED** [review]
looks good, approved! :)

**Review by hackliv — APPROVED** [review]
this is v v cool @CreNiruta! 😁 I'm dming you now on Slack to set up some time to meet and talk about next steps for the grant.

**Pull request merged**
