### PR TITLE
Create gamer-1478.md

### PR DESCRIPTION
**Pull request by gamer-1478**
## Describe your project in 1-3 sentences
I am building an open-source digital chess board that you can either play with multiplayer, or single-player or use at tournaments as a replacement dgt board. the designs, schematics and other stuff will be available for everyone to use. 

## Hack Club Slack handle

gamer1478

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
This is an awesome project, thanks for submitting @gamer-1478!

I had a couple questions to address before approving, but the intent of the project is def in the spirit of the grant.

I noticed you're running with both an Arduino Mega and a Raspberry Pi4 & wanted to check if that was intentional. It seems like you could drive the screen, buttons, and hall effect sensors from just the GPIO header of the Raspberry Pi. Is there a particular thing you need both of them for?

Also, did you mean to include both the magnetic chess set and the mat chess set in your budget? It seems like the plan just includes use of the magnetic one.

Let me know and you can re-request review!

**Comment by gamer-1478** [comment]
@maxwofford Hey max, I hope you're doing well. I just wanted to follow up on the pull request. I was wondering if you could take a look at it when you have a chance. Let me know if you need any additional information from me.

Thanks in advance!

**Review by maxwofford — APPROVED** [review]
Hey @gamer-1478, sorry for the delay here. That answered all my questions! I'm going to approve this. @hackclub/bank-ops will be in touch shortly to send the funding!

**Review by MelSmith104 — COMMENTED** [review]
hey @gamer-1478! this is so cool and i love that you're planing to opensource it! i love chess and this project looks like so much fun :) im dm'ing you right now to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
