### PR TITLE
Jungle Shoot

### PR DESCRIPTION
**Pull request by Shourya-maker-lab**
## Describe your project in 1-3 sentences

We will build a rover to help us get a picture of wildlife in dense woods near our place. We really like wildlife observation. We are excited about this project as we will learn new tech and real-life hardware skills. This will also help us to motivate other people in our locality to see the real beauty of nature and in campaigns to protect wildlife.

## Hack Club Slack handle

Shourya Pandey

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Arpan-206** [comment]
You should tag your team members or have them comment the checklist since the budget is quite significantly above $250, if you have other teammates that is.

**Comment by Shourya-maker-lab** [comment]
okay i will surely do thanks.

**Review by maxwofford — CHANGES_REQUESTED** [review]
You mention "we" but I only see one username on the project. Could you have any collaborators comment in this thread?

Love the youtube channel. Hope to see the build there soon!

This project looks awesome! I wanted to ask if the design for the rover comes from a tutorial or is being made completely from scratch.

What's the reason for using an uno & a mega & a pi? Could you control this just from the pi? Or use one arduino?

Also, I noticed you're using a 3d printer to build an enclosure for the robot. Do you need the rpi case if you're putting it inside the 3d printed enclosure anyways?

I'm going to mark this as "requested changes", but once your friends comment on this I can mark approved!

**Comment by Shourya-maker-lab** [comment]
Hi, 
thankyou for viewing my channel. At first, I was thinking that the mega is a good option but then I realized that uno can do the same stuff here and as I made that list earlier I will edit that. And actually, I am not very proficient in micro python or c so making code only for pi is a bit complicated for me that is why I thought Arduino ( my best buddy) is the best choice.
As far as the RPI case we are trying to build a 360 rotatable camera so we have to mount raspi outside the body.

**Comment by Shourya-maker-lab** [comment]
And as per my friend's comment, I informed them to do that asap. The designs for the rover are completely from scratch.

**Comment by 4nge1ina** [comment]
## Describe your project in 1-3 sentences

We are going to build our own eBook Reader (like Kindle) using the Raspberry Pi with a custom OS image, books store etc.
I couldn't see anyone doing this online, so can't attach many sources. Kinda figuring this out on our own.

## Hack Club Slack handle

4nge1ina

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by yoyoGreatcoder** [comment]
## Describe your project in 1-3 sentences

We will build a rover to help us get a picture of wildlife in dense woods near our place. We really like wildlife observation. We are excited about this project as we will learn new tech and real-life hardware skills. This will also help us to motivate other people in our locality to see the real beauty of nature and in campaigns to protect wildlife.

## Hack Club Slack handle

Aryan Guar

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by 4ryamanTripathi** [comment]
## Describe your project in 1-3 sentences

We will build a rover to help us get a picture of wildlife in dense woods near our place. We really like wildlife observation. We are excited about this project as we will learn new tech and real-life hardware skills. This will also help us to motivate other people in our locality to see the real beauty of nature and in campaigns to protect wildlife.

## Hack Club Slack handle

Aryaman Tripathi

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by Shourya-maker-lab** [comment]
Hi, 
We have made all the change's on the list and all the members are present in the thread.

**Comment by Shourya-maker-lab** [comment]
@maxwofford Hi I made all the changes as required and all the team members are here can you pls re-review it. Thank you in advance.

**Comment by Shourya-maker-lab** [comment]
team members :- @4nge1ina @yoyoGreatcoder @4ryamanTripathi  @Shourya-maker-lab

**Review by maxwofford — APPROVED** [review]
Awesome, thanks for answering all the questions. Excited to see it once you have something built!

The @hackclub/bank-ops team will be in touch to send the funds.

**Review by MelSmith104 — COMMENTED** [review]
hey everyone! this is so cool! i love that you're building your own E-reader :) im dm'ing you on slack to get the process rolling for the winter hardware grant!

**Comment by Arpan-206** [comment]
@MelSmith104 E-reader ? Are you sure you didn't mix up projects?

**Comment by MelSmith104** [comment]
@Arpan-206 oh shoot! somehow i had two tabs opened up and i did mix them up! i dm'ed @Shourya-maker-lab to get that cleared up. thank you for pointing that out!

**Comment by Shourya-maker-lab** [comment]
hi

**Comment by Arpan-206** [comment]
@MelSmith104 happens to the best of us, haha!

**Comment by Shourya-maker-lab** [comment]
update the list

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
