### PR TITLE
Create KoKoOogit.md

### PR DESCRIPTION
**Pull request by KoKoOogit**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by KoKoOogit** [comment]
My slack username: Ko Ko Oo

**Review by bellesea — CHANGES_REQUESTED** [review]
@KoKoOogit this is super cool!

i have a few questions:
- since you don't have access to a 3d printer how do you plan on creating a frame? maybe you could consider building something by hand?
- i believe the items you're connecting can just be plugged in? if so, what's the role of the soldering kit?
- does your budget include shipping and taxes?

could you please update your response to those by adding them as details to your file?

thank you!

**Comment by KoKoOogit** [comment]
Hi @bellesea  thanks for your comment. I have made changes to my readme. I also accidentally created a #249 while I was finding how to update this pull request since it is my first time with pull requests. Thanks!

**Review by bellesea — COMMENTED** [review]
@KoKoOogit thank you sm for pushing the changes! could you please try to include the shipping and taxes (since we only offer up to the amount written in your budget)?

also, could you please move the extra details under ## plan instead?

and, do you need another header? it looks like the kit you have includes one 20 pin header but the bonnet requires 2x20 pin headers?

please let me know if you need any help with this, thank you!

**Comment by KoKoOogit** [comment]
@bellesea  Thanks again for the updates. I have made a few changes to the components - Pi Zero W. Instead of using Pi Zero 2W, I decided to use just Pi Zero W which is more affordable. Thanks!

**Review by bellesea — APPROVED** [review]
hiii @KoKoOogit this looks awesome and can't wait to see you build this :)

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Comment by KoKoOogit** [comment]
@bellesea  Thanks!

**Review by hackliv — APPROVED** [review]
what's up @KoKoOogit !! this looks so cool! 😃 I'm dming you now on Slack about getting set up with the grant on Hack Club Bank.

**Pull request merged**
