### PR TITLE
Template adjustments and error fixes (SPOILER: its a lot them)

### PR DESCRIPTION
**Pull request by ZeroQLi**
Oh boy this is a long one, i've made several fixes to the md files of the repo for convenience (and me)

Most of the file changes are just adjusting the project names (removing the `#project name` header with the actual project name)

and some of them are YAML fixes and and file name changes (like AHussein04.md and camdan-me.md, the latter of which is a complete name change since the original file name is not a valid username)

feel free to review and adjust to your needs.

_PS: ya'll owe me a post card lmao _(/j)__

### CODE REVIEW

**Comment by ZeroQLi** [comment]
PSA: DO NOT PUSH IT YET

there's still fixes i haven't committed yet

**Comment by ZeroQLi** [comment]
duplicate, closing

**Comment by exu3** [comment]
> PS: ya'll owe me a post card lmao (/j)

I just put one in the mail to you!

**Comment by ZeroQLi** [comment]
very cool
image

**Pull request closed without merging**
