### PR TITLE
Update Val171.md

### PR DESCRIPTION
**Pull request by Val171**
Well, encountered a major hurdle, the website I was ordering the chassis from turned out to be a scam so I'll be making the chassis out of balsa wood and cardboard. The electronics remain more or less the same. I am leaving a buffer incase I need more parts. A lot of these items are currently on discount thus prices may change in the next few days depending on how long it takes for this to get approved.

_Project proposals are no longer being accepted as of January 15th, 2023 23:59 EST._

If this a bug fix, documentation update, or other, please describe the purpose of this pull request below:

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @Val171 can you please put your budget in USD? also, are you referencing anything for the design of your car? thank you sm :)

**Comment by Val171** [comment]
> hey @Val171 can you please put your budget in USD? also, are you referencing anything for the design of your car? thank you sm :)

Yeah I've got some schematics for the dimensions. Changes the design to a tesla Cybertruck which is basically a pentagon so should be easier. Budget do you mean the new one? Its about $163.ive ready received all the funds though from mel. So after converting to inr it leaves me with around 6.5k or $80. I was thinking of using that if I need anything else. While I'm actually building it. If I'm left with anything I can send it back. I'm so sorry for this. 
I really thought the website was legit.

**Review by bellesea — APPROVED** [review]
@Val171 ahhh cool! this looks good! no need to apologise, it's hard to know what's trustable :( 

can you please still list the USD conversion in your budget (you can put both if you want) so it's easier for people to generally understand how much it cost you?

also, what's the reason for having different gear tooths for your pinion & spear gears?

and oh wow the cybertruck looks very cool, can you please add the link in your file?

just to confirm, you already have the money and are just requesting to change what you spend it on right?

**Comment by Val171** [comment]
@bellesea Thanks! 
1) done👍
2) Different number of gear teeth lead to change in gear ratio. A bigger pinion or smaller spur gear makes the vehicle have more top speed, at a decrease in acceleration.
Smaller pinion and bigger spurs give more acceleration. 
3) Thanks again😅 and done
4) yes

**Comment by MelSmith104** [comment]
thank you!!

**Pull request merged**
