### PR TITLE
added mine

### PR DESCRIPTION
**Pull request by davidarogunre**
## Describe your project in 1-3 sentences
Chat Robot Implemented with Chat GPT-3 is an exciting project. My project will be to create a chatbot that can interact with users in a natural, conversational way, powered by the cutting-edge GPT-3 technology. I am excited because I will learn how to use hardware components to build the chatbot The chatbot will be able to respond to users with personalized, human-like conversations, making it a great way to engage users in an interactive experience.

## Hack Club Slack handle
@folucodes

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hiii @davidarogunre this is awesome!! super cool to see this go from a slack message to this PR haha :)

i'm wondering, do you need to also purchase a SD card and power supply?

also, could you please include shipping and taxes within your calculations?

thanks!

**Comment by davidarogunre** [comment]
@bellesea Yeah I forgot, I do need an sd card and power supply and yes, taxes and shipping have been included into my current calculation

**Comment by davidarogunre** [comment]
@bellesea I have pushed changes to the list and every prices for  each item contains the shipping and taxes added to the price

**Comment by bellesea** [comment]
> @bellesea I have pushed changes to the list and every prices for each item contains the shipping and taxes added to the price

@davidarogunre thank you so much! one more small thing, how do you plan on programing your pi? will you be doing a headless set up (if so do you need an SD card reader or smth) or do you have a monitor, keyboard, and mouse w/ the relevant cables that you can connect?

**Comment by davidarogunre** [comment]
I was thinking of using python to program it using https://realpython.com/python-raspberry-pi/ tutorial

**Review by bellesea — APPROVED** [review]
@davidarogunre can't wait to see you work on this :) a fabulous member of @hackclub/bank-ops will be reaching out soon w/ next steps!

**Comment by davidarogunre** [comment]
Thanks alot, I really appreciate it, I will be waiting

**Review by bellesea — APPROVED** [review]

**Review by MelSmith104 — COMMENTED** [review]
hey @davidarogunre ! i can't wait to see charlie come to life :) this project sounds really awesome and i love how much thought you've put into it. im dm'ing you on slack right now so that we can we chat about getting you set up on Bank for the grant! i also can't wait to hear more about your plan!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
