### PR TITLE
GalaxyGamingBoy's Proposal | Plant Location Chooser

### PR DESCRIPTION
**Pull request by GalaxyGamingBoy**
## Describe your project in 1-3 sentences

I am building a Plant Location Chooser to help me and my family plant flowers in a location that would be beneficial for the plant to grow.

## Hack Club Slack handle

marios_mitsios

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@GalaxyGamingBoy this project sounds super exciting!! to check, have you factored in shipping costs and taxes for your budget?

**Comment by GalaxyGamingBoy** [comment]
> @GalaxyGamingBoy this project sounds super exciting!! to check, have you factored in shipping costs and taxes for your budget?

Yes! I live in Europe and taxes are included in the price, also I specifically chose the store because all orders above 80$ get free shipping.

**Comment by GalaxyGamingBoy** [comment]
I also added a storage box to help storing the components when not in use to avoid any avoidable damage to them, I can remove it if you want. Thanks!

**Review by bellesea — APPROVED** [review]
@GalaxyGamingBoy thank you so much for the quick changes! this looks awesome and we can't wait to see this sprout :) awesome peeps on the @hackclub/bank-ops team will reach out w/ next steps!!

**Review by hackliv — APPROVED** [review]
Hey @GalaxyGamingBoy this sounds so cool! 🤩 I'd love to hear more about it!!

Dming you now on Slack about setting up a call together and getting onto Hack Club Bank for the grant!

**Pull request merged**
