### PR TITLE
Create zoya-hussain.md

### PR DESCRIPTION
**Pull request by zoya-hussain**
## Checklist before submitting proposal:

- [✓] I am a current high school student (or younger).
- [✓] I have submitted an RSVP at <https://hackclub.com/winter>
- [✓] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✓] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by zoya-hussain** [comment]
hi! yes, i'll be referencing a guide on a previously made DIY project called the [Ultimate Writer](https://alternativebit.fr/posts/ultimate-writer/).

**Comment by bellesea** [comment]
> hi! yes, i'll be referencing a guide on a previously made DIY project called the [Ultimate Writer](https://alternativebit.fr/posts/ultimate-writer/).

great! can you please link/cite this in your file? thanks sm :)

**Review by sampoder — APPROVED** [review]
@hugoyhu check this out!

@zoya-hussain, love the project idea! welcome to a winter hardware wonderland ❄️ ☃️

**Review by arianna-m — APPROVED** [review]
Hi @zoya-hussain! WOW, I absolutely love this idea! I really like how you told us about how much you love writing and how your typewriter will keep you from getting distracted. Next steps for us would be to move communications over to Slack so we can move forward! We can schedule a Zoom call, so I can explain how you get the grant and share with you the fiscal sponsorship contract which you'll have to sign with a parent/guardian. Looking forward to working together! :)

**Pull request merged**
