### PR TITLE
Update: Create RishitaxGhosh.md (#378)

### PR DESCRIPTION
**Pull request by RishitaxGhosh**
This reverts commit 4b226e2d615f4493afed09af824581d25044f4b0.

_Project proposals are no longer being accepted as of January 15th, 2023 23:59 EST._

If this a bug fix, documentation update, or other, please describe the purpose of this pull request below:

Updated Budget List: 

Hi I was facing troubles placing order on the other products as prices were hiked due to limited availability, sold out kit item and late delivery. 
I made a new budget list keeping in mind delivery time and mentioned individual items (since the previously mentioned electronics kit was sold out): 

1. nozzle $15 - https://amzn.eu/d/bFH9P89
2. full kit of breadboard + resistors + capacitors $55 - https://amzn.eu/d/1khwAYM
3. Soldering kit $25 - 
https://amzn.eu/d/eqnEKAP
https://amzn.eu/d/fpEr1oN
4. Multimeter $45 - https://amzn.eu/d/8MgIdGv
5. Arduino $35 - https://amzn.eu/d/jhKUW3v
6. Distance Sensor (x3) - $15  https://amzn.eu/d/0AyCLu5 
7. 9V battery (x3) - $15 https://amzn.eu/d/63lbNmu
8. Battery Connector  - $5
https://amzn.eu/d/feG4odT
https://amzn.eu/d/cFqelHw
9. On/Off Switches - $5 https://amzn.eu/d/0jx4mlr
10. Motor Shield - $10 
https://amzn.eu/d/ay4QF8W 
11. PLA Filament (x2) - $40
https://amzn.eu/d/7a100ux
https://amzn.eu/d/0ClkuZv
total: $265 + $60 (expected mining fee) = $325 
I would be requiring this amount since the balance left is $1 on my amazon pay

### CODE REVIEW

**Comment by cfanoulis** [comment]
Hey! I see you deleted your proposal file - I'm going to need you to restore that and edit your budget table with your new materials - thanks :)

**Comment by RishitaxGhosh** [comment]
Hi, this is my original PR: https://github.com/hackclub/winter/pull/378 
I am not sure what has been deleted

**Comment by cfanoulis** [comment]
this is what I'm seeing on my end - did you forget to push an update?image

**Comment by RishitaxGhosh** [comment]
Screenshot 2023-02-09 at 12 07 42 PM

Hi this what is appearing on my page

**Pull request closed without merging**
