### PR TITLE
Nvidia jetbot

### PR DESCRIPTION
**Pull request by parthagarwal2005**
## Describe your project in 1-3 sentences

 I am building Nvidia jetson Nano Powered Jetbot.

## Hack Club Slack handle
Parth Agarwal

 - [x] I am a current high school student (or younger).
 - [x] I have submitted an RSVP at https://hackclub.com/winter
 - [x] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
 - [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Arpan-206** [comment]
Isn't it already an official tutorial at the Jetson page?

https://www.nvidia.com/en-in/autonomous-machines/embedded-systems/jetbot-ai-robot-kit/

**Comment by parthagarwal2005** [comment]
Yes their is.
Can we not build from tutorials?

**Comment by Arpan-206** [comment]
> Yes their is. Can we not build from tutorials?

Not directly afaik.

**Comment by parthagarwal2005** [comment]
@bellesea would you please review my PR? As I need to order the parts early.

**Comment by bellesea** [comment]
> @bellesea would you please review my PR? As I need to order the parts early.

hey @parthagarwal2005 sorry we have a backlog of PRs to review but will try to review yours within 48 hours! thanks for your patience :) and although it is ok to follow a tutorial, we highly recommend that you modify it in some way to make it your own, that will make your project more likely to be approved hehe! thank you.

**Comment by parthagarwal2005** [comment]
Sure, I'll make sure to modify some procedures and also add a personal touch to the project.

**Comment by bellesea** [comment]
> Sure, I'll make sure to modify some procedures and also add a personal touch to the project.

hey @parthagarwal2005 i'm wondering, would you like us to review the project as is or do you have plans to add to it? both are ok hehe :) please let me know :)

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @parthagarwal2005 this is super cool! 

a few questions:
- i noticed in the [bill of materials](https://jetbot.org/master/bill_of_materials.html) that there's a piOLED header, do you need that?
- do you have access to a 3d printer and can print out the chassis & camera mount?
- do you have any ideas for expanding beyond building the jetbot? could be a hardware adjustment or something you want to make your jetbot do that isn't part of the ready guide :)

thank you!

**Comment by parthagarwal2005** [comment]
Hy @bellesea I have the required piOLED header, so I don't need that.
As for the 3D printer I will get it arranged with the help of my brother.
Or can I ask my friend to join me in the project, do we get 250 per person or for a single project?

**Comment by parthagarwal2005** [comment]
Yes I have plans to expand the jetbot that will inculde converting the jetbot into a AI puppy that will help people by entertaining them.
I am currently figuring out the plan to do that.

**Comment by bellesea** [comment]
> Hy @bellesea I have the required piOLED header, so I don't need that. As for the 3D printer I will get it arranged with the help of my brother. Or can I ask my friend to join me in the project, do we get 250 per person or for a single project?

if a friend joins you we could increase the budget up to 500 (250 per person) but we'd ask that you perhaps 3d design your own chassis (can be modified from existing ones), like if you were to make it similar to a puppy that would work :) please let me know what you decide :)

(can you please add to your files that you already have the header? thanks!)

**Comment by parthagarwal2005** [comment]
Sure @bellesea My friend will be joining in soon. Also I'll add 3d printer tomorrow morning, And about vague plans for modifying the Chassis, I'm still figuring that out.

**Comment by parthagarwal2005** [comment]
@bellesea Sorry But my friend would not be joining and I couldn't find a 3d Printer suitable and under budget for the project, but I'll 3d print the required chassis as of now using my brother's 3d printer.
And I'll make sure to change the chassis to look like a puppy.

**Comment by bellesea** [comment]
> @bellesea Sorry But my friend would not be joining and I couldn't find a 3d Printer suitable and under budget for the project, but I'll 3d print the required chassis as of now using my brother's 3d printer. And I'll make sure to change the chassis to look like a puppy.

@parthagarwal2005 no worries at all! thank you :)

**Review by daisybanks — APPROVED** [review]
Hi @parthagarwal2005! This project sounds super cool and i can't wait to hear more about it! I'm dming you now on Slack so we can talk about the next steps for getting you on Bank and getting you your grant! :)

**Comment by parthagarwal2005** [comment]
Hy @bellesea Looks like the nvidia jetson kit in not available in my country or is highly expensive😥😥😥. Is it possible to change my project at this time?

**Comment by Arpan-206** [comment]
Hey don't be disheartened, try getting a new team member onboard. Maybe use this as an opportunity to teach a friend/sibling a few things or just work with them?

**Comment by parthagarwal2005** [comment]
@Arpan-206 Thanks, I think I'll figure something out.

**Comment by bellesea** [comment]
hey @parthagarwal2005 (saw the email notification of your message) yep if you'd like to change your project please make another PR by Jan 15 at 11:59pm ET and we'd be happy to review again :) or if your project is similar but you're changing some components, feel free to just update this PR and re-request a review from me! thanks :)

**Pull request merged**
