### PR TITLE
Humidifier with moisture sensor

### PR DESCRIPTION
**Pull request by InformationAntti**
## Describe your project in 1-3 sentences

I am building an air humidifier with an adjustable humidity level.

## Hack Club Slack handle

InformationAntti

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
Hey @InformationAntti, thanks for submitting! I can't wait to see the case you end up designing for this. I've been 3d printing for a little while but haven't done much work designing my own parts yet.

This looks great & I love that you're adding a display to customize the project just that much more.

**Comment by InformationAntti** [comment]
Thank you for your interest in my project @maxwofford! How will we proceed with getting the grant?

**Comment by maxwofford** [comment]
@InformationAntti someone from @hackclub/bank-ops will reach out!

**Comment by InformationAntti** [comment]
Good to know. Thank you!

**Comment by InformationAntti** [comment]
Hi! I noticed that there were like 20 other Vincents in the slack so I have changed my Slack handle to InformationAntti in order to avoid confusion.

**Review by hackliv — APPROVED** [review]
Hey @InformationAntti this sounds awesome! I'm dming you now on Slack to continue chatting. 😊

**Pull request merged**
