### PR TITLE
Robotic arm

### PR DESCRIPTION
**Pull request by busterbob64**
## Describe your project in 1-3 sentences
I'm building a robotic arm powered by Google Coral.

## Hack Club Slack handle
@<wbr>Sarah.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by garyhtou** [comment]
Hey @busterbob64, just checking in to see how you're doing with this project. Have you gotten a chance to finish this up and self-reviewed your project proposal?

**Comment by busterbob64** [comment]
Still working on it!

**Comment by bellesea** [comment]
hey @busterbob64 no rush but just FYI proposals chose Jan 15 at 11:59pm ET so if you're still interested in moving forward  please mark this PR as ready for review by then :) thank you sm!

**Comment by busterbob64** [comment]
Hi! Unfortunately, I've decided not to. I'm not signed into GitHub right
now, so if you could close the PR for me that'd be great.

Thanks, and sorry.

**Comment by bellesea** [comment]
@busterbob64 no worries at all! done, thank you :)

**Pull request closed without merging**
