### PR TITLE
Face Following Robot

### PR DESCRIPTION
**Pull request by bikash159**
## Describe your project in 1-3 sentences

A Face following robot track a human face and follows human movement and changes position.

## Hack Club Slack handle

Bikash Gupta

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by tinuh** [comment]
Hey @bikash159, a face-following robot seems like a really cool idea! Is there any guide you'll follow or reference for your build? Also, I noticed that you'd be using wires to connect, do you plan on using a soldering iron to connect the battery holder to the board? If so make sure to add that to your budget. I also noticed that the batteries that you'll be using use different connectors than your battery holder, if this was a typo make sure to replace this item in your budget with the right batteries.

**Comment by bikash159** [comment]
Yes there is a really descriptive tutorial made DIY BUILDER in YouTube, I was quite inspired with it. 

The battery holder will be directly connected to the motor shield driver power pin connectors. 

Right now, it is difficult to get fresh 18650 batteries on amazon so I have use a different connector batteries but I will just need to remove the connector to fit that in the battery holder, so no problem there.

**Comment by tinuh** [comment]
Is there anything different or unique that you’ll be doing from the DIY Builder guide?

**Comment by bikash159** [comment]
Sure I am going to implement a Traffic Sign Recognition too in the Robot. In that order, it will have two operational modes one will be human following robot and other will be  Traffic Sign Recognition Robot.

**Comment by bikash159** [comment]
I have added the unique thing!

**Review by tinuh — CHANGES_REQUESTED** [review]
Hey @bikash159, both of the things you plan on doing are DIY Builder projects for this item. I recommend that you make a variation of this project that really makes it your own. Also, how exactly do you plan on using the acrylic sheet to create the body for your robot?

**Comment by bikash159** [comment]
I am also working on a program that will be able to learn movement of different objects and move according to its movements.
To make the chassis I will first cut Acrylic sheet in a rectangular shape using appropriate tools which I already own.

**Comment by tinuh** [comment]
Hey @bikash159, extremely sorry for the late response time, an awesome member of @hackclub/bank-ops will reach out to you soon regarding further steps with this grant. Looking forward to what you create!!!

**Review by tinuh — APPROVED** [review]

**Review by daisybanks — APPROVED** [review]
Hi @bikash159! This robot sounds really cool and I love that it's main job would be to help people and assist in variety of ways! I'm dming you now on Slack to talk about next steps in getting you on Bank and getting you your grant. :)

**Pull request merged**
