### PR TITLE
Update AEZ314.md (we'll collab)

### PR DESCRIPTION
**Pull request by Alcatraz-jan**
I'm AEZ314's friend, we'll be collaborating on this.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Alcatraz-jan** [comment]
@AEZ314 hey bud!

**Comment by AEZ314** [comment]
> @AEZ314 hey bud!

Hey drok. Welcome to the party. They will soon merge this.

**Comment by AEZ314** [comment]
@MelSmith104 Hey Mel. This is my friend Doruk, or drok as he affectionately calls himself :) We'll be working on our CO2 laser cutter together.

**Review by bellesea — CHANGES_REQUESTED** [review]
hii @Alcatraz-jan love the fun vibe haha but could you please add one more thing to the file:
in line 2 where it's 
`name: "@AEZ314"
`

please do
`name: ["@AEZ314", "@Alcatraz-jan"]
`

thanks!

**Comment by Alcatraz-jan** [comment]
> hii @Alcatraz-jan love the fun vibe haha but could you please add one more thing to the file: in line 2 where it's `name: "@AEZ314" `
> 
> please do `name: ["@AEZ314", "@Alcatraz-jan"] `
> 
> thanks!

'kay i handled it.

**Comment by bellesea** [comment]
thank you!!

**Review by bellesea — APPROVED** [review]
love that y'all are working together :)

**Comment by MelSmith104** [comment]
hey @Alcatraz-jan ! can you send me your slack id so that we can move forward with adding you to the project :)

**Comment by Alcatraz-jan** [comment]
> y @Alcatraz-jan ! can you send me your slack id so that we c

U04JXR6VC0Y here u go

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
