### PR TITLE
println("ZeroQL's project")

### PR DESCRIPTION
**Pull request by ZeroQLi**
## Describe your project in 1-3 sentences

I am creating an IOT trello based kanban board

## Hack Club Slack handle
@ ZeroQL

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project it looks AWESOMEE!! small thing: can you please add your project name in the file, similar to how it is in the [template](https://github.com/hackclub/winter#readme)? )_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — APPROVED** [review]
console.log(\`Hey @ZeroQLi! Love the project idea! This sounds like it'd be super helpful for suffering IB students like myself. @hackclub/bank-ops will be in touch soon to help you get your grant :D\`)

**Comment by ZeroQLi** [comment]
std::cout << "Awesome, looking forward to the review and ultimately building the thing, i'm not that far behind in the school stress department (being a CBSE peep)"

**Review by MelSmith104 — COMMENTED** [review]
hey @ZeroQLi! this is so cool and such a different project! im dm'ing you on slack to get the process started for the grant!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
