### PR TITLE
Magic Umbrella

### PR DESCRIPTION
**Pull request by Aarushcoro**
## Describe your project in 1-3 sentences

Are you also bored by using normal umbrellas . I have got an idea of modifying it into an Magic Umbrella. It will use solar panel/solar fabric to collect solar energy and it will transfer it to lithium batteries for storage. This energy will be used in powering up light and fan. When the temperature will go above 30 degree C the fan will automatically get on and when there will be dark in the surroundings, the light will automatically get on. 

## Hack Club Slack handle

 https://hackclub.com/slack 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: can you please make it only one file "aarushcoro.md"? and, can you please properly format your budget table? thank you! please let me know if you need any help hehe)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by Aarushcoro** [comment]
can u please help me in doing that

**Comment by bellesea** [comment]
> can u please help me in doing that

yep! done :)

**Comment by Aarushcoro** [comment]
Thank you belle for helping me. Can you please guide me what to do next regarding my project.

**Review by maxwofford — CHANGES_REQUESTED** [review]
Wow, this is an awesome project! I had a couple questions, but once you address them I'd love to get this merged in!

What's the second arduino in the budget for? Doesn't one have enough gpio pins for all yours sensors?

I didn't see an arduino power cable in your list of parts. Are you going to power it directly from the pins?

I also didn't see spare wiring for your components. Is everything going to be wired up fairly close to the Arduino so the built-in wires connect them, or are you going to extend it with additional cabling?

I'm curious to see how long it can hold a charge for!

**Comment by Aarushcoro** [comment]
Hi @maxwofford. I am using a motor driver to make the fan spin. I also need 8 analog pins but an Arduino Uno has only 6 pins. 2 pins will be used by the LCD and 1 will be used by DHT 11 temperature and humidity sensor. 2 will be used by potentiometer and 1 will be used by LED to control brightness. 1 will be used by LCD to control the brightness of the LED and 1 will be used by a DPDT switch to change the power input. The Arduino Uno of which I have given you the link already comes with the power cable and I already have the wires. It can continuously work for 5 to 6 hours.

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
This project sounds awesome! A couple of clarifying questions:

* As Max asked, about the wiring. I'm not sure what kind of umbrella you're using but can you provide a little more info about where everything is going on the umbrella?
* Correct me if I'm wrong, but I believe you forgot to add the necessary sensor for turning the LEDs on and off. Do you mind adding that in, even if you already have it?

Once you've got these done we'll review your PR and hopefully get it merged! :)

**Comment by bellesea** [comment]
hey @Aarushcoro it's been a few days since JC's request for changes. i'm wondering, are you still interested in moving forward with this PR? if so, please update your PR by this Friday at 11:59pm ET so that you to get your parts in time for the event! thanks :)

**Comment by cfanoulis** [comment]
Hey, unfortunately it has been more than 24hrs since belle asked for clarifications and we haven't heard back from you - I'm going ahead and closing this PR as stale. Thanks for taking the time for write up your proposal :)

**Pull request closed without merging**
