### PR TITLE
Modern Duck Hunt & NES Zapper

### PR DESCRIPTION
**Pull request by DevIos01**
## Describe your project in 1-3 sentences

I am excited to build a modern version of the classic NES games, Duck Hunt and the NES Zapper, with my best friend @KianaMarjan. The Duck Hunt game will feature updated graphics and sound, as well as new gameplay elements to keep players engaged. It will be built using the Unity game engine and will be compatible with PC. The modern NES Zapper will be compatible in modern pc with API support. It will use a microcontroller to control the laser sight and trigger with multiple button, and will be powered by a rechargeable battery.

## Hack Club Slack handle

 Username: DevIos
 UserID: U014E8132DB

## Checklist before submitting proposal:

DevIos:
- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by KianaMarjan** [comment]
Awesome @DevIos01, will be fun working on this together!

## Checklist before submitting a proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Review by bellesea — CHANGES_REQUESTED** [review]
@DevIos01 and @KianaMarjan this is sooo awesome!! could you please elaborate under plan a little bit on how you plan on using the hardware parts listed in your budget? for example, for which parts of this project will you be using the Raspberry Pi?

Also, is the Duck Hunt game a fully software project? 

Thanks :)

**Comment by DevIos01** [comment]
> @DevIos01 and @KianaMarjan this is sooo awesome!! could you please elaborate under plan a little bit on how you plan on using the hardware parts listed in your budget? for example, for which parts of this project will you be using the Raspberry Pi?
> 
> Also, is the Duck Hunt game a fully software project?
> 
> Thanks :)

Hey @bellesea,

The Duck Hunt game will be a full software project, built using the Unity game engine and compatible with PC (the game itself is more like a demo project for the hardware). The modern NES Zapper, on the other hand, will involve both hardware and software components. The hardware components, such as the raspberry pi as the main microcontroller with custom other PCB for buttons and triggers, and using API to communicate the hardware with the game, rechargeable battery, and 3D printed components, will be used to create the physical NES Zapper. The software components, such as the microcontroller circuit and any additional features or sound effects, will be used to control the functionality of the NES Zapper.

I hope this helps to clarify how the hardware parts listed in the budget will be used in the project. Let me know if you have any additional questions.

hardware parts listed in the budget will be used in the project:

1. The One Nine Design OKdo Raspberry Pi 4 Model B 8GB Starter Kit will be used as the main computer for the project. It will be the main mini controller handling all the hardware input / API stored on it for communication 
2. The Raspberry Pi 32GB MicroSDHC With NOOBS will be used to store the operating system and any necessary software for the Raspberry Pi.
3. The Raspberry Pi Camera V2 Video Module will be used to provide video input for the NES Zapper project. It can be used to capture the laser sight and trigger input from the NES Zapper and send it to the Raspberry Pi for processing.
4.  The gyroscope will be used on hardware to detect the movement and rotation to recreate it on game.
5. The iFixit Pro Tech Kit will be used to repair and maintain the hardware components of the project, such as the Raspberry Pi and the NES Zapper.
6. The iFixit Pro Magnetic Project Mat will be used as a workspace to hold small parts and tools during the assembly of the NES Zapper.

When I use the word **NES Zapper** I am using it for reference but I will make my own version of it including the 3d model of how it looks and technical parts like gyroscope, microcontroller, etc.

**Review by bellesea — APPROVED** [review]
@DevIos01 and @KianaMarjan this is soooo awesome!! can't wait to see y'all work on this :)

a fabulous member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by MelSmith104 — APPROVED** [review]
hey @DevIos01 you already know i absolutely love your project lol - dm'ing you now to get the ball rolling on getting you the grant :)

**Comment by NahirElio** [comment]
Hi, I'm Nahir Elio and we @DevIos01 @KianaMarjan are IRL/classmates, and the reason I'd like to join/contribute is that even though we study engineering programs in high school, we never get a chance to do IRL stuff like working with hardware or print 3d part, it's just a theory but last November when I helped in TeenHack Stockholm I was able to do those things and it was fun and also wanted to try this project as a learning experience.

My contributing part to this project is to work/do a 3D part design and print them and assemble them once @DevIos01 is done with the hardware/firmware part. start by using Autodesk 3d which we use in our class and then learn how to convert the file to 3d printable and test it before moving on to making real parts of the 3d model in several small parts before assembling them and adding for glue gun.

Note: I don't know much English so I am using google translate so there might be a grammar error.

## Hack Club Slack handle

Username: Nahir Elio
UserID: U04HXJMEUR1


## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Pull request merged**
