### PR TITLE
Glucose Monitoring Project

### PR DESCRIPTION
**Pull request by Bhoomi-2115**
## Describe your project in 1-3 sentences

I am building a glucose monitoring system which can be scaled according to the number of members utilizing it using raspberry Pi and Arduino UNO. The data collected will be used to analyze the risk of diabetes with every reading. It will have the functionality of maintaining different profiles on the storage server (second Raspberry Pi).

## Hack Club Slack handle

Bhoomi Dwivedi

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by exu3** [comment]
Hello @Bhoomi-2115! Thanks for submitting a project proposal. I just wanted to give you a heads up that we're running a bit behind on reviewing projects. You can expect a review within the next 24-48 hours.

**Review by bellesea — CHANGES_REQUESTED** [review]
@Bhoomi-2115 this is sooooo cool!!! i'm wondering, are you referencing any guides for building this? 

also, do you have any plans for creating an "inserter" where you can read the individual electrodes on the strip? or how do you currently plan on reading the initial data?

btw, does your budget include taxes and shipping? 

thank you sm and hacky new years!

**Comment by Bhoomi-2115** [comment]
@bellesea @exu3 

- Yes I am referring to a document I found on web from University of Texas at El Paso [Document Link](http://www.ece.utep.edu/courses/web1305/EE1305/modules/module_6.htm) and I aim to seek guidance of the wonderful Hack Club community and a senior of mine who has explored this domain a bit.
- I plan to follow the same document to create a rudimentary probe for the electrodes using bent metal strips, since I did not dive deep into the design yet. I can even repurpose the head of an existing meter as a make shift solution. 
- I plan on probing an existing meter to collect the data and build correlations on the values. Since blood coagulates the resistance and voltage changes with time. I intend to record that data and build relations using that. I also plan to make use of [this document](https://www.nxp.com/docs/en/application-note/AN4364.pdf) for reference 
- Yes the budget includes India's taxes and since I have chose an indigenous store (robu.in) shipping won't be a problem. The only problem is availability and fluctuation in price of RPi (considering the current shortage).

Thank you for looking into my project and suggesting changes!

**Comment by bellesea** [comment]
> @bellesea @exu3
> 
> * Yes I am referring to a document I found on web from University of Texas at El Paso [Document Link](http://www.ece.utep.edu/courses/web1305/EE1305/modules/module_6.htm) and I aim to seek guidance of the wonderful Hack Club community and a senior of mine who has explored this domain a bit.
> * I plan to follow the same document to create a rudimentary probe for the electrodes using bent metal strips, since I did not dive deep into the design yet. I can even repurpose the head of an existing meter as a make shift solution.
> * I plan on probing an existing meter to collect the data and build correlations on the values. Since blood coagulates the resistance and voltage changes with time. I intend to record that data and build relations using that. I also plan to make use of [this document](https://www.nxp.com/docs/en/application-note/AN4364.pdf) for reference
> * Yes the budget includes India's taxes and since I have chose an indigenous store (robu.in) shipping won't be a problem. The only problem is availability and fluctuation in price of RPi (considering the current shortage).
> 
> Thank you for looking into my project and suggesting changes!

@Bhoomi-2115 great, thank you sm! could you please add this additional context into the files? on the fluctuation of price, we'll be able to offer up to a total $250 so if the price rises or falls after the project is accepted it's no worries at all :)

**Comment by Bhoomi-2115** [comment]
@exu3 @bellesea 

As suggested I have added the above points discussed to the MD file. I request you to look into it and let me know if anything else is required!

**Comment by bellesea** [comment]
> @exu3 @bellesea
> 
> As suggested I have added the above points discussed to the MD file. I request you to look into it and let me know if anything else is required!

@Bhoomi-2115 thanks for pushing the changes! since you have two raspberry pis do you need two SD cards and two power chargers too?

**Comment by Bhoomi-2115** [comment]
> > @exu3 @bellesea
> > As suggested I have added the above points discussed to the MD file. I request you to look into it and let me know if anything else is required!
> 
> @Bhoomi-2115 thanks for pushing the changes! since you have two raspberry pis do you need two SD cards and two power chargers too?

@bellesea 
No, I already have older ones. Plus I guess I would exceed my limit if I added that, I didn't want to be wasteful about it since I already have one from a previous set.

**Comment by bellesea** [comment]
> @bellesea No, I already have older ones. Plus I guess I would exceed my limit if I added that, I didn't want to be wasteful about it since I already have one from a previous set.

ahh cool, thank you!

**Review by bellesea — APPROVED** [review]
@Bhoomi-2115 this is soo cool! can't wait to see you work on this :))

an awesome member of @hackclub/bank-ops will be reaching out in the next few days with next steps!

**Comment by Bhoomi-2115** [comment]
> @Bhoomi-2115 this is soo cool! can't wait to see you work on this :))
> 
> an awesome member of @hackclub/bank-ops will be reaching out in the next few days with next steps!

Sure I'll look forward to it!

**Review by hackliv — APPROVED** [review]
@Bhoomi-2115 this project sounds so awesome! I'm dming you now on Slack to coordinate next steps for getting the grant through Hack Club Bank. :)

**Comment by bellesea** [comment]
heyy just checking, do you already have your arduino UNOs and have what you need to program the arduino? (eg. a USB 2.0 Cable Type A/B & a usb port on your computer)

**Comment by Bhoomi-2115** [comment]
> 
@bellesea 
Yes! I do, my seniors were more than happy to lend me those when they saw me taking interest in IoT.

**Pull request merged**
