### PR TITLE
Create KAIDEVRIM.md

### PR DESCRIPTION
**Pull request by KaiDevrim**
## Hack Club Slack handle
Kai - Penguin-ō

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — APPROVED** [review]
Hey @KaiDevrim this looks awesome! @MelSmith104 will follow up w/ next steps for your grant :) Can't wait to see how this turns out!

**Review by MelSmith104 — COMMENTED** [review]
hey @KaiDevrim ! love this! i'm going to dm you soon on slack so that we can get to the next step in getting you a grant! be on the lookout for a message from me soon!

**Comment by MelSmith104** [comment]
@KaiDevrim just dm'ed you!

**Comment by KaiDevrim** [comment]
updated the budget a lil
## Budget

| Product         | Supplier/Link                         | Cost   |
| --------------- | ------------------------------------- | ------ |
| PiKVM           | https://www.amazon.com/dp/B0B5R37TT3  | $79.99  |
| Mechanical Numpad | https://www.amazon.com/Tidbit-Programmable-Mechanical-Numpad-White/dp/B08CBQHGJ7 | $39.99 |
| SD Card Switcher | https://www.amazon.com/Icstation-Micro-Card-Dual-Switcher/dp/B01MY139K4 | $13.99 |
| NFC Hat         | https://thepihut.com/products/nfc-hat-for-raspberry-pi-pn532 | $30
| Total           |                                       | $182

**Pull request merged**
