### PR TITLE
Smart Image Classification

### PR DESCRIPTION
**Pull request by gershomj**
## Describe your project in 1-3 sentences

I am going to build a deep learning real-time image classification and object detection program with the NVIDIA Jetson Nano.

## Hack Club Slack handle
@gersh

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — APPROVED** [review]
@gershomj this is really awesome!!! can't wait to see you work on this :)

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

btw,  i'm wondering, have you ever worked with image classification & object detection? and is there a specific thing you're trying to do with this?

**Comment by gershomj** [comment]
I haven't worked with image classification and object detection before in a direct sense, but I have used the open-cv library to create a relatively simple facial recognition program ["Smart Oculi"](https://youtu.be/YkP2MSAkqm0), which is, in a way image classification but more tuned for facial recognition. My plans with this are to hopefully continue to onboard this technology onto something more autonomous, perhaps like a robot. It would be cool if these models could be run on regular dog-sized quadruped robots that could be affordable for everyone as a personal companion, but I haven't gotten that far in my plan as of yet 😅

**Review by daisybanks — APPROVED** [review]
Hi @gershomj! You're project sounds really cool! Could you please dm on Slack @daisy so we can talk next steps for getting you your grant? I was having a hard time finding you on slack just barely and want to make sure I have the right person. :)

**Comment by bellesea** [comment]
hey @gershomj did you mean to close this PR?

**Pull request closed without merging**
