### PR TITLE
Create christopherli574.md

### PR DESCRIPTION
**Pull request by christopherli574**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by tinuh** [comment]
Hey @christopherli574, your 3D printed keyboard project looks incredible here are some suggestions that I have regarding your project,

- Make sure you include taxes and shipping in the calculation for your budget, not sure if you included it in the price of the item but definitely something to keep in mind
- For printing parts for mechanical keyboards it may be worth checking out resin 3D printers as those prints tend to have more quality and would be better for this application here is a [recommendation](https://www.microcenter.com/product/657436/creality-ld-002r-lcd-resin-3d-printer) that I have, if you have a micro center nearby
- Could you have the partner for your project comment on this pr so that we can verify that you'll be working with him on this project?
- It looks like you already have LEDs on the PCB that you are buying which means that you won't necessarily need to desolder the LEDs on your current keyboard (which I don't even think is feasible), also the PCB looks like you're buying is hot-swap so it seems like you wouldn't be using the soldering iron
- For the keycaps do you plan on finishing them up (ex. sanding them and polishing them), considering that it's pla this step might be needed for a good experience

**Comment by mocer123** [comment]
Working with chris on this project

**Comment by christopherli574** [comment]
These prices include taxes/shipping. Unfortunately a resin printer will not suffice because the print bed won't be large enough. I'll switch the PCB to this one https://divinikey.com/products/kbdfans-kbd67-rev2-65-pcb
I plan to sand the keycaps after 3d printing them.

**Comment by tinuh** [comment]
Hey @christopherli574, could you provide more detail on how you plan on desoldering the LED lighting and transferring it to the new PCB? This does not seem possible to me as the new PCB would need to already have the circuits to control the RGB lighting, and the new PCB you provided it only has the circuitry for a regular backlight.

**Comment by christopherli574** [comment]
We won't plan to desolder and transfer the LED lighting from a different keyboard in that case. We will follow a guide like this one instead https://www.youtube.com/watch?v=8hdMKYgk5Eo

**Comment by tinuh** [comment]
ok, got make sure you include the LEDs you plan on using in your budget

**Comment by christopherli574** [comment]
done!

**Review by tinuh — APPROVED** [review]

**Comment by tinuh** [comment]
Hey @christopherli574, can't wait for this project to come to life! An amazing member of @hackclub/bank-ops will be reaching out to you soon with further details about the grant!

**Comment by christopherli574** [comment]
thank you for your help!

**Review by sampoder — CHANGES_REQUESTED** [review]
@mocer123 could you complete the checklist as well in a comment on this PR?

**Comment by mocer123** [comment]
✓ I am a current high school student (or younger).
✓ I have submitted an RSVP at <https://hackclub.com/winter>
✓ I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
✓ I have self-reviewed my project proposal.

**Comment by sampoder** [comment]
Thank you! (cc: @MelSmith104)

**Comment by christopherli574** [comment]
@MelSmith104 I'm U01UNDAQDBM

**Comment by mocer123** [comment]
U04KXVBBRKM

**Comment by MelSmith104** [comment]
thank you! dm'ing you both :)

**Review by MelSmith104 — APPROVED** [review]

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
