### PR TITLE
Autonomous self driving car - Tesla cyberTruck

### PR DESCRIPTION
**Pull request by sanjus-robotic-studio**
## Describe your project in 1-3 sentences

Autonomous self driving car in the form of Tesla cyberTruck using Raspberry pi. 

## Hack Club Slack handle
@ Sanjiv A

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at 
- [x] I am a member of the Hack Club Slack 
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey! Super cool sounding project, thanks for sharing it :D 

I'd like to know more about how you plan to create the Cybertruck shell part of the project. Will you be 3D printing it or using another manufacturing method?

**Comment by sanjus-robotic-studio** [comment]
@sampoder I will be 3d printing the shell part of the cyber truck with the 3d printer at home

**Comment by sampoder** [comment]
Could you amend your proposal to include more details about that?

**Comment by sanjus-robotic-studio** [comment]
@sampoder Made the changes

**Comment by sanjus-robotic-studio** [comment]
@sampoder can you look into it now

**Review by sampoder — APPROVED** [review]
☃️ Welcome to a Winter Hardware Wonderland! ✨

**Review by daisybanks — APPROVED** [review]
Hi @sanjus-robotic-studio! This project sounds really fun! I love that your vehicle is going to have so many cool features like navigation with the gps and obstacle detection with cameras. I love that there a lot of different things going on with this to work on! I'm dming you now on Slack to talk about the next steps in getting you your grant. :)

**Pull request merged**
