### PR TITLE
Monopoly Tablet

### PR DESCRIPTION
**Pull request by KianTheCon**
## Describe your project in 1-3 sentences
I am building a Monopoly BoardGame Tablet that will utilize special conductive game pieces to differentiate the pieces in game. 

## Hack Club Slack handle
Kster

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! such a cool idea! i'm wondering, is the game going to be played on the tablet? if so, are you coding your own version of monopoly and is the screen large enough? 

**we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by KianTheCon** [comment]
Sorry for not elaborating further on the monopoly part, I knew I should have written more. My plan was initially to just write a monopoly clone myself, but I thought I would also explore a few open source clones on github that I could maybe just alter to work with my game pieces if possible (if nothing really worked or required more work altering than just starting from scratch, I'll just program my own). 
As far as the screen I know it is a little too small, but I had a hard time finding a combination of sbc/pi-like device and monitor that would arrive at a reasonable total cost. The prices of all the raspberry pi devices are inflated like crazy right now so I went for something that looked like a good value at least. That's why I had to sacrifice on the display. If you have a suggestion for an affordable alternative, I would appreciate it. I also, to complete fault of my own, did not see the rule that consumer electronics are usually not purchased. If nothing else seems affordable I believe I may have an old Raspberry Pi 3 Model B kit that I could utilize for this, so it is an option that I drop the current sbc I put in the budget in favor of buying a larger display. 
I would appreciate any suggestions on large multipoint touchscreens that will work with a pi/sbc and on everything else I've written above. If my project still fails to reach the necessary criteria for the hackathon, I understand and appreciate your consideration nonetheless. Thank you and have a nice day!

**Comment by bellesea** [comment]
hey @KianTheCon that sounds good and no worries at all! i think your justification makes sense so i wouldn't worry too much about it until we're able to do a full review hehe :) and, a heads up that we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by devramsean0 — APPROVED** [review]
Looks good! You will be able to top up the bank account before you order.

@hackclub/bank-ops will follow up with you in slack :)

**Review by MelSmith104 — COMMENTED** [review]
hey @KianTheCon! this project looks awesome! I absolutely adore monopoly even though it brings out my competitive side. im dm'ing you on slack right now!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
