### PR TITLE
Add nickkbuii

### PR DESCRIPTION
**Pull request by nickkbuii**
## Describe your project in 1-3 sentences

 I am building an electronic sign language interpreter to allow deaf people to communicate with others who don't know sign language

## Hack Club Slack handle
@ Nick Bui

## Checklist before submitting proposal:
- [ X] I am a current high school student (or younger).
- [X ] I have submitted an RSVP at <https://hackclub.com/winter>
- [X ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ X] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: at first glance, this looks awesome!! can you please make sure your project is a markdown file by adding .md at the end of the file name? can't wait to review this)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by bellesea** [comment]
thanks for changing it! a heads up that we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by alhardwarehyde — APPROVED** [review]
Text to Speech is a big undertaking but you've really seem to have thought it over and have a really clear plan for what you need to do which is awesome!

@hackclub/bank-ops for their review.

**Review by daisybanks — APPROVED** [review]
Hi @nickkbuii! This sounds like a really meaningful and awesome project and I can't wait to see you start building it! I'm dming you now on Slack to talk about next steps! :)

**Pull request merged**
