### PR TITLE
Create Neesh774.md

### PR DESCRIPTION
**Pull request by Neesh774**
## Describe your project in 1-3 sentences
I'm building a system to automatically open and close my blinds.

## Hack Club Slack handle
@ Kanishq Kancharla

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@Neesh774 this looks awesome! could you please factor in shipping / taxes for your budget?

also, will you be printing a pre-designed clamp?  or designing your own clamp?

thanks sm!

**Comment by Neesh774** [comment]
So Adafruit isn't showing that it has any shipping costs for my order, and the 3D printer from Amazon also has free shipping. And I'll be designing my own clamp!

**Comment by bellesea** [comment]
> So Adafruit isn't showing that it has any shipping costs for my order, and the 3D printer from Amazon also has free shipping. And I'll be designing my own clamp!

@Neesh774 cool, thank you sm!

**Review by bellesea — APPROVED** [review]
this looks incredible! can't wait to see you work on this hehe :) the awesome @hackliv will be reaching out w/ next steps!

**Review by hackliv — APPROVED** [review]
@Neesh774 this sounds awesome! I struggled so hard with my blinds the other day, so I can't wait to check out your progress on this. :) Dming you now on Slack to coordinate getting set up on Bank!

**Comment by ByteAtATime** [comment]
Out of curiosity, did you get this idea from Joma Tech?

**Pull request merged**
