### PR TITLE
3-d printed claw

### PR DESCRIPTION
**Pull request by kriaga259**
## Describe your project in 1-3 sentences

I am building a 3-d printed claw with servos.

## Hack Club Slack handle (don't have one yet)

{at} sneha n
{at} aditi l

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Sneha-Narayan** [comment]
i am a teammate

**Comment by aditilagisetty** [comment]
I am a teammate.

**Comment by exu3** [comment]
Screenshot 2023-01-09 at 10 43 53 PM
 
@kriaga259 could you make sure to join the Hack Club Slack? https://hack.af/slack

**Comment by exu3** [comment]
@Sneha-Narayan @aditilagisetty 

Could you both complete the following checklist in a separate comment?

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

**Review by exu3 — COMMENTED** [review]
I think this project idea is great. However, I don't think it makes sense to approve a budget solely for the purpose of purchasing a complete 3D printer kit because the goal of the event is to build a technically challenging project and learn something new. The purpose of the grant is to cover electronic components and hardware. If a project's budget includes expensive tools/devices, I don't think it should exceed a certain percentage of the budget.

Since you already have all the other components you need to build this claw, perhaps you could instead spend your time during Winter Hardware Wonderland building a 3D printer of your own? I might recommend this MP3DP from V1 Engineering https://docs.v1engineering.com/mp3dp/version2/

I'm going to close this pull request as this proposal doesn't quite meet the requirements, but feel free to open a new pull request, or reopen this one if you feel that I have misunderstood your project.

**Pull request closed without merging**
