### PR TITLE
Speed Tracking Luxury Keyboard

### PR DESCRIPTION
**Pull request by happiestbee**
## Describe your project in 1-3 sentences

I am building a keyboard that is able to track how fast a user types and display it on a LCD screen. It also keeps track of other related stats and has other features such as lighting and speakers. The keyboard features can be controlled using a web app. 

## Hack Club Slack handle

Display Name: Steven Wang
Username: stevenwang770

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @happiestbee this is such a cool idea! 

it seems like the majority of your project is a python script to detect inputs + a display system for that so we won't be able to approve the purchasing of your keyboard since it's not essential to this project functioning.

an alternate suggestion would be if you use the arduino to intercept keystrokes from your keyboard, perhaps by connecting your keyboard to the arduino and arduino to your computer. 
https://docs.arduino.cc/built-in-examples/usb/KeyboardSerial

please let me know how you'd like to proceed :) thank you!

**Comment by happiestbee** [comment]
Thank you, I have updated the project following your suggestions.

**Comment by bellesea** [comment]
> Thank you, I have updated the project following your suggestions.

@happiestbee cool! could you please do a little more research into making sure that would work (that was a hacky suggestion i've never tested haha) and expand on your plan so we could imagine you building it?

thank you :) please let me know when you're ready for a re-review :)

**Comment by happiestbee** [comment]
@bellesea I have done some additional research and found guides that will tell me exactly how I should connect the pieces and write the arduino programs and have expanded on my plans accordingly. 
I do have everything I need to program the arduino including the IDE installed. 
Thank you!

**Review by bellesea — CHANGES_REQUESTED** [review]
@happiestbee this is super awesome!! a small question: how would your arduino then send the keyboard input signals to your computer such that it'll still work as a keyboard for your computer?

thank you :)

**Comment by happiestbee** [comment]
@bellesea The keyboard library that the arduino uses to read the input from the board also allows the arduino to send the input to the keyboard using the Keyboard.write() command 
this can be seen in use here https://docs.arduino.cc/built-in-examples/usb/KeyboardSerial

**Comment by bellesea** [comment]
> @bellesea The keyboard library that the arduino uses to read the input from the board also allows the arduino to send the input to the keyboard using the Keyboard.write() command This way, I can read the input form the board and still send all the keystrokes to the computer this can be seen in use here https://docs.arduino.cc/built-in-examples/usb/KeyboardSerial

incredible! thank you :)

**Review by bellesea — APPROVED** [review]
@happiestbee this is super awesome!!

a fabulous member of @hackclub/bank-ops will be reaching out soon with next steps :)

**Review by MelSmith104 — COMMENTED** [review]
hey @happiestbee! this project sounds so fun! i've always loved testing my typing speed and use to do it literally all the time. im dm'ing you on slack right now to chat about next steps :)

**Comment by happiestbee** [comment]
@MelSmith104 Thank you! I have responded to your slack dm

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
