### PR TITLE
Create shreekar-developer.md

### PR DESCRIPTION
**Pull request by shreekar-developer**
## Describe your project in 1-3 sentences
My brother and I plan to build a custom PC NAS using wood and 3D printed parts. We will create the structure from wood with 3D printed brackets and mounts. And we will custom build a PC for the inside of the case running a NAS OS. 

## Hack Club Slack handle
shreekar
Shreepaad
aditya ramesh

## Checklist before submitting proposal:
Shreekar Checklist
- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Shreepaad** [comment]
Slack Username: Shreepaad
Shreepaad Checklist
- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey, this is an awesome project. I'm running a Synology NAS at home and have been wanting to build my own for a while now. I had a couple questions about how you're planning to implement your project.

You mentioned you're going to use the 3d printer to create fan frames & the actual case for the PC. Are you designing the parts yourself, or following a design online?

For the NAS, what OS are you planning to run?

**Comment by shreekar-developer** [comment]
Hi @maxwofford  

We will custom build the 3D printed components. We both have CAD Experience and will use Autodesk Inventor for it. 
I plan on running Truenas for now and potentially upgrading to a paid Unraid plan. 

Thank you!

**Review by maxwofford — APPROVED** [review]
This looks great! I'd love to see the design you come up with.

I'm approving the design & someone from @hackclub/bank-ops will be in touch shortly.

**Comment by Aditya-Ramesh** [comment]
@maxwofford Can I join their team? I would also like to work on the project with them after speaking with Shreekar and Shreepaad. We would use the extra budget for hard drives for our NAS. We discovered that the hard drives that we were going to use were full or were damaged. We can provide the updated parts here in the comments, or in the meeting next Thursday with Daisy. Anything works. Please let us know.

## Hack Club Slack handle
aditya ramesh


## Checklist before submitting proposal:
Aditya Checklist
- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

**Comment by shreekar-developer** [comment]
> @daisybanks  Can I join their team? I would also like to work on the project with them after speaking with Shreekar and Shreepaad. We would use the extra budget for hard drives for our NAS. We discovered that the hard drives that we were going to use were full or were damaged. We can provide the updated parts here in the comments, or in the meeting next Thursday with Daisy. Anything works. Please let us know.
> 
> 
> 
> ## Hack Club Slack handle
> 
> aditya ramesh
> 
> 
> 
> 
> 
> ## Checklist before submitting proposal:
> 
> Aditya Checklist
> 
> - [X] I am a current high school student (or younger).
> 
> - [X] I have submitted an RSVP at <https://hackclub.com/winter>
> 
> - [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
> 
> - [X] I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
hey @Aditya-Ramesh love that you're going to work with them! can y'all please update your budget with the changes so that we can review and ensure that it still fits the goals of this grant? thank you :)

**Comment by shreekar-developer** [comment]
> hey @Aditya-Ramesh love that you're going to work with them! can y'all please update your budget with the changes so that we can review and ensure that it still fits the goals of this grant? thank you :)

We just finished updating our budget. We are using 2 hard drives because we are doing RAID1 data redundancy.

**Comment by maxwofford** [comment]
Hey @shreekar-developer! I'll review this when I can. Please update the markdown to include all members. At the time of writing only the previous budget is approved, so that won't change until the new budget is reviewed.

**Comment by shreekar-developer** [comment]
> Hey @shreekar-developer! I'll review this when I can. Please update the markdown to include all members. At the time of writing only the previous budget is approved, so that won't change until the new budget is reviewed.

Hi @maxwofford, I updated the markdown file to include Aditya’s GitHub. So in the meeting today afternoon, will we be approved for $500? And then $250 added later if this new budget is approved?

**Comment by shreekar-developer** [comment]
@maxwofford 

I updated the file with ideas if we have time remaining. Thank you!

**Review by maxwofford — APPROVED** [review]
The updated hardware on this is good to go! Just want to confirm, the grant is $750 (3 hackers x $250), so you'll need to cover the extra $75.

cc @daisybanks so she can send the grant!

**Comment by shreekar-developer** [comment]
Ok, thank you!

**Pull request merged**
