### PR TITLE
Create faheemam8102.md

### PR DESCRIPTION
**Pull request by faheemam8102**
## Describe your project in 1-3 sentences

 In this project, I would like to experiment with the stirling engine and termoelectric plates. I would like to experiment with heat and electricity by combining these 2 thermoelectric generators and learn more about the relationship between the 2. NOTE: I am not an expert and am just experimenting and trying to learn more about this fascinating field! Through this learning, I would also like to create body heat to electricity generator that could potentially power a load like a fan that gets faster as your body temperature rises.

## Hack Club Slack handle
Mr. E
 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@faheemam8102 thank you so much for your patience with a review! i'm wondering, what is the specific modification that you're making to maximise the efficiency of a stirling engine and how did you come to the conclusion that this would work?

thank you!

**Comment by faheemam8102** [comment]
Thank you! So this is more of an experiment that I am really wanting to see how thermodynamics and electricity can work hand in hand. I would like to make a change to my project though.

I actually realized I actually need some more equipment, and that would be 2 gamma type stirling engines, clamp meter, infrared thermometer, tachometer, and some thermal glue.

Some of these tools I realized I need to help gather data and information. My main goal is to experiment with electricity and heat. I am actually planning on doing 2 experiments:

1.) I would like to use the peltier plates and create electricity from body heat. I sit at my chair for probably around 5 hours a day and would like to see if I can use the useless heat to generate some kind of useful electricity. For this, I need some peltier plates and a heat sink or cooler. The peltier plates (thermoelectric plates) generate electricity based off of a difference in heat. So on one side, body heat creates the hot side and on the other side, the heat sync plus ice will create the cool side.

2.) For the second experiment, I would to use stirling engines (alpha and gamma types) to create mechanical/electrical energy from heat. These engines also run on a difference in heat so I am planning on using the peltier plates to create the heat and cold source. I would like to create a double gamma engine apparatus where the peltier plates are in the middle and on the outside generate mirror images of each other. (I can explain more in detail in to edited pull request). In order to power these peltier plates, I would like to use a green energy from a more powerful alpha type stirling engine to keep things green. I know it may be more efficient to directly hook up an electric motor but I would like to more so see where electricity and heat are lost in this apparatus by using the clamp meter and infrared thermometer. I may run different iterations of this experiment and see how different placements of the peltier plates on the double gamma set up can impact the speed. I would use the tachometer to measure the speed.

Am I allowed to make these edits to my request?
Thank you and sorry for the delay and long response.

**Comment by bellesea** [comment]
@faheemam8102 yes please go ahead and update your file with these changes! looking forward to learning about and reviewing this once you're done :) to aid us, it'd be super helpful if you linked some relevant guides/articles that support your experimentation, thank you sm!

**Comment by faheemam8102** [comment]
Done with the updates.
Here are some articles:
https://www.instructables.com/Thermoelectric-Generator-Project/ - TEG project
https://scienceimproved.com/how-to-generate-electricity-thermoelectric-generator/ - Thermoelectric plates
https://news.ncsu.edu/2016/09/wearable-teg-heat-harvesting-2016/ - body heat and thermoelectric plates
https://patents.google.com/patent/DE102006012128A1/en - Patent with similar idea (I am not copying this)
https://sites.suffolk.edu/jstraka/2015/10/18/the-stirling-heat-engine-peltier-device/ - general info article
https://www.youtube.com/watch?v=vsTIWhZ-6HM - A similar approach to the double gamma engine setup

Hope these help!

**Review by Sheepy3 — CHANGES_REQUESTED** [review]
Hey! I think this is a great project and a great opportunity to learn. However, I think you may need to define an end goal outside of experimentation. What final deliverable could you come up with? you suggested experimenting with body heat and useless energy sources, could you describe what you intend to create following your experimentation?

**Comment by faheemam8102** [comment]
Sure! In one of my goals, I intend to create a chair where heat from the body can come through a circuit to create meaningful energy to power some kind of load or even a Stirling engine to create a mechanical fan that moves faster as your body temperature rises! (this can create a greater temperature difference in the peltier plates and increases the voltage that can power another set of plates that power a heat engine or even a normal fan)

**Comment by Sheepy3** [comment]
> Sure! In one of my goals, I intend to create a chair where heat from the body can come through a circuit to create meaningful energy to power some kind of load or even a Stirling engine to create a mechanical fan that moves faster as your body temperature rises! (this can create a greater temperature difference in the peltier plates and increases the voltage that can power another set of plates that power a heat engine or even a normal fan)

sounds super cool! add this to your PR and I'll approve :)

**Comment by faheemam8102** [comment]
Thank you! I have added it to my PR!

**Review by Sheepy3 — APPROVED** [review]
Approved!

**Comment by faheemam8102** [comment]
Thank you!

**Review by bellesea — APPROVED** [review]

**Comment by bellesea** [comment]
an awesome member of @hackclub/bank-ops will be reaching out soon with next steps :)

**Review by hackliv — APPROVED** [review]
Hey @faheemam8102 ⚡️ this is so cool! I'm dming you now on Slack to chat more about your plans for the experiment and next steps to receive the grant. 😁

**Pull request merged**
