### PR TITLE
Create thinkingjet.md

### PR DESCRIPTION
**Pull request by thinkingjet**
## Describe your project in 1-3 sentences
1) E ink reader/widget dashboard sort of thing 
2) RAsberry pi smart display/smart mirror
3) Usb Rubber ducky hud injector thing using a rasberry pi pico 

## Hack Club Slack handle
Gauravjeet Singh

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by thinkingjet** [comment]
For Gauravjeet Singh(angad1411@gmail.com) Github user: thinkingjet

**Comment by thinkingjet** [comment]
Update from the proposal: ordered the rasberry pi 4 using my own money

**Review by MelSmith104 — CHANGES_REQUESTED** [review]
hey @thinkingjet ! these projects all sound amazing :) before moving forward i just want to make sure that you've factored in shipping / taxes in your budget. please let me know!

**Comment by thinkingjet** [comment]
@MelSmith104 Yeah, all the prices are including delivery and taxes

**Comment by thinkingjet** [comment]
Alreafy done

**Review by MelSmith104 — COMMENTED** [review]
awesome! thank you for the update on the shipping / taxes! im dm'ing you on slack right now to go over next steps!

**Review by MelSmith104 — APPROVED** [review]

**Review by bellesea — APPROVED** [review]

**Pull request merged**
