### PR TITLE
Realistic Iron Man Helmet

### PR DESCRIPTION
**Pull request by aryamanrtunjay**
## Describe your project in 1-3 sentences
A realistic iron man helmet, it will have a heads up display, a camera on the back, and a microphone with speakers to project your voice. Furthermore, we are planning on integrating a Jarvis AI into the system so voice input can be used to change the HUD display or get information about things the camera sees or answers to questions from google.

## Hack Club Slack handle
Aryaman Rtunjay
raghav kalyan

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@aryamanrtunjay this is soo awesome!! to check, do you have access to a 3d printer to later print out the Iron Man helmet? and, do you already have the pi and servos + what you need to be able to connect all of this together (probably some sort of soldering set)?

@raghav-kalyana-sundaram can you please comment to this PR confirming that have done the below?
- [ ]  I am a current high school student (or younger).
- [ ]  I have submitted an RSVP at https://hackclub.com/winter
- [ ]  I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [ ]  I have self-reviewed my project proposal.

**Comment by Raghav-Kalyana-Sundaram** [comment]
@bellesea 

- [x]  I am a current high school student (or younger).
- [x] I have submitted an RSVP at https://hackclub.com/winter
- [x] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [x] I have self-reviewed my project proposal.

**Comment by aryamanrtunjay** [comment]
Hi @bellesea 

Yeah! I've got a 3D printer to print out the helmet and some pretty cool red and gold spray paint cans to paint the 3D print. Raghav has the Pi and I've got an arduino kit and some servos that go with it so we're thinking of powering the arduino using the Pi and using the arduino to control the servos. The Pi would only be used for controlling the Jarvis AI with the speakers and microphone.

The HUD unit just needs an HDMI input so I have spare HDMI cables er can connect to it from the Pi HDMI output port to the HUD unit. The microphone is on a USB so that can be plugged straight into the raspberry pi and the speakers and camera have wires on them meant to plug into the raspberry pi. The eye LED strip are connected to a battery so those don't need to be connected to the Pi or the Arduino.

Thanks,
@aryamanrtunjay and @Raghav-Kalyana-Sundaram

**Comment by bellesea** [comment]
> 

awesome!! thank you sm for sharing :)) @aryamanrtunjay could you please update your file with the information above? perhaps under "plan"?

**Comment by aryamanrtunjay** [comment]
Done :+1:

**Review by bellesea — APPROVED** [review]
@aryamanrtunjay and @Raghav-Kalyana-Sundaram thank you so so much for sharing this project idea w/ us!! can't wait to see y'all work on this :))

a fabulous member of @hackclub/bank-ops will be reaching out soon (likely tmrw EST) w/ next steps!

**Comment by aryamanrtunjay** [comment]
Sounds good! Thanks for the suggestions!

**Review by hackliv — APPROVED** [review]
WOWOWOWOW @aryamanrtunjay and @Raghav-Kalyana-Sundaram this is so awesome! I can't wait to see this in the making during the Slack event. 😃 I'm dming you both on Slack now to talk about next steps for joining Hack Club Bank and receiving the grant.

**Pull request merged**
