### PR TITLE
First PC Build

### PR DESCRIPTION
**Pull request by Abhinav413652**
## Describe your project in 1-3 sentences
I am building a PC with custom Hacking OS.

## Hack Club Slack handle
Abhinav Singh

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by akdd0126** [comment]
Waiting for it to be merged...

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hello Abhinav! Unfortunately I'm not able to approve a grant for this project; as it is oriented more towards software but not hardware. The goal for this grant it to provide an entrypoint for students to come in contact with the very-low lever hardware that makes computers... well, computers.

Also, I'm afraid you're quite over budget. The allotted grant per student is 250$. Is anybodybelse joining you?

**Comment by akdd0126** [comment]
There are two persons in this project so I was asking for 500 dollars. And it's not just software, I will learn how hardwares and softwares interact. So please approve.

**Comment by cfanoulis** [comment]
Hi, I've replied to you via Slack

**Pull request closed without merging**
