### PR TITLE
personal tempate update and otherfixes (#439)Co-authored-by: Charalampos Fanoulis <charalampos.fanoulis@gmail.com>

### PR DESCRIPTION
**Pull request by ZeroQLi**
WHAT'S UP GUYS  this is ZeroQL BACK with another pull request and this today we are going to open this pull request

before we start off i would like to thank today's wonderful sponsor RAID SHADOW LEGENDS. One of the biggest mobile role-playing games of 2019 and it's totally free! Currently almost 10 million users have joined Raid over the last six months, and it's one of the most impressive games in its class with detailed models, environments and smooth 60 frames per second animations! All the champions in the game can be customized with unique gear that changes your strategic buffs and abilities! The dungeon bosses have some ridiculous skills of their own and figuring out the perfect party and strategy to overtake them's a lot of fun! Currently with over 300,000 reviews, Raid has almost a perfect score on the Play Store! The community is growing fast and the highly anticipated new faction wars feature is now live, you might even find my squad out there in the arena! It's easier to start now than ever with rates program for new players you get a new daily login reward for the first 90 days that you play in the game! So what are you waiting for? Go to the video description, click on the special links and you'll get 50,000 silver and a free epic champion as part of the new player program to start your journey! Good luck and I'll see you there!

### CODE REVIEW

**Comment by cfanoulis** [comment]
zero is2g :sob:

**Review by cfanoulis — APPROVED** [review]
image

**Comment by ZeroQLi** [comment]
Ok so the country commit may need some explanation

for no other reason than my internal curiosity, i decided to fetch the location of ALL 250+ members participating in hardware party and found some countries missing in the list (using their public gh api thingy you get the point)

below are the countries the associated participant, the country I've added to list and the related PR

_note: some have had more than 1 participant but is that really necessary_

| name  | country   | related PR   | 
|---|---|---|
|wollygfx|Columbia|https://github.com/hackclub/winter/pull/393|
|WilmervH|Finland|https://github.com/hackclub/winter/pull/108|
|PasinduDushan|Sri Lanka|https://github.com/hackclub/winter/pull/257|
|mostlywhat|Thailand|https://github.com/hackclub/winter/pull/71|
|chrisrama|South Africa|https://github.com/hackclub/winter/pull/322|
|peiprjs|Spain|https://github.com/hackclub/winter/pull/149|
|SatoMasahiro2005|Japan|https://github.com/hackclub/winter/pull/17|
|ZeroQLi|United Arab Emirates|https://github.com/hackclub/winter/pull/325|

also is it me or does the last name look _vaguely_ familiar 🤔

**Comment by ZeroQLi** [comment]
it seems you guys will wrap up proposals this week.

if so then keep this PR open.That way i can finish off with the fixes of other upcoming grants without needing to open another pr

**Comment by ZeroQLi** [comment]
can you guys solve the above edit conflict, i have no clue.

**Comment by maxwofford** [comment]
I don't have edit access to push to your branch! That said, we can squash this once it's ready.

**Comment by cfanoulis** [comment]
@maxwofford this needs to be resolved via CLI - github complains about complexity...

**Comment by maxwofford** [comment]
Merging, thanks for the fix!

**Comment by ZeroQLi** [comment]
awesome, thanks for fix up

I _guess_ this is the last one, i'll prob do one last check but I've got exams and the actual hardware event going on  so it'll take some time

I've made of half all the contributions i made in 2022 in january alone thanks to this repository. So thank you for letting me inflate my contribution history :p.

**Pull request merged**
