### PR TITLE
ATL Notice Board

### PR DESCRIPTION
**Pull request by vmss2009**
## Describe your project in 1-3 sentences

Develop a webapp using flutterflow and curate content from ATL activities which needs to be displayed on a monitor that is powered on for the whole duration of the ATL. A raspberry pi would act as a computing device to run our webapp. An RFID reader connected to raspberrry pi would read a student's RFID card and show the relevant student record.

## Hack Club Slack handle
vasa.mohanseshasai

## Checklist before submitting proposal:

- [✔ ] I am a current high school student (or younger).
- [✔ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [✔ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✔ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by sanjay-nagesh — CHANGES_REQUESTED** [review]
Hey!

Could you please include taxes and shipping in your budget?

Thanks,
Sanjay Nagesh

**Comment by vmss2009** [comment]
Hi

The prices mentioned there already includes taxes and shipping.

Regards
Mohan

**Comment by vmss2009** [comment]
Is raspberry pi also considered as a pre-built kit ?

Regards
Mohan Seshasai Vasa
Visakhapatnam, AP, India
Github-  https://www.github.com/vmss2009

**Comment by bellesea** [comment]
@vmss2009 no, a rpi does not count as a pre-built kit :) and, a heads up that we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @vmss2009 thank you so much for your patience with a review!

this is such a cool idea but unfortunately doesn't really fit the intentions of this grant/event as it's a fully software project that you can work on without the hardware... although, we'd be open to amends to this PR such as some sort of physical sensor so people can interact with your webapp... like what if your website had "accounts of sorts" then you added an RFID reader and gave everyone at your specific ATL an RFID tag so they could tag the reader and the notice board would show their specific schedule. it doesn't have to be this idea but we're looking for something with more "hardware hacking."

or if you'd like you can also submit another PR with a different idea :)

please let me know how you'd like to proceed, thank you!

**Comment by bellesea** [comment]
hey @sanjay-nagesh it's been a few days since my request for changes :) i'm wondering, how would you like to proceed? we look forward to moving forward soon so you can get your parts in time for the event! thanks :)

**Comment by sanjay-nagesh** [comment]
> hey @sanjay-nagesh it's been a few days since my request for changes :) i'm wondering, how would you like to proceed? we look forward to moving forward soon so you can get your parts in time for the event! thanks :)
> 

This is not my project LOL

**Comment by bellesea** [comment]
> > hey @sanjay-nagesh it's been a few days since my request for changes :) i'm wondering, how would you like to proceed? we look forward to moving forward soon so you can get your parts in time for the event! thanks :)
> 
> This is not my project LOL

ack sorry about this! meant to ping @vmss2009 :) thanks!

**Comment by bellesea** [comment]
hey @vmss2009 we're very excited by your PR but since we're now drawing closer to the date of the event, we need you to **respond to the changes requested above by Friday (27th) at 11:59pm ET or we won't be able to move forward with your PR**. this is because you're unlikely to get your parts in time if there's any further delay. thank you sm!

**Comment by vmss2009** [comment]
Hi

Sure, I am thinking about 2 plans and I should be able to submit a PR
request by Friday 11:59pm.


Regards
Mohan Seshasai Vasa
Visakhapatnam, AP, India
Github-  https://www.github.com/vmss2009

**Comment by bellesea** [comment]
> Hi Sure, I am thinking about 2 plans and I should be able to submit a PR request by Friday 11:59pm. Regards Mohan Seshasai Vasa Visakhapatnam, AP, India Github- https://www.github.com/vmss2009

great! looking forward to it :)

**Comment by vmss2009** [comment]
Hi Belle

I updated the PR now by adding the RFID card reader and RFID cards to
uniquely identify students to show their record of activities.


Regards
Mohan Seshasai Vasa
Visakhapatnam, AP, India
Github-  https://www.github.com/vmss2009

**Review by bellesea — CHANGES_REQUESTED** [review]
@vmss2009 awesome!! a few more things:
- can you please check if your budget includes shipping & taxes
- do you have enough RFID cards?
- how do you plan on connecting your rpi to the RFID reader?
- can you please elaborate on your plan for how you'd send the data from the RFID reader to your application so it shows the relevant pages?
- also, what's the reason for using flutterflow instead of coding the whole website?

thank you!

**Comment by vmss2009** [comment]
Hi Belle


   - can you please check if your budget includes shipping & taxes  *Yes,
   Included*


   - do you have enough RFID cards?
*Ordering a total of 10. So we can test with 10 ATL students. Seems enough.
   *
   - how do you plan on connecting your rpi to the RFID reader?
*7 pins (out of a total of 8) of RFID reader are to be connected to RPI.
   This website has complete pin to pin connection details.
   (https://www.raspberrypi-spy.co.uk/2018/02/rc522-rfid-tag-read-raspberry-pi/
   <https://www.raspberrypi-spy.co.uk/2018/02/rc522-rfid-tag-read-raspberry-pi/>).
   Minor change is that we are going to use RPI v4 instead of v3. *
   - can you please elaborate on your plan for how you'd send the data from
   the RFID reader to your application so it shows the relevant pages?

* Firstly we will register all the RFID's issued to students into the
   Firestore database. When a student shows up with an RFID tag to get his
   data, a unique ID  for each RFID will be sent to RPi. We will create an API
   in which the RPi will call it (POST request) and send the unique ID to the
   API and it returns the student name for the presented unique ID. UniqueID
   is  checked in the Firestore database and the client (flutterflow) will
   invoke the API whenever the POST request is called. By that we can get the
   name of the student from the RFID reader to our client. Then we will check
   the schedule of the respective student by retrieving it from the Firestore
   database. *
   - also, what's the reason for using flutterflow instead of coding the
   whole website?
*Already developed the majority of the software part (web app) in
   flutterflow. And I don't want to spend time reinventing the wheel. This
   time I want to spend time integrating the hardware part so that Here is the
   link to my website. (https://www.hamaralabs.com/
   <https://www.hamaralabs.com/>) Also, here is the link to the webapp to
   access ATL student services. (https://hamaralabs.flutterflow.app/#/
   <https://hamaralabs.flutterflow.app/#/>). Would be happy to demonstrate the
   product online.*


Regards
Mohan Seshasai Vasa
Visakhapatnam, AP, India
Github-  https://www.github.com/vmss2009

**Review by bellesea — APPROVED** [review]
@vmss2009 great! thank you sm :)

a awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

approving to move forward but can you please add the information that you mentioned within your file? also, since you've already started working on this project it might not take a whole 10 days for you to do this so i hope you can even further expand your plan and push yourself further :) thanks!

**Review by hackliv — APPROVED** [review]
this sounds awesome @vmss2009! I'm so excited to hear more about it from you. 😊 DMing you now on Slack to chat about next steps for the grant

**Pull request merged**
