### PR TITLE
Create Michaell14.md

### PR DESCRIPTION
**Pull request by Michaell14**
## Describe your project in 1-3 sentences
Me and my friend are building an interactive smart mirror that can respond to my voice and update me on basic daily information like the weather and the time. 

## Hack Club Slack handle

Michael Li

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by MelSmith104 — COMMENTED** [review]
hey @Michaell14 ! super excited to see the project you've come up with :) i love the smart mirrors! before moving forward, since you're working on this project with your friend can you please have them comment on this pr with the same requirements? 

 I am a current high school student (or younger).
 I have submitted an RSVP at https://hackclub.com/winter
 I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
 I have self-reviewed my project proposal.

Thank you!

**Comment by Dupopking** [comment]
Hi, my name is Nick P. and I am working with Michael on this project!

Github: @Dupopking
Slack: @Nick Peng

[x] I am a current high school student (or younger).
[x] I have submitted an RSVP at https://hackclub.com/winter
[x] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[x] I have self-reviewed my project proposal.

**Comment by Michaell14** [comment]
Thanks Nick! 

Slack ID: U03P8PN8RJ5

**Comment by MelSmith104** [comment]
awesome! thank you both so much! im dm'ing you in slack right now!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
