### PR TITLE
Smart RC Car With AI Camera

### PR DESCRIPTION
**Pull request by TheScientist101**
## Describe your project in 1-3 sentences
My project is a remote control car with smart features. It has the ability to detect objects in front of it and collect temperature and humidity data.

## Hack Club Slack handle
@Urjith Mishra

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy @TheScientist101 thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: why do you want your rc to have a temp and humidity sensor? how would the car inform the driver? would it be better to just have a mounted camera and make it a fpv rc?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by TheScientist101** [comment]
Thanks @bellesea I have updated the request, the sensors were from the referenced tutorial, I also wasn't exactly sure why they included them, but I thought they could be interesting. I will probably remove the temperature and humidity sensor and find a raspberry pi that will fit the budget and is in stock. Please let me know if you need anything else.

**Comment by TheScientist101** [comment]
I understand that my cost is above the covered 250 dollars and I will cover the remaining costs. However, do I need deposit the money into hack club bank first, or could I just directly add it to the order?

**Comment by JeffreyWangDev** [comment]
Hello @TheScientist101, I just saw your request and I just want to let you know that you can get a raspberry pi 4b from the official [website ](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/) for $55.

**Comment by TheScientist101** [comment]
Hey @JeffreyWangDev thanks for the info but it is out of stock in all of their authorized distributors.

**Comment by bellesea** [comment]
@TheScientist101 ahhh cool! was just curious hehe, if you'd like to have the sensors it's 100% cool :) and we'd ask that you deposit it into hack club bank first then pay for it through the issued cards :)

what about the AI component of your project? how would the car inform the driver? would it be better to just have a mounted camera and make it a fpv rc?

**Comment by TheScientist101** [comment]
Hello @bellesea I plan to use the AI component to allow the robot to react differently in different situations, this could make it more autonomous than just a regular FPV RC car. Let me know if you need more clarification.

**Comment by TheScientist101** [comment]
Please let me know if my math is wrong, I might have made a typo somewhere or something

**Comment by TheScientist101** [comment]
@bellesea Please let me know if my math is wrong, I might have made a typo somewhere or something

**Comment by bellesea** [comment]
@TheScientist101 thank you for pushing these changes :) we should review this PR within the day or so, thank you for your patience!

**Review by alhardwarehyde — APPROVED** [review]
Hi this project looks awesome! As a former Adafruit employee love where you're getting your parts. Adafruit's a great resource. Tagging @hackclub/bank-ops to take from here!

**Review by daisybanks — APPROVED** [review]
@TheScientist101 - This looks like a really fun project and a good way to combine your knowledge of software with a hardware project! I'm dming you now on Slack to talk about next steps in getting you you your grant!

**Pull request merged**
