### PR TITLE
Create tejasCreative.md

### PR DESCRIPTION
**Pull request by TejasCreative**
## Hack Club Slack handle
tejas

## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by TejasCreative** [comment]
How strict is the High Schooler rule? I am 19 and an active person in the slack and was wondering if I'd be allowed to? If not, no worries!

**Review by Sheepy3 — COMMENTED** [review]
Hey, this project sounds awesome, but unfortunately we can only accept projects by those in highschool and under :( I still hope you manage to pursue this project some time in the future, and as you said you're active in the server, I'd love to see it some time!

**Review by Sheepy3 — COMMENTED** [review]
Apologies, I wasn't aware you were exempt from the highschooler rule 😓. Please disregard my previous review. 

Like I said, this project is awesome. Looking through all your components and PR plan, I think this project is already good to go. My only suggestion would be to elaborate further on how exactly you plan to build this project, but I will not request changes as I think it is already fairly adequate.

**Review by Sheepy3 — APPROVED** [review]

**Comment by bellesea** [comment]
woohoo! for context: @TejasCreative is joining the winter wonderland in a staff-like capacity!

**Review by MelSmith104 — COMMENTED** [review]
hey @TejasCreative holy crap i feel like this project literally was made for me. the amount of times i leave and walk away without bringing my keys (or my phone) with me is insane. im dm'ing you on slack now so that you can build this for me! jk jk but dm'ing you to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
