### PR TITLE
Create Puffball101961.md

### PR DESCRIPTION
**Pull request by Puffball101961**
## Describe your project in 1-3 sentences

A 128x32 RGB Matrix Price ticker that scrolls through various crypto and stock prices.

## Hack Club Slack handle

Puffball

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@Puffball101961 this looks awesome! just to confirm, do you have access to a 3d printer? also, what prices are you planning on tracking?

thank you so much!

**Comment by Puffball101961** [comment]
Hi, I have access to my own 3D printer (an ender 3). I am planning on tracking cryptocurrencies like Bitcoin, ethereum, polygon, tezos, and stocks like Google, Microsoft and Coinbase. I will build the software to allow any stock or crypto to be tracked, not just the above.

**Review by bellesea — APPROVED** [review]
@Puffball101961 this looks awesome!! thanks so much for adding some more details hehe :) an awesome member of the @hackclub/bank-ops team will reach out w/ next steps soon!

**Comment by hackliv** [comment]
hey @Puffball101961! this looks really cool. :) I'm dming you now about getting set up on Bank with the grant! also excited to hear which crypto is your fav!

**Review by hackliv — APPROVED** [review]

**Comment by Puffball101961** [comment]
Added $65 extra budget to buy RGB matrix panels locally instead of AliExpress

**Pull request merged**
