### PR TITLE
The TodayDisplay

### PR DESCRIPTION
**Pull request by Spartoons**
## Describe your project in 1-3 sentences

I'm creating a smarth screen for my room wall, to have the calendar, the agenda, see the clock and the weather and to appear some interesting news.

## Hack Club Slack handle

 @Spartoons

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm thinking: this feels very much like a software project so i'm not super sure if it fully fits the goals of this event?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @Spartoons :)

thanks for your response to our initial comment :) i fully hear that there's parallel's to the magic mirror but i think there's something a little different between connecting a screen to a controller & building a frame, assembling a mirror in front of a screen, and connecting all of that to a controller? further, it's super cool that you'll be connecting your pine 64 such that it connects to Notion, although that's a great idea it isn't really a project where you're "making" something?

some modifications we could consider would be adding some physical sensors to your controller and having that display on some sort of custom built interface, alongside your calendar, clock, weather data, etc. 

also, i'm wondering:
- what's the reason for having 2 Pine 64s AND a controller?
- i think your current pine 64 link is to an orange pi? is that intentional?

thank you! please let me know what you think :)

**Comment by Spartoons** [comment]
hey @bellesea  :-)
Thanks for the feedback, I have already changed the project file! I really appreciate your comment, the project may have been a bit poor, but with the new changes implemented, I think it is a much better project and one from which I can learn a lot more. The changes are as follows: I have added a temperature and humidity sensor, so that it can be seen on the on-display interface; also a microphone to record audio notes and a speaker to play them; in addition, it has LED lights of different colors to indicate depending on the mode it is in and buttons that can interact with the web directly from the Orange Pi, to record audio notes or play them. 

About your comments, I had put Pine 64 by mistake, because it was the one I was going to use at first, but it doesn't have everything I need. On the other hand, I had put that they were two because at now I’m living in two places at the same time, so it would be perfect for my to have a smartScreen in every place, and that was the original plan.

Thank you again for you review, I hope you like this new version us much as I do :)

**Review by bellesea — APPROVED** [review]
hey @Spartoons thanks for the changes! this looks super awesome!

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps :)

approving to move forward but i'm wondering, will you be coding the web interface yourself? also, can you please commit what you wrote in the comment about the plans with the LEDs etc. within your file? thank you :)

**Comment by Spartoons** [comment]
thanks for the approval @bellesea  !!
I have already commited all the elctronic parts in the file :)

As for the web interface, I intend to do it myself, but as long as I will probably have to ask for help from @Peiprjs  , a friend of mine. So the idea is to doit on my own,  but I will probablly end up asking for help from friends or through slack :)) 

Thanks!

**Comment by Peiprjs** [comment]
> As for the web interface, I intend to do it myself, but as long as I will probably have to ask for help from @Peiprjs , a friend of mine. So the idea is to doit on my own, but I will probablly end up asking for help from friends or through slack :))

Heey congraats! Sure, we can work on our projects during club hours!

**Review by daisybanks — APPROVED** [review]
Hi @Spartoons! I love the idea for your TodayDisplay smart screen! I'm dming you now on Slack to talk about next steps for getting you your grant!

**Pull request merged**
