### PR TITLE
PCB Business Card with NFC

### PR DESCRIPTION
**Pull request by maggie-j-liu**
## Describe your project in 1-3 sentences

I'm making a PCB business card that supports NFC for a link to my website.
 
## Hack Club Slack handle

@ maggie

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by VelocityDesign** [comment]
This is so cool!

**Review by cfanoulis — COMMENTED** [review]
Hey maggie! this sounds really cool (i actually kinda want one now lol)

Just a quick question, do you plan on covering the 21.22$ outside of your grant? thx in advance!

**Comment by maggie-j-liu** [comment]
yep!

**Comment by cfanoulis** [comment]
Alright, one more thing: I noticed that you mentioned having the PCB manufacturer assemble the PCBs for you. Are you certain you cannot do that yourself? I see you did include a soldering iron

**Comment by maggie-j-liu** [comment]
The parts are kinda small and i've never soldered before :(( jlc pcb has an option where you can have them assemble a certain number -- i'll probably have them assemble some and try to solder the rest myself, or solder on the larger pieces (led, capacitor, resistor) and have them assemble the nfc chip

**Review by cfanoulis — APPROVED** [review]
Sounds like a plan! A banker from @hackclub/bank-ops will be in touch shortly to get you on da hack bank

**Comment by maggie-j-liu** [comment]
yayy tysm! excited :D

**Review by daisybanks — APPROVED** [review]
Hey Hey hey @maggie-j-liu! So excited to be working together and for a chance to get to know you as I've seen you around Slack so much! Dming you now on slack to talk about getting you your grant!

**Pull request merged**
