### PR TITLE
DerrXF

### PR DESCRIPTION
**Pull request by DerrFX**
## Describe your project in 1-3 sentences

I am building a 3D printer to print Chirstmas gifts. This is my first time working on a hardware project, very excited.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
Hey @DerrFX :) Thanks for sharing this proposal, and absolutely love the idea of 3d printing gifts hehe! Although, it might not arrive in time for christmas haha, but definitely available for future use! 

I was wondering, are you following a guide of any sort on designing this 3d printer? 

And, would you be able to clarify your plan since some parts are a little vague...

Thank you so much!

**Review by bellesea — CHANGES_REQUESTED** [review]
@DerrFX https://www.instructables.com/3D-Printer-2/ is a great guide to follow, thanks for linking it! 

I noticed that in the guide the author ran into some issues with creating the x carriage out of wood, do you have a plan if you run into similar issues? Also, do you have the necessary tools to cut the wood?

And, i might have missed it but do you plan on purchasing cooler fans, linear and radial bearings etc.? 

This is an awesome project and super excited to see you build it!!

**Comment by bellesea** [comment]
> @DerrFX https://www.instructables.com/3D-Printer-2/ is a great guide to follow, thanks for linking it!
> 
> I noticed that in the guide the author ran into some issues with creating the x carriage out of wood, do you have a plan if you run into similar issues? Also, do you have the necessary tools to cut the wood?
> 
> And, i might have missed it but do you plan on purchasing cooler fans, linear and radial bearings etc.?
> 
> This is an awesome project and super excited to see you build it!!

heyyy @DerrFX hope you're doing awesome! following up to see if you're still interested in moving forward with this project?

**Comment by cfanoulis** [comment]
Hi @DerrFX! Thanks for your proposal. It's been a week since Belle's message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Hacky New Year!

**Comment by cfanoulis** [comment]
Hello! Unfortunately 2 days have passed, which means that I'll be closing this PR as stale. If you still wish to pursue a grant please let us know by replying to this PR before Jan. 15th

**Pull request closed without merging**
