### PR TITLE
Smart box

### PR DESCRIPTION
**Pull request by ThanatosXingYu**
## Describe your project in 1-3 sentences
This is a box that uses Raspberry Pi as the server, identifies different people through Bluetooth Address and displays each person's customized content at the same time. And it can also recognize and answer human questions through voice  recognition module

## Hack Club Slack handle
Thanatos Zhang

My Hack club slack handle is Thanatos Zhang, you may also see Thanatos in other profile.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @ThanatosXingYu, thanks for submitting this project! You mentioned using GPT, but I don't see that in your budget. Do you have API access for free?

**Comment by ThanatosXingYu** [comment]
> 

Hello, I have checked my GPT's api agiain just now. I have a free balance of $18 until April 1. I have checked the usage price of GPT's api, which is very cheap. The cheapest one is even 0.0004 $for 1000 tokens. And other apis, such as weather, have been found free and tested

**Comment by ThanatosXingYu** [comment]
hi @maxwofford, could you please check my project when you have time? It has been 4 days :)

**Review by maxwofford — APPROVED** [review]
Thanks for waiting! We've had so many PRs come in recently. It looks like everything is good to go here so I'll tag in @hackclub/bank-ops to get you set up.

**Review by daisybanks — APPROVED** [review]
Hi @ThanatosXingYu - this sounds really cool! Is this meant to alert you as to who has come home too? Like if you're seeing stocks show up you know your dad is home? I'm dming you now on Slack to set up a time to meet so i can explain next steps in getting you your grant. :)

**Pull request merged**
