### PR TITLE
Easternspork Project Summary and Budget

### PR DESCRIPTION
**Pull request by Easternspork**
## Describe your project in 1-3 sentences

I am building a humanoid robot, that hopefully has walking and talking capabilities.

## Hack Club Slack handle

@Easternspork 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@Easternspork woah this is super cool! i'm wondering, are you referring to any guide(s) for this? also, how do you plan on controlling the servos?

thanks :)

**Comment by bellesea** [comment]
Hi @Easternspork :) Thanks for your proposal. It's been a while since my message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Hacky New Year!

**Comment by Easternspork** [comment]
Sorry I hadn't realized it hadn't gone through - I'm still interested. For guides, I've looked through a bunch of youtube videos and blog posts about projects like this, but I don't really have one single "tutorial" type guide I can follow through. For the servos, I already have a servo controller that I believe can handle the amount of current that will be needed to control the servos, and I will control the servo controller with a raspberry pi I have with me.

**Comment by bellesea** [comment]
> Sorry I hadn't realized it hadn't gone through - I'm still interested. For guides, I've looked through a bunch of youtube videos and blog posts about projects like this, but I don't really have one single "tutorial" type guide I can follow through. For the servos, I already have a servo controller that I believe can handle the amount of current that will be needed to control the servos, and I will control the servo controller with a raspberry pi I have with me.

@Easternspork no worries! sounds good, will be back on Tuesday to resume the review! thanks :))

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @Easternspork this looks super cool! 

an awesome member of @hackclub/bank-ops will be reaching out with next steps!

approving to move forward but can you please:
- clarify if you'll be designing the parts of the robot yourself?
- add more details about where you'll be placing the different servos so we could visualise your robot's movement?

thank you sm!

**Review by bellesea — APPROVED** [review]

**Review by daisybanks — APPROVED** [review]
Hi @Easternspork! Your project sounds so cool and I can't wait to hear more about it! I'm dming you now on Slack so we can talk about next steps in getting you set up on Bank and getting you your grant!

**Pull request closed without merging**
