### PR TITLE
The all in one robot

### PR DESCRIPTION
**Pull request by Dhruv-Gupta123**
## Describe your project in 1-3 sentences

I am building an all in one robo that can  shoot using a weapon, can be controlled by gesture, can be controlled by phone, can be controlled by a wireless remote, can follow your hand,  can move away from your hand, can follow light, etc.
I am also making a second project in which a person can control any appliance by the movement of their hand.

## Hack Club Slack handle

Dhruv_Gupta

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
Hey @Dhruv-Gupta123, thanks for submitting this! This sounds like a really fun project. I'm going to approve it now with comments so we can get the grant out ASAP.

Could you update your comment about the weapon to clarify that it's a nerf shooter?

I wanted to check how the nerf shooter would be powered– is the bo motor fast enough to shoot something?

If you are using only some of the bo motors for the drive train, are you still going to make it tank drive? Are they strong enough to turn the vehicle?

**Comment by Dhruv-Gupta123** [comment]
The nerf shooter will be powered by bo motors as they have a 100rpm(rotations per minute) so it cant harm anyone.
Yes the motors are strong enough to move the tank as i have made such cars a long time ago i have measured how much wait 
the mots can lift and it was 1..5kg and the wait of the tank will be abut 500grams only.

**Comment by maxwofford** [comment]
@hackclub/bank-ops will be in touch shortly to get you onboarded!

**Comment by Dhruv-Gupta123** [comment]
OK Thanks!

**Review by MelSmith104 — COMMENTED** [review]
hey @Dhruv-Gupta123! i love how this robo does just about everything! it'll be interesting seeing it come to life! dm'ing you in slack to chat about next steps :)

**Comment by MelSmith104** [comment]
closing PR since they no longer wish to move forward

**Pull request closed without merging**
