### PR TITLE
Hardware allocation to VMs with kernel level assignments

### PR DESCRIPTION
**Pull request by SiruX21**
## Describe your project in 1-3 sentences

We are building a cloud computer that can handle two users at the same time for heavy tasks such as video editing, code compiling, and gaming. It will involve a lot of dependence on Hardware Encode and CPU cores.

## Hack Club Slack handle

Siru

## Checklist before submitting proposal:

- [✅] We are a current high school student (or younger).
- [✅] We have submitted an RSVP at <https://hackclub.com/winter>
- [✅] We are a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✅] We have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Look-Its-Sky** [comment]
I am in collaboration with @SiruX21 for this project

[✅] We are a current high school student (or younger).
[✅] We have submitted an RSVP at https://hackclub.com/winter
[✅] We are a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[✅] We have self-reviewed my project proposal.

**Comment by RartedRussian** [comment]
I am in collaboration with @SiruX21 for this project

[✅] We are a current high school student (or younger).
[✅] We have submitted an RSVP at https://hackclub.com/winter
[✅] We are a member of the Hack Club Slack (Join at https://hackclub.com/slack) Name - Eric Zazovsky
[✅] We have self-reviewed my project proposal.

**Comment by Cimbobimb** [comment]
I am in collaboration with @SiruX21 for this project

[✅] We are a current high school student (or younger).
[✅] We have submitted an RSVP at https://hackclub.com/winter
[✅] We are a member of the Hack Club Slack (Join at https://hackclub.com/slack) Name - Andres Perez
[✅] We have self-reviewed my project proposal.

**Comment by bellesea** [comment]
hey @SiruX21 @Look-Its-Sky @RartedRussian @Cimbobimb :)

thank you so much for making this PR! Unfortunately, this proposal doesn't quite meet the goals of the event.

the goal of Winter Hardware Wonderland is to make hardware hacking (creatively building things using the details of how electronics work) available to more people, but building a super computer doesn't really count. it just should be more lower level than plugging a few components together. i understand that you'll be setting up your own virtual machines which is super cool but you'd also be able to do that by renting cloud server space.

i'm going to close this pull request for now, but feel free to open a new one with a revised project proposal, or re-open this one if it's easier.

let me know if you have any questions! i've also DMed you in Slack and would be happy to chat more there. thank you :)

**Pull request closed without merging**
