### PR TITLE
Create sahitid.md

### PR DESCRIPTION
**Pull request by sahitid**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@sahitid wahoo this is awesome!! are you referencing any guides for this project?

and, how do you plan on programming your pi? will you be doing a headless set up (if so do you need an SD card reader or smth) or do you have a monitor, keyboard, and mouse w/ the relevant cables that you can connect?

i see that you're purchasing jumper wires, do you already have a breadboard?

also, do you need a power supply for your pi?

and, i see that some of the things (like the pi) are out of stock, do you have plans for where else you'd be able to purchase these items from?

thanks sm!!

**Comment by sahitid** [comment]
i think i'll be able to connect the pi via a LAN cable (which i own). sorry, i completely forgot about the breadboard! but i don't need an additional power supply (i can use a usb-c maybe?). i'll update my budget with the breadboard and a different pi distributer.

**Comment by bellesea** [comment]
> i think i'll be able to connect the pi via a LAN cable (which i own). sorry, i completely forgot about the breadboard! but i don't need an additional power supply (i can use a usb-c maybe?). i'll update my budget with the breadboard and a different pi distributer.

thanks for pushing the changes! do you need an SD card reader or is your computer already compatible with that? i'm thinking your initial set up might be smth like this? https://www.instructables.com/Set-Up-Raspberry-Pi-4-Through-Laptoppc-Using-Ether/

**Comment by sahitid** [comment]
yup, that's what i was planning to do + my computer has a built-in SD card reader

**Review by bellesea — APPROVED** [review]
@sahitid wahoo this looks awesome!! can't wait to see you build this :)

a fabulous member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by arianna-m — APPROVED** [review]
Hi @sahitid! This looks incredible! Your Motion Sensor Video Recorder sounds very helpful. I love how you thought through it, and I'm excited to see how it turns out! Next steps for us would be to move communications over to Slack so we can move forward! We can schedule a Zoom call, so I can explain how you get the grant and share with you the fiscal sponsorship contract which you'll have to sign with a parent/guardian. Looking forward to working together! :)

**Pull request merged**
