### PR TITLE
Create xi-forgetme.md

### PR DESCRIPTION
**Pull request by xi-forgetme**
## A mini Home NAS

Do you wanna have a mini NAS that can storage data or do hack for you?

Do you wanna have a home server build with open source hardware that can move everywhere by control?

Here is!

This is a mini NAS build with a RPi 4B, it can also controlled moving everywhere as long as you have a Internet connection

## Hack Club Slack handle

WandererInc

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Hey @xi-forgetme, thanks for submitting your proposal!

The intent of the grant is to support hardware hacking and learning how to do physical projects. The software stuff you're working on is awesome, but I wanted to see if there was any part you're planning to build that is physical. The intent of the hardware grant is to fund hardware-based projects. For example, you could design and build the enclosure and components for the NAS.

You can update this PR or reach out to me if you have any questions!

**Comment by xi-forgetme** [comment]
@maxwofford hey! Could you please check my PR again? Thank you very much!

**Comment by xi-forgetme** [comment]
> 

I see, I have changed the project to be smaller and more portable, then designed a mini car for the server host.

**Review by xi-forgetme — COMMENTED** [review]
Just changed a little bit lol

**Review by xi-forgetme — COMMENTED** [review]
Just changed my budget to by a camera so that I can make the NAS server car better to control

**Review by xi-forgetme — COMMENTED** [review]
@maxwofford sorry to trouble you again, please let me know if I need anything changed again, I'm not really good at using GitHub, thanks

**Review by maxwofford — APPROVED** [review]
Hey @xi-forgetme! Sorry for the slow review on this. Your updates to the project have been great. This is a completely ridiculous project and I love it.

I'm a bit surprised the totals add up to exactly $250. How did that happen?

I'm going to approve this, but please update the JD links– most of them aren't working. You can still buy from JD, but we want to show people what specific parts you're buying.

**Comment by maxwofford** [comment]
I'm tagging in @hackclub/bank-ops who will take it from here!

**Review by daisybanks — APPROVED** [review]
Hi @xi-forgetme! I'm so excited to see your project approved and ready for the next steps! This project is really cool! I'm dming you on Slack to talk about getting you your grant. :)

**Pull request merged**
