### PR TITLE
rfid nfc wallet

### PR DESCRIPTION
**Pull request by sol5000**
## Hack Club Slack handle
sol5000

## Checklist before submitting proposal:

- [V ] I am a current high school student (or younger).
- [V ] I have submitted an RSVP at <https://hackclub.com/winter>
- [V ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ V] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project, can you please elaborate more under your plan?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey @sol5000! Super interesting idea you've got here. Any way you think you could tie in a microcontroller or some electronics to jazz it up?

**Review by sampoder — CHANGES_REQUESTED** [review]
That sounds great! Would you like to rework your plan + budget to include that?

**Comment by sampoder** [comment]
Could you add the details to your plan as well?

**Review by sampoder — APPROVED** [review]
🌈 ❄️  Welcome to a Winter Hardware Wonderland! ☃️ ✨

**Comment by bellesea** [comment]
hey @sol5000 a member of @hackclub/bank-ops will be reaching out early next week with next steps :) thanks for your patience!

**Review by daisybanks — APPROVED** [review]
Hi @sol5000 -this project sounds wicked cool and convenient! I'm dming you on Slack now to talk about next steps in getting you your grant. :)

**Comment by bellesea** [comment]
@sol5000 we'll merge it once the grant has been given :)

**Pull request merged**
