### PR TITLE
RC Quadcopter DIY

### PR DESCRIPTION
**Pull request by btechboy**
## Describe your project in 1-3 sentences
I am going to build a quadcopter which will help revolutionize the arena of automated farming.
I wanted to make it because it will open up many possibilities in my current field of study as i can monitor larger crop fields and keep the track of crops' health.

## Hack Club Slack handle
@btechboy

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy @btechboy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted (eg. i noticed some parts of your budgets don't have price, is it because you already have it?), you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits).

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @btechboy this looks super cool!

a few things:
- are you referencing any sort of guides for this build?
- have you checked that all the components are compatible with each other? 
- do you have any ideas on extending or modifying this build to make it your own in anyway?
- the total is a little above the max $250 per person, will you be able to cover the excess?

thank you!

**Comment by btechboy** [comment]
hey @bellesea , thanks for reviewing my PR.

- Yes, I am referring to some YouTube tutorials that I found helpful for me in setting up the drone and the flight controller. You can check them out here.
   

>  [1st tutorial](https://youtu.be/I8ugqKsMIpE)

> [2nd tutorial](https://youtu.be/FhlMFzumsVg)

- Yes, I have checked that all the components are compatible with each other.
- Yes, I have thought about adding some modifications (little bit of redesign) in frame and motor placing for that I will use some homemade stuff or may be some toys which I already have (I will go with whatever looks better on the drone). Furthermore, if I get some days remaining, I will try adding some extra features to it.
- Yeah, If I get approval for this, I am ready to cover up the extra expenses as I have already mentioned that this will be a great jump-start for me.

**Review by btechboy — COMMENTED** [review]
required changes done.

**Comment by bellesea** [comment]
an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by MelSmith104 — COMMENTED** [review]
hi @btechboy! this drone sounds like a really fun project to build! i'm dm'ing you on slack right now so that we can chat about next steps!

**Review by btechboy — COMMENTED** [review]
hey @bellesea, I have added the changes that you asked for.

- I want to tell you if my budget allowed to extend it then I thought of adding a ESP32 camera module and automatic sprinkler to the drone, but for now I am more focused on making a bot that can fly up above in the sky.

**Comment by bellesea** [comment]
> hey @bellesea, I have added the changes that you asked for.
> 
> * I want to tell you if my budget allowed to extend it then I thought of adding a ESP32 camera module and automatic sprinkler to the drone, but for now I am more focused on making a bot that can fly up above in the sky.

@btechboy thank you so much! that's a super cool idea, hopefully you can add onto it after you build this drone hehe :)

**Comment by btechboy** [comment]
sure @bellesea, I will try my best to complete it :)

**Review by MelSmith104 — APPROVED** [review]

**Review by btechboy — COMMENTED** [review]
.

**Pull request merged**
