### PR TITLE
Create winstoniskandar&mayuridev.md

### PR DESCRIPTION
**Pull request by winstoniskandar**
## Describe your project in 1-3 sentences

We are building a LED light display that can be controlled by audio input.

## Hack Club Slack handle
@Winston, @DylanIskandar

## Checklist before submitting proposal:

- [Yes] I am a current high school student (or younger).
- [Yes] I have submitted an RSVP at <https://hackclub.com/winter>
- [Yes ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [Yes] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hey there! Thanks for your proposal! I have some questions regarding your budget items:

 - I see you have included a raspi compute board, while you haven't included any compute modules. Can you please explain how you're planning to use it?
 - How will you be powering the Arduino? Do you have a power supply from older projects?
 - How will you be controlling the lights? Do you need a seperate controller to connect them to Arduino?
 - I see you haven't included any breadboards, or wires, or soldering tools. How will you be connecting everything together
 - Have you factored in shipping costs & taxes?

Also, can you please have your partner comment on this github PR confirming they have completed the checklist as well? Thanks

**Comment by winstoniskandar** [comment]
- Sorry I forgot to remove that from the list, at first we wanted to use a raspberry pi but chose to go with an Arduino instead.
- We already have a power supply from an old project. I believe its something like this (https://www.amazon.com/Arduino-Power-Supply-Adapter-110V/dp/B018OLREG4)
- Forgot this. Just added the resistors/transistors
- We have these materials from past projects.
- Yup!

**Comment by mayuridev** [comment]
Checklist before submitting proposal:
[Yes] I am a current high school student (or younger).
[Yes] I have submitted an RSVP at https://hackclub.com/winter
[Yes ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[Yes] I have self-reviewed my project proposal.

**Comment by cfanoulis** [comment]
Great! And finally... how are you going to be receiving audio input? I don't see a microphone in your budget 🤔

**Comment by winstoniskandar** [comment]
We have a regular pair of apple cabled headphones that we can plug into the arduino. (I changed the arduino to fit our project)

**Comment by cfanoulis** [comment]
Great, how will that be connected to the board?
Also, I still don't understand how the BOSE speaker connects to this - will you be connecting it to the adruino and giving input from there as well?

**Comment by winstoniskandar** [comment]
Not sure, I just read online that it could be handy. I figured I could just set them up on the breadboard and connect the wiring.
Yes, that's correct. I will use the analog input pin and set that up through there.

**Review by cfanoulis — APPROVED** [review]
Cool! I'm going ahead and approving this - but frankly I think a BOSE speaker is overkill for this. If you can find something cheaper please go for it ;)

In the meantime, a banker from @hackclub/bank-ops will be in touch shortly to get you setup with your grant

**Comment by winstoniskandar** [comment]
Awesome, thanks so much!

**Comment by winstoniskandar** [comment]
Hi, are there any updates on this? I just heard that the project deadline is Jan 15. and I didn't want to come too close to the deadline.

**Pull request merged**
