### PR TITLE
Create Steve-Dusty.md

### PR DESCRIPTION
**Pull request by Steve-Dusty**
## Describe your project in 1-3 sentences

my project:
A DIY beginner project by feeding my cat using the system. helps learn the hardware of basics fast

## Hack Club Slack handle

@stevedusty

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Steve-Dusty** [comment]
my project:
A DIY beginner project by feeding my cat using the system. helps learn the hardware of basics fast

**Comment by devramsean0** [comment]
you need to list a budget lol

**Comment by Steve-Dusty** [comment]
@devramsean0 I did. Look at my markdown

**Comment by devramsean0** [comment]
oh right yeah, forgot about the markdown lol

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project, it looks super cool! could you please expand in your file a little more about how the "food drop mechanism" would work?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by Steve-Dusty** [comment]
@bellesea The drop mechanism is basically a 3/4 made with plastic. The cardboard will have a small hole beneath it, and the 3/4th circle would cover it. When it's ready to drop food, the servo will rotate the circle to where the 1/4th opening is, and food will be able to drop through that opening.

**Comment by bellesea** [comment]
> @bellesea The drop mechanism is basically a 3/4 made with plastic. The cardboard will have a small hole beneath it, and the 3/4th circle would cover it. When it's ready to drop food, the servo will rotate the circle to where the 1/4th opening is, and food will be able to drop through that opening.

@Steve-Dusty that sounds awesome! and do you have the materials you need to build this mechanism? also, can you please add these details to your file?

btw, we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Comment by Steve-Dusty** [comment]
@bellesea I can create the parts on my own with the supplies that I have. It doesn't need much material (cardboard, plastic bottles works). May I ask if I could edit the file to add a 3D printer to my list to help me create custom parts?

**Comment by bellesea** [comment]
@Steve-Dusty sure! would you be able to cover the excess? thanks :)

**Comment by Steve-Dusty** [comment]
> @Steve-Dusty sure! would you be able to cover the excess? thanks :)

Yes

**Review by bellesea — CHANGES_REQUESTED** [review]
@Steve-Dusty this is super cool!

a few more things:
- add details in under plan about how your food drop mechanism would work + that you'll be designing it yourself
- update your elegoo start kit with mega board link, rn it's incomplete 
- how would your app communicate with your arduino mega? i don't believe it's wifi/bluetooth compatible and i think you'd need an extra component? 
- how will you run openCV on your arduino?

thanks!

**Comment by Steve-Dusty** [comment]
> @Steve-Dusty this is super cool!
> 
> a few more things:
> 
> * add details in under plan about how your food drop mechanism would work + that you'll be designing it yourself
> * update your elegoo start kit with mega board link, rn it's incomplete
> * how would your app communicate with your arduino mega? i don't believe it's wifi/bluetooth compatible and i think you'd need an extra component?
> * how will you run openCV on your arduino?
> 
> thanks!

ah, thank you for catching those mistakes. fixed!

**Review by bellesea — APPROVED** [review]
@Steve-Dusty awesome!!

a fabulous member of @hackclub/bank-ops will be reaching out soon with next steps :)

approving to move forward but can you please specify the rpi that you have so this file can serve as a more comprehensive report of your project? and to confirm you already have the usb cable you need? thanks!

**Comment by Steve-Dusty** [comment]
> approving to move forward but can you please specify the rpi that you have so this file can serve as a more comprehensive report of your project? and to confirm you already have the usb cable you need? thanks!
I updated the file. Yes, I have the USB cable

**Review by daisybanks — APPROVED** [review]
Hi @Steve-Dusty! I love that you want to create your own feeding system for your pet and I'm sure they'll love it as well! I couldn't seem to find you on Slack with the handle you provided. Would you mind dming me to talk about next steps?? My handle is @daisy. :)

**Pull request merged**
