### PR TITLE
Custom dot. style NFC Business Cards

### PR DESCRIPTION
**Pull request by CamTheHelpDesk**
## Describe your project in 1-3 sentences

I am building custom dot. style NFC business cards out of wood that operate on my own infrastructure.

## Hack Club Slack handle

@camdan.me

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Thanks for submitting your plan @CamTheHelpDesk! Just a couple questions:

- I saw you're purchasing an NFC Writer. I think many phones have that built in now (I just checked on my iPhone & was able to write a tag– bet there's something out there for Android too). Do you need to buy one?
- What other projects are you going to use the laser cutter for? It looks like the majority of the project is setting up the NFC cards & connected websites, so if there are things that really need the laser cutter we'd want to show that.

**Comment by CamTheHelpDesk** [comment]
Hi @maxwofford,

Thanks for the questions!

- I did clarify your first question in my write-up, `"I need an NFC encoder because my phone happens to be among the few that doesn't support NFC yet."` So yes, unfortunately I do need a writer- but I chose the least expensive one I could find that I still believe will work.
- Regarding why I want to laser cutter; a majority of the project certainly is setting up the connectivity features, but I've seen a few laser cut business cards before (minus the connectivity features), and they're really unique and memorable so that certainly is a priority. While I could, in theory, simply print the cards, I also see this as a fantastic opportunity to learn digifab software, hardware, and techniques. In addition, I've been eyeballing a few other projects, such as a wooden globe as a gift for a teacher I've had for most of my life, a custom stand to integrate my dock for my laptop, a laser pointer projector with some motors and mirrors, wooden mechanical sculptures, along with other miscellaneous art projects created to further my learning.

Thanks again!

**Review by maxwofford — APPROVED** [review]
Thanks for clarifying! I'm going to approve this but could you please update the README to mention the other things you're planning to laser cut? Thanks!

**Comment by CamTheHelpDesk** [comment]
Sweet, thank you so much! I went ahead and updated the README.

**Review by MelSmith104 — COMMENTED** [review]
hey @CamTheHelpDesk i love that you chose something that you also really want to use! this project sounds really cool and im excited to see your cards :) im dm'ing you right now to chat about next steps!!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
