### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by wollygfx**
If this a bug fix, documentation update, or other, please describe the purpose of this pull request below:

I need to buy a SD card for my raspberry pi

### CODE REVIEW

**Review by ivoinestrachan — COMMENTED** [review]
Hey what will you need the storage for, is it store the videos?
or is it to store more files?

**Comment by wollygfx** [comment]
I need to install an OS to the raspberry pi

**Comment by wollygfx** [comment]
and i might need to install some software to it

**Comment by wollygfx** [comment]
sorry, i was not aware that i needed the sd card before submitting the project at first

**Comment by ivoinestrachan** [comment]
Hey, alright cool ,@hackliv  we can move forward with this purchase

**Review by hackliv — APPROVED** [review]

**Review by ivoinestrachan — APPROVED** [review]

**Pull request merged**
