### PR TITLE
IoT Plant Watering System

### PR DESCRIPTION
**Pull request by Verisimilitude11**
## IoT Plant Watering System

I am going to build a smart plant watering system that uses a microcontroller and sensors to automatically water my plants based on soil moisture levels. I am excited to build this project because I love plants, but I often forget to water them. This system will help me take better care of my plants and save water by only watering when needed.

## Hack Club Slack handle

Should be @Verisimilitude11.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Verisimilitude11** [comment]
Hey, I see that all of the PRs before and after me have been reviewed - is there anything I need to do?

**Review by bellesea — CHANGES_REQUESTED** [review]
hiiii @Verisimilitude11 this is great!!

a few questions:
- what do you think about writing your own software for this (your board is compatible w/ Arduino IDE/Micropython) instead of using Blynk? i think you'd be able to learn a lot more and have more fun doing this? there are tons of guides that you'd be able to find online to guide you... if you're down for this, could you please add it to your plan?
- what's the role of the 2-channel relay module?

thank you!

**Comment by Verisimilitude11** [comment]
Hi @bellesea, thanks for the reply! To answer your questions:
1. This is a great idea, thanks for telling me! I'm totally down for this; I added it to my plan.
2. The 2-channel relay module controls the flow of electricity to the pump. The relay acts as a switch, which will allow me to turn the pump on and off using the microcontroller. When the relay is "closed," electricity can flow through it to the pump, and when it is "open," the flow of electricity is interrupted.

One question: How might I go about getting more parts later on if necessary (e.g., if there's a short circuit with one of the parts or something similar)?

Let me know if you need anything else! Thanks again for this opportunity!

**Comment by Verisimilitude11** [comment]
Also I'm very familiar with programming so do you think it would be possible to make my own app using Java or Swift?

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @Verisimilitude11 thanks for elaborating! for your relay, wouldn't the relay module you have in your budget already work? i'm wondering why are you including both a single and 2-channel relay module?

and if you need to add onto your budget later on you'd just chat with the hack club bank person you'll be in contact with hehe :)

for the code, yes you can def do that! check this out: https://lastminuteengineers.com/creating-esp8266-web-server-arduino-ide/ (and there are also plenty of other guides online)

**Comment by Verisimilitude11** [comment]
Ohh, good catch! I was planning on initially using a different guide which suggested using a 2-channel relay instead of the single-channel one. I removed it from the list and recalculated the total price. Sorry about that.

I got it; sounds good!

Thanks for the guide! This looks really interesting; I added it to my plan.

Is there anything else you'd like me to do or any other clarifying questions?

**Review by bellesea — APPROVED** [review]
@Verisimilitude11 thank you so much for pushing the changes and your rapid response :)

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
