### PR TITLE
My project proposal

### PR DESCRIPTION
**Pull request by PasinduDushan**
## Describe your project in 1-3 sentences

I am building an Arduino CNC plotter machine. You can convert normal images to machine understandable code using a custom dashboard I make in this project. This will be a very unique project for me as I spend a lot of time Infront of the computer and really want to find out about the physical side of electronics.

## Hack Club Slack handle

Pasindu Dushan

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by PasinduDushan** [comment]
Sorry for doing a lot of commits. :)

**Review by MelSmith104 — COMMENTED** [review]
hi @PasinduDushan ! this project sounds so amazing! some people here at hack club bank also built a CNC machine recently and it was so cool! for next steps can you please send me your slack ID?

**Comment by PasinduDushan** [comment]
Here you go.

Display Name - Pasindu Dushan
ID - U04FJLBBHN2

**Comment by MelSmith104** [comment]
@PasinduDushan just dm'ed you!

**Review by MelSmith104 — COMMENTED** [review]
super excited about your project and for our call tomorrow!

**Pull request merged**
