### PR TITLE
Proxmox Home Server and Lab

### PR DESCRIPTION
**Pull request by grammarfruit**
## Describe your project in 1-3 sentences

Me and my sister are going to build a multipurpose home server and lab, which will be running Proxmox a type 1 hypervisor that runs on Debian Linux. We will be using it for home assistant and node-red, which I will use to create an app to integrate our garage door and front door locks to close when we leave the house, and fun things with the lights. We will also be using it as a home lab for prototyping and creating our own flavor of Linux as with Proxmox we won't have to replace the operating system on our laptop.

## Hack Club Slack handle

grammarfruit

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by roseappletpe** [comment]
Hi! I'm his sister who is also working on this

slack - roseapple.tpe

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Helloooo :) Unforunately, we're not able to approve this proposal, as we're looking for projects that get you down to the nityy-gritty of electrical components - not assembling a computer with commercially available components like CPUs & RAM sticks.

I'll be closing this PR - however I'm able to grant you a one-time extension to the deadline if you want to submit a new project ✨ If you do, please submit a new proposal by January 19th (00:00 UTC) & mention this PR's ID (#352). Have a hacky day!

**Comment by grammarfruit** [comment]
> Helloooo :) Unforunately, we're not able to approve this proposal, as we're looking for projects that get you down to the nityy-gritty of electrical components - not assembling a computer with commercially available components like CPUs & RAM sticks.
> 
> I'll be closing this PR - however I'm able to grant you a one-time extension to the deadline if you want to submit a new project ✨ If you do, please submit a new proposal by January 19th (00:00 UTC) & mention this PR's ID (#352). Have a hacky day!

I saw that pull #266 was approved for a similar project, and I thought that building a flavor of linux would be pretty hacky and cool

**Pull request closed without merging**
