### PR TITLE
Update_LexHarie.md

### PR DESCRIPTION
**Pull request by LexHarie**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
From a technical perspective, this looks like its good to go! Sweet idea @LexHarie! Just to help things go smoothly in the next stage, could you update your PR comment to complete the template?

**Review by daisybanks — APPROVED** [review]
Hi @LexHarie! I love this project idea! Could you please be sure to fill out the checklist for your pr? I'll be dming you on Slack to talk about getting you on Hack Club Bank so you can access and use your grant! :)

**Comment by daisybanks** [comment]
Actually it looks like you're missing your Slack handle in your pr - could you please reach out to me on Slack? My Slack handle is @daisy.

**Comment by bellesea** [comment]
> @daisybanks @bellesea @sampoder
> 
> image image
> 
> my order got canceled on Amazon, and I'm 1 battery short (since I have 1 extra), and if I order on amazon right now, it may take a while. We do have a local reseller here that can give me the battery before February 14, if I only I can use the virtual card but the balance hasn't been refunded yet by Amazon, or idk.

@LexHarie oh no :( we'll see what we can do but it's the weekend so it might have to wait till monday morning ET. hope we can figure smth out together!

**Pull request merged**
