### PR TITLE
Custom Keyboard Firmware

### PR DESCRIPTION
**Pull request by samanthahuaa**
## Describe your project in 1-3 sentences

We are coding our own keyboard firmware by creating forks of QMK. We will build our first mechanical keyboards in order to test our firmware.

## Hack Club Slack handle

@Samantha H and @Courtney Huang

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by courtneyhg** [comment]
I'm so excited to work on this project alongside Samantha so we can build keyboards with increased functionality to make our lives more efficient when we use our computers!

- [ x]  I am a current high school student (or younger).
- [ x]  I have submitted an RSVP at https://hackclub.com/winter
- [ x]  I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [ x]  I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: what do you mean by creating forks of QMK? will you be writing your own version of QMK or using QMK? thank you!)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by samanthahuaa** [comment]
We planned on using QMK to write our own custom key layouts. We will fork the QMK repo in order to edit the template key layouts and add our special touches to the layout of the keyboards we'll build. Is this not "techy" enough for this grant? We are open to editing our proposal!

**Comment by bellesea** [comment]
> We planned on using QMK to write our own custom key layouts. We will fork the QMK repo in order to edit the template key layouts and add our special touches to the layout of the keyboards we'll build. Is this not "techy" enough for this grant? We are open to editing our proposal!

hey @samanthahuaa modifying QMK is a step in the right direction but we'd actually encourage you to think about expanding the project more to allow for deeper understanding of low-level hardware such as making your own firmware from scratch! if you have any questions about this i highly encourage you to check out [#hardware-party](https://hackclub.slack.com/archives/C0168BR5PDE) or [#keyboard](https://hackclub.slack.com/archives/C01BFAM700N) in the Slack hehe :)

we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, and if you'd be interested in editing your proposal in anyway we'd highly welcome that :)

**Review by alhardwarehyde — APPROVED** [review]
You two have clearly both put a lot of thought in this and I love that you decided to work on this together. 

@hackclub/bank-ops to take it from here!

**Comment by alhardwarehyde** [comment]
Sorry about the mixup! This PR got approved by mistake and still needs to go through review which we will be working on shortly!

**Review by MelSmith104 — COMMENTED** [review]
hey @samanthahuaa and @courtneyhg! this looks like such a fun build to do together! im so excited to hear more about your project! im dm'ing you both on slack right now to get the process started :)

**Review by alhardwarehyde — APPROVED** [review]
Sorry again about the confusion! Approved and tagging bankops again just in case! @hackclub/bank-ops

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
