### PR TITLE
Media Deck

### PR DESCRIPTION
**Pull request by edmundlzen**
## Describe your project in 1-3 sentences

I am building a media deck that has a lot of uses, multimedia control, stock market price ticking, notification displaying, macro keys, etc.

## Hack Club Slack handle

Edmund

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@edmundlzen this is awesome!! just to check, do you already have access to a breadboard and jumper wires? also, do you need something like a protoboard for when you actually solder it together?

thanks :)

**Comment by edmundlzen** [comment]
@bellese yes! I already have the breadboard and jumper wires at home, I'll add those to the budget now. I think for the protoboard I'll try and find it locally and buy it myself.

**Comment by bellesea** [comment]
> @Bellese yes! I already have the breadboard and jumper wires at home, I'll add those to the budget now. I think for the protoboard I'll try to find it locally and buy it myself.

great, thank you sm!

**Comment by bellesea** [comment]
@edmundlzen one more small check, do you have what you need in order to program your banana pi?

**Comment by edmundlzen** [comment]
@bellesea I originally intended to just use ssh to control the banana pi but I guess just in case, I'll get a mini HDMI Cable also. I added the cost for that and the shipping to the budget

**Comment by edmundlzen** [comment]
Oh yeah, and I'm aware that I'll cover the balance by myself. 👍🏻

**Comment by bellesea** [comment]
> @bellesea I originally intended to just use ssh to control the banana pi but I guess just in case, I'll get a mini HDMI Cable also. I added the cost for that and the shipping to the budget

cool! ssh is also ok hehe, do you already have the SD card and a card reader?

**Comment by edmundlzen** [comment]
@bellesea I have the sd card at home and I'll use an old mac to write the sd card with! I added the sd card in the budget. 👍🏻

**Review by bellesea — APPROVED** [review]
@edmundlzen this looks awesome!! can't wait to see this media deck come to life :)

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Comment by edmundlzen** [comment]
This was much faster than I imagined 🏃🏻 . Thank you so much for the help!

**Review by daisybanks — APPROVED** [review]
Hi @edmundlzen! This looks great! I love the attention to detail and how well thought out your plan is, and I'm excited to see the end result! I'm dming you on Slack now so we can talk about getting you your grant. :)

**Pull request merged**
