### PR TITLE
LED and Speaker Connected "Alarm"

### PR DESCRIPTION
**Pull request by sai-nallani**
## Describe your project in 1-3 sentences
A network of speakers and led lights that can be used to change other's lights and say something through
speakers.

## Hack Club Slack handle
sxbuto

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: why are you purchasing a smart light bulb? and, how would you build your api? also, do you have what you need to program the pico?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by devramsean0** [comment]
What are you going to be using the raspberry pi for?

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey @sai-nallani! Sounds like a cool project! If you wouldn't mind, I'd love to work on making your plan slightly more detailed.

What's your plan for connecting the Pico to the lights to the speakers? & what do you think about using Adafruit's NeoPixels over a commercial bulb?

**Comment by bellesea** [comment]
hey @sai-nallani hope you're doing awesome! it's been two days since sam's request for changes, i'm wondering, when do you think you'll be able to make the changes? we'd love to move forward with reviewing this PR so you can get your parts in time for the event :) thanks!

**Comment by sai-nallani** [comment]
> hey @sai-nallani hope you're doing awesome! it's been two days since sam's request for changes, i'm wondering, when do you think you'll be able to make the changes? we'd love to move forward with reviewing this PR so you can get your parts in time for the event :) thanks!

I'm sorry for not replying. I was busy with tons of school work. I will make the changes over the weekend probably.

Also, I need some help determining what exactly I need.

@devramsean0 I need a raspberry pi as a microcontroller to handle requests from my API to turn the smart light on and off.

The smart light is needed because it is open source (kind of) and it is compatible with api requests.

So, I will use a raspberry pi to control a smart light and speaker. The API is going to be on the web, and the raspberry pi will have a "listen" port where it listens to requests from the server. What suggestions do you guys have?

**Comment by sai-nallani** [comment]
> Hey @sai-nallani! Sounds like a cool project! If you wouldn't mind, I'd love to work on making your plan slightly more detailed.
> 
> What's your plan for connecting the Pico to the lights to the speakers? & what do you think about using Adafruit's NeoPixels over a commercial bulb?

I think that is a good idea! I think that is more customizable as well.

**Review by sai-nallani — COMMENTED** [review]
approving

**Comment by sampoder** [comment]
Could you expand your plan to include the following?

> > Hey @sai-nallani! Sounds like a cool project! If you wouldn't mind, I'd love to work on making your plan slightly more detailed.
> > What's your plan for connecting the Pico to the lights to the speakers? & what do you think about using Adafruit's NeoPixels over a commercial bulb?
> 
> I think that is a good idea! I think that is more customizable as well.

**Comment by sai-nallani** [comment]
> Could you expand your plan to include the following?
> 
> > > Hey @sai-nallani! Sounds like a cool project! If you wouldn't mind, I'd love to work on making your plan slightly more detailed.
> > > What's your plan for connecting the Pico to the lights to the speakers? & what do you think about using Adafruit's NeoPixels over a commercial bulb?
> > 
> > 
> > I think that is a good idea! I think that is more customizable as well.

Certainly.

1. My School's engineering room has a soldering iron kit, and using that i will attach the headers to the pico. I think I will also change the headers from male to female because then I wouldn't need to use a bread board.

2. Next, I looked at Adafruit's Neopixels. I believe I can simply just connect the Neopixels' pins to the pico. I will also find a external power source. 

3. Afterwards, I will attach the speakers to the pico. Since they are speakers designed to connect to the raspberry pi, I don't think there is a problem with that.

4. To contain all the wiring, I will design a 3d-printed container (provided with by my school's engineering class) to contain the hardware. 

Next step, API

As you may have noticed, I chose a Pico W to include wireless capabilities. Building the API would be fairly simple. The challenging part would be making it work with the PICO. I think to actually do it, I would need to have a small web server running on the Pico. This is where I was thinking instead of getting a Pico, should I get a Zero W? It has more ram, so it may be able to support a web server more efficiently than the Pico. Do you believe that a Pico could support a small web server?

Or another possible solutions is to use web sockets.

The web socket would be a runner program running on the Pico, and it would be connected to a server that is always running located in my home or located in the cloud. The RPI would be sending requests to the server, and the server will establish a web socket with the RPi. The web socket establishes a constantly running communication port between the server and the pico. This is what chat applications use for real-time communications, so I think web sockets would be a more efficient solution.

This is my skeletal plan right now, and I am open to more suggestions. Do you have any other ideas?

**Review by sampoder — COMMENTED** [review]
☃️ ❄️ Welcome to a Winter Hardware Wonderland! 🦕 ✨ 

To help @hackclub/bank-ops, could you add the plan and the parts required you commented to your Markdown file?

**Review by sampoder — APPROVED** [review]

**Comment by sai-nallani** [comment]
> ☃️ ❄️ Welcome to a Winter Hardware Wonderland! 🦕 ✨
> 
> To help @hackclub/bank-ops, could you add the plan and the parts required you commented to your Markdown file?

Done.

**Review by MelSmith104 — COMMENTED** [review]
hey @sai-nallani :) this project sounds really fun lol i especially like the part about why you want to build it :) im dm'ing you on slack right now to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
