### PR TITLE
smart Mirror

### PR DESCRIPTION
**Pull request by SantoshiUser**
I building the new proposal after previous proposal was closed, so i was given another time to open new PR ,mention the id 372 so, i am mentioning it. here.

### CODE REVIEW

**Comment by amareshw** [comment]
I will be working together on this Project with @SantoshiUser .

**Comment by bellesea** [comment]
#372

**Comment by cfanoulis** [comment]
hey! unfortunately due to [policy](https://hackclub.slack.com/archives/C0168BR5PDE/p1674229327663039), we cannot add any new members to a declined PR, as it's past Jan 15th

The original PR was for a 1-man team, so the max. grant will be 250$ - is that ok?

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hey, I need you to delete the old proposal file - please do so before I can review :)

**Comment by SantoshiUser** [comment]
> hey! unfortunately due to [policy](https://hackclub.slack.com/archives/C0168BR5PDE/p1674229327663039), we cannot add any new members to a declined PR, as it's past Jan 15th
> 
> The original PR was for a 1-man team, so the max. grant will be 250$ - is that ok?

actually the original PR was also the two man team, here is the link of the original PR where in summary we have mentioned we both will be working together. link:https://github.com/SantoshiUser/winter/blob/main/SantoshiUser.md

**Comment by SantoshiUser** [comment]
> Hey, I need you to delete the old proposal file - please do so before I can review :)

okay, we will delete the delete the old proposal file, before that can u please accept this request on behalf of both of us. @SantoshiUser  and @amareshw

**Comment by cfanoulis** [comment]
> actually the original PR was also the two man team, here is the link of the original PR where in summary we have mentioned we both will be working together. link:https://github.com/SantoshiUser/winter/blob/main/SantoshiUser.md

In your original PR (#372) I do not see any other team member that has commented or you mentioning that you have another team member before I reviewed your PR.

If you cannot cover costs above 250$ please understand we cannot proceed with your proposal

**Comment by amareshw** [comment]
Really sorry for the misunderstanding @cfanoulis .
Actually, we had pulled two request ,one at 372 by @SantoshiUser and 373 by me .We were working on the same project, so pull request of 373 was closed having said that it is same project. so here is the link of 373 https://github.com/hackclub/winter/pull/373, and here is the link of that PR : https://github.com/amareshw Hope you haven't misunderstood what we are trying to say because of my poor english😅.

**Comment by SantoshiUser** [comment]
i have deleted the old old proposal file

**Comment by jianmin-chen** [comment]
It's absolutely okay! We'll provide the $500 total grant because you guys made two PRs for the same rejected project before (I'm assuming it was a mistake). I'll take a look into a project and see if there's anything that needs to be changed!

**Comment by SantoshiUser** [comment]
> It's absolutely okay! We'll provide the $500 total grant because you guys made two PRs for the same rejected project before (I'm assuming it was a mistake). I'll take a look into a project and see if there's anything that needs to be changed!

sure Ma'm

**Review by jianmin-chen — APPROVED** [review]
Okay, everything looks good to go for the most part! @hackclub/bank-ops will be reaching out soon :)

**Review by jianmin-chen — APPROVED** [review]

**Comment by SantoshiUser** [comment]
> Okay, everything looks good to go for the most part! @hackclub/bank-ops will be reaching out soon :)

I am really excited for this , Thanks for your approval :)

**Review by daisybanks — APPROVED** [review]
Hi @SantoshiUser and @amareshw! Everything is sounding and looking good! I'm excited to get you guys set up with your grants so you can start ordering your parts! I'm dming you both on Slack in a group chat now!

**Comment by dhruvaop** [comment]
I want to work on this project/issue

**Pull request merged**
