### PR TITLE
Home-Environment-Monitor (HEV)

### PR DESCRIPTION
**Pull request by thomaswcy**
## Describe your project in 1-3 sentences

I am building a Home-Environment-Monitor (HEV) using RaspberryPi 4b. I am building this with my friend @MeliLXT. This is my first raspberrypi project.

## Hack Club Slack handle
@thomaswcy and @MeliL

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — CHANGES_REQUESTED** [review]
Thanks for submitting @thomaswcy! If @MeliLXT is working on this with you please have them comment to confirm.

What are you planning to do with the sensor input? Will this run as a dashboard? Or a webserver that any of your devices can connect to for seeing the conditions at your house?

**Comment by thomaswcy** [comment]
OK. It will be a dashboard, but it will be deployed as a webserver to make the process of building UI componments easier. @MeliLXT will be replying to this PR later in today.

**Comment by MeliLXT** [comment]
> ## Describe your project in 1-3 sentences
> 
> I am building a Home-Environment-Monitor (HEV) using RaspberryPi 4b. I am building this with my friend @MeliLXT. This is my first raspberrypi project.
> ## Hack Club Slack handle
> 
> @thomaswcy and @melil
> ## Checklist before submitting proposal:
> 
>     * [x]  I am a current high school student (or younger).
> 
>     * [x]  I have submitted an RSVP at https://hackclub.com/winter
> 
>     * [x]  I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
> 
>     * [x]  I have self-reviewed my project proposal.

I am Meli and I am building the project with #thomaswcy.

**Review by maxwofford — APPROVED** [review]
Thanks for addressing the comments! I'm approving this & can't wait to see what it looks like once you have everything deployed.

@hackclub/bank-ops will be in touch to send the funding!

**Review by daisybanks — APPROVED** [review]
Hi @thomaswcy and @MeliLXT! It was nice to see you guys again today! :) I'm excited you're joining us for WHW and your project sounds really cool! I sent you both the contract and once I get that back after you and your parents have signed I'll set up another account on Bank for you and get you your grants there!

**Pull request merged**
