### PR TITLE
Create Create AHussein04.md

### PR DESCRIPTION
**Pull request by Ahussein04**
## Describe your project in 1-3 sentences
Silent Disco with audio visualizer on headphones and on the walls using RPI to coordinate  programmable led strips. 

## Hack Club Slack handle
@Ahussein04 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by kapaarnav** [comment]
I am his partner,

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: how are you going to control the led light strips on your headphones?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by devramsean0** [comment]
Hey @kapaarnav , can you complete the checklist, like your teammate had done?

**Review by devramsean0 — DISMISSED** [review]
How are you going to control the headphone led strips? I'm guessing something to do with wifi?

**Comment by Ahussein04** [comment]
> How are you going to control the headphone led strips? I'm guessing something to do with wifi?

Yeah we plan on using the ESP32 to wirelessly control the headphones and the rasberry pi to take control of the mounted led's

**Comment by kapaarnav** [comment]
> Hey @kapaarnav , can you complete the checklist, like your teammate has done?

[yes] I am a current high school student (or younger).
[yes] I have submitted an RSVP at https://hackclub.com/winter
[yes] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[yes] I have self-reviewed my project proposal.

**Review by devramsean0 — COMMENTED** [review]
Could you make your plan more detailed?, how sre you going to connect the led strips? Also i noticed you only have 1 esp and 1 led strip for the headphones. But multiple headphones.

**Comment by Ahussein04** [comment]
> 

Hi so we plan on soldering the headers to the esp and connecting the correct wires. We plan on following a guide to do this correctly. Also for the other esp we realized we would be over budget if we included two so we plan on buying another for ourselves. Also the Amazon link we had for the headphones strip comes with two strips so that solves that issue.

**Review by devramsean0 — APPROVED** [review]
Looks good! @hackclub/bankops will follow up in slack

**Review by MelSmith104 — COMMENTED** [review]
hey @Ahussein04 and @kapaarnav! this is such a fun sounding project! i bet it'll be a lot of fun to build too :) im dm'ing you both on slack right now to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
