### PR TITLE
Self Hosted Home Assistant

### PR DESCRIPTION
**Pull request by Dishit79**
## Describe your project in 1-3 sentences

I am building a selfhosted home assistant which can help me with basic tasks like turning lights off/on, opening my garage door, setting timers and more.  This project is made to be configurable and more commands can be added over time. 

## Hack Club Slack handle

Dishit79

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: what's the reason for picking a tablet over a pi w/ speakers and mic set up?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by Dishit79** [comment]
Right so I picked a tablet over a Pi because of the insane price surges on the raspberry pi currently. A raspberry pi costs upwards of 200 dollars not including all the other accessories needed to get it off the ground. Furthermore I am also interested in app development so this purchase provide more versatility in the future as oppose to a Linux machine like the pi.

**Comment by devramsean0** [comment]
This seems like more of a software project than a hardware project. also a RPI zero 2 W would probably be just as capable compared to a tablet (and cheaper probably) and if you had to assemble the screen / power button /mic setup yourself it would become more of a hardware project.

**Comment by Dishit79** [comment]
Alright I'll make some changes to include more hardware involvement

**Comment by bellesea** [comment]
hey @Dishit79 i'm wondering, are you still interested in moving forward with this PR? if so, can you please try and update your PR by this Friday or latest this weekend? If not, we might not have enough time to move forward with the grant and allow you to get your parts in time for the event! thanks :)

**Comment by Dishit79** [comment]
Alright I have updated the pull request.

**Review by devramsean0 — APPROVED** [review]
Looks much better! a member of @hackclub/bank-ops will be in touch

**Review by daisybanks — APPROVED** [review]
Hi @Dishit79! Everything is looking good and we're ready to talk about next steps in getting you your grant! I'm dming you now on Slack. :)

**Pull request merged**
