### PR TITLE
Create srinathn07.md

### PR DESCRIPTION
**Pull request by srinathn07**
## Describe your project in 1-3 sentences

I am creating a plant health system that allows owners of plants to maintain their pots 

## Hack Club Slack handle
Srinath Narayanan

## Checklist before submitting a proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

(note: i'm wondering, are you referencing any sort of guides for your project and can you please format your budget table and ensure it includes shipping + taxes? thank you!)

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by srinathn07** [comment]
Thank you for your feedback, Belle! I have made the necessary changes to the budget format. I've also added the guide to which I'll be referring while creating my project. Thank you, and the team, for providing us high school students with these incredible opportunities to help showcase our talents and knowledge.

**Review by devramsean0 — APPROVED** [review]
Looks good!, thanks for updating your pr to include taxes and shipping. A member of @hackclub/bank-ops will be in touch :)

**Comment by srinathn07** [comment]
Thank you!

**Review by MelSmith104 — COMMENTED** [review]
hey @srinathn07! love your project idea :) honestly this sounds like something i would desperately need since the only plants i can keep are plastic! im dm'ing you on slack right now to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
