### PR TITLE
arsalaan(new).md

### PR DESCRIPTION
**Pull request by Arsalaan-Alam**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by hackliv — APPROVED** [review]

**Review by shanecelis — CHANGES_REQUESTED** [review]
Hi, thank you for the update to this approved project. One small issue: It seems there are two identical files in this pull request. Can you remove the `arsalaan(new).md` before we merge? Thank you.

**Comment by Arsalaan-Alam** [comment]
sure




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
01/18/23,
01:52:12 PM

**Review by bellesea — CHANGES_REQUESTED** [review]
@Arsalaan-Alam can you please elaborate a little more under your plan how you will be using each of these individual parts in your project? thank you!

**Review by shanecelis — APPROVED** [review]

**Review by bellesea — APPROVED** [review]
hey @Arsalaan-Alam this looks great!

approving to move forward but can you please add under plan what you wrote to me in Slack explaining how these extra modules fit your project? thank you :)

**Pull request merged**
