### PR TITLE
Create Abhinav413652.md

### PR DESCRIPTION
**Pull request by Abhinav413652**
## Describe your project in 1-3 sentences
 I am building a Mechanical Keyboard for home and school purposes. 

## Hack Club Slack handle
Joined the Hack Club Slack at https://hackclub.com/slack -
<!--->

## Checklist before submitting proposal:
- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
@Abhinav413652 thank you for taking the time to share this project w/ us :) unfortunately we won't be able to move forward with this project idea as we believe project should be something you spend a significant amount of time on, that you can add something to that makes it your own, and that you can learn from. and as you're buying ready parts and just assembling it, most of the learning spaces of this project is already done for you?

if you're interested in building a mechanical keyboard, perhaps you could look into underlying details of how keyboards work and see if there's a particular part you're interested in that you could work on? B wrote an [awesome post in Slack](https://hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499) about ways to make a mechanical keyboard project :)

please reach me on slack (belle) if you have any questions or would like to have a discussion around this! thank you so much for understanding and we hope to see another project from you!

**Comment by akdd0126** [comment]
Thank you for replying. But can you give me the right link of B's blog on mechanical keyboard because the one you gave me above is not working.

**Comment by bellesea** [comment]
> Thank you for replying. But can you give me the right link of B's blog on mechanical keyboard because the one you gave me above is not working.

hey @Abhinav413652 that's not a blog post, it's a slack post and should lead you to the Hack Club Slack ([hackclub.com/slack](hackclub.com/slack)) which is where everyone involved in this program is hanging out :)

**Comment by akdd0126** [comment]
Ahh... I am getting a glitch or when I click on home I see nothing...

**Comment by bellesea** [comment]
> Ahh... I am getting a glitch or when I click on home I see nothing...

hmm, what's your slack handle (your slack name)? i could DM you there and share the link?

**Comment by akdd0126** [comment]
abhi783922 is my slack username.

**Comment by akdd0126** [comment]
And can I reapply after modification of this project?

**Comment by bellesea** [comment]
@akdd0126 hmm i don't see you your username (abhi783922) in the hack club slack ([hackclub.com/slack](https://hackclub.com/slack))? my username is belle, would you be able to DM me? thank you sm!

and yes 100%, please reapply again!

**Comment by Abhinav413652** [comment]
Hi! I guess my name on slack is Abhinav Singh. I would be glad if you can dm me the right link as it says that you got a glitch.

**Pull request closed without merging**
