### PR TITLE
SATOMASAHIRO2005.md

### PR DESCRIPTION
**Pull request by SatoMasahiro2005**
## Describe your project in 1-3 sentences

Making the MIDI keyboard for playing with non-mainstream scales

## Hack Club Slack handle

佐藤昌浩

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@SatoMasahiro2005 this is such a cool idea!! i'm personally not that musically inclined so i was wondering, what does it mean to make a keyboard with "lots of black keys that are removable"? 

also, is there already an existing midi keyboard that you'll be modelling your keyboard after?

**Comment by SatoMasahiro2005** [comment]
First, Thank you for reading.
I am sorry for my unclear sentence.  

What I would like to do is follow this diagram.


---
I have KOMPLETE KONTROL M32.

**Review by bellesea — APPROVED** [review]
@SatoMasahiro2005 thanks so much for clarifying it! this is super exciting and can't wait to see how this turns out :) @MelSmith104 will be reaching out w/ next steps :)

**Review by MelSmith104 — COMMENTED** [review]
hey @SatoMasahiro2005 ! this is the first musical project i've reviewed so far and it sounds so neat! im dm'ing you on slack right now so that we can go over next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
