### PR TITLE
Gam3rrXD's Project | RGB Smart Mirror with Motion Sensing

### PR DESCRIPTION
**Pull request by Gam3rrXD**
## Hack Club Slack handle
@Gam3rr

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@Gam3rrXD thanks for the proposal! can you please add more details for your plan? eg. what frameworks would you have to download and what you use this for?

**Comment by Gam3rrXD** [comment]
Sure, I would be using the magic mirror framework as the base and adding on supporting modules. I would also be using amazons voice service framework in order to use voice commands with the mirror. This would be used for a better aesthetic and it would be used as a home automation device. Adding to PR!

**Comment by Gam3rrXD** [comment]
@bellesea pull request was updated!

**Comment by Gam3rrXD** [comment]
Hi @MelSmith104 could you please take a look at my proposal when there is time. Thanks!

**Comment by Gam3rrXD** [comment]
Hi @MelSmith104 could you please take a look at my proposal when there is time. Thanks!

**Review by bellesea — APPROVED** [review]
@Gam3rrXD thank you so much for the quick changes! and, it's 100% cool if you reference guides in building this too but love how hacky and personalised it feels :) the incredible @MelSmith104 will be reaching out w/ next steps!

**Review by MelSmith104 — COMMENTED** [review]
hey @Gam3rrXD ! i love the idea to hack on a smart mirror! this looks like such a fun project :) i'm gonna slack with you with next steps so that we can start the process of getting you set up on hack club bank!

**Pull request merged**
