### PR TITLE
Secure Vpn Travel Router Using Raspberry Pie

### PR DESCRIPTION
**Pull request by singhgurmehar**
## Describe your project in 1-3 sentences

In Winter Hardware Wonderland, I plan to build a Secured Wifi Router using Raspberry Pie for travel with its own VPN server for providing an advanced security layer over public Wifi's.

## Hack Club Slack handle

Gurmehar Singh

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@singhgurmehar this is really awesome and so useful! i'm wondering, do you have any plans for expanding on or modifying this project to make it your own?

thank you hehe :)

**Comment by singhgurmehar** [comment]
@bellesea i have mentioned in the readme aswell that after completing it i will try to run an independent dns and vpn server on the same pie which will be used by the pie to stay anonymous and block ads & trackers.

**Comment by bellesea** [comment]
> @bellesea i have mentioned in the readme aswell that after completing it i will try to run an independent dns and vpn server on the same pie which will be used by the pie to stay anonymous and block ads & trackers.

@singhgurmehar that's super awesome! what would running an independent dns and vpn server include? could you please add some details on your plan for this?

**Comment by singhgurmehar** [comment]
@bellesea Done..

**Comment by bellesea** [comment]
> @bellesea Done..

@singhgurmehar thank you so much! unfortunately setting up adguard isn't really a significant modification for making it your own as it doesn't really require any low level knowledge of networking? like what if you set up your own instance of an open source VPN server? https://opensource.com/article/18/6/vpn-alternatives

**Comment by singhgurmehar** [comment]
@bellesea i tried to sum up plan in a short otherwise configuring the router(in cmd ) , installing drivers of wireless adapter, enabling its GUI to connect it further seems tough for me as i am secondary school student of class 6. i had mentioned in the readme file that after successfully completing the above steps i will try to run an independent server on the same pie alongwith a working Router.

Additionally, setting up adguard is like the router running its own DNS server which will be blocking ip requests to Ad's and we can even use that DNS at our Home Router and even in the mobile to block all kind of ads. Configuring Adguard takes hours because DNS server takes some hours for applying the change in config in our DNS

**Comment by bellesea** [comment]
> @bellesea i tried to sum up plan in a short otherwise configuring the router(in cmd ) , installing drivers of wireless adapter, enabling its GUI to connect it further seems tough for me as i am secondary school student of class 6. i had mentioned in the readme file that after successfully completing the above steps i will try to run an independent server on the same pie alongwith a working Router.
> 
> Additionally, setting up adguard is like the router running its own DNS server which will be blocking ip requests to Ad's and we can even use that DNS at our Home Router and even in the mobile to block all kind of ads. Configuring Adguard takes hours because DNS server takes some hours for applying the change in config in our DNS

hey @singhgurmehar thanks for expanding on that! i'm discussing w/ fellow reviewers and will respond asap with whether this is appropriate for the grant :) thank you for your patience!

**Comment by bellesea** [comment]
hey @singhgurmehar unfortunately due to the majority of this project being software based we'd be looking for something that is a little more technically challenging and personalised rather than setting up a ready system with minimal coding experienced. so we won't be able to move forward with the project as is but if you do modify it in a way where you're working on a technically interesting challenge that leads to you understanding low level knowledge of networking or pivot the project in another direction we'd be happy to re-review :) 

i'm going to close this pull request for now, but feel free to open a new one with a revised project proposal, or re-open this one if it's easier. i've also dm-ed you on slack and would be happy to continue chatting there! thank you :)

**Pull request closed without merging**
