### PR TITLE
Create AHussein04.md

### PR DESCRIPTION
**Pull request by Ahussein04**
## Describe your project in 1-3 sentences
Using some code and some audio parts we plan on creating a grand sensory experience. Transforming record player signals to Bluetooth audio and a Audio Visualizer.

## Hack Club Slack handle
@AHUSSEIN04

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by kapaarnav** [comment]
Hello, I am Aarnav Kapoor and I am his partner.

**Comment by bellesea** [comment]
Hii @Ahussein04 and @kapaarnav this is super super cool but unfortunately doesn't quite fit the goals of this event.

The goal of Winter Hardware Wonderland is to make hardware hacking (creatively building things using the details of how electronics work) available to more people, and plugging together a series of consumer products doesn't really count.

I'm going to close this pull request for now, but feel free to open a new one with a revised project proposal, or re-open this one if it's easier.

Let me know if you have any questions, you could reply in this thread or reach out via slack (i'm belle). thank you!

**Comment by Ahussein04** [comment]
Hi if we were to make the audio visualizer using a raspberry pi and outputting it to an led strip or led panel would that fit the goals of the event?

**Comment by bellesea** [comment]
> Hi if we were to make the audio visualizer using a raspberry pi and outputting it to an led strip or led panel would that fit the goals of the event?

yeah! that part would definitely fit the goals but we wouldn't approve it if the majority of the budget went towards a non-essential part of that project if that makes sense? an audio visualizer is super cool though :)

**Comment by Ahussein04** [comment]
Since the new idea is to have a silent disco incorporating a audio visualizer would it make sense to remove all the items that involve the record player and keep the headphones.

**Comment by bellesea** [comment]
> Since the new idea is to have a silent disco incorporating a audio visualizer would it make sense to remove all the items that involve the record player and keep the headphones.

oooo interesting, can you please elaborate more on this idea? what are you going to spend your time building and what are the major parts you'd purchase + what role it plays in the project?

**Comment by Ahussein04** [comment]
Ok so we wanted to have silent disco parties in my partners basement so we can listen to music together and relax. We have been seeing a lot about raspberry pi's being used to sync with led light strips and capture noise frequencies to create the visualizer. We plan on using large pieces of wood and attaching the led strips and writing a program to function as the visualizer.

**Comment by bellesea** [comment]
@Ahussein04 how would the rpi capture noise frequency if the music will be played directly to your headphones?

**Comment by Ahussein04** [comment]
I was watching some videos and they said that it could take them in from the device where the sound is coming from.

**Comment by bellesea** [comment]
> I was watching some videos and they said that it could take them in from the device where the sound is coming from.

@Ahussein04 cool! tbh i don't think we'd approve the headphones because eventhough your intention is a silent disco party, your project really is an audio visualizer and it's possible to do that without having headphones... unless you're modding your headphones in anyway that's essential to this project. if you're interested in moving forward, please make a new PR (or re-open this one) with the new plan elaborating on how it would work (including linking the sources you're referencing) by Jan 15 at 11:59pm ET :)

thank you!

**Comment by Ahussein04** [comment]
Hi I forgot to include the fact we wanted to put some of the led strips on the headphones so to really create the disco experience.

**Comment by bellesea** [comment]
@Ahussein04 sure that would be a great modification! if the led strips on your headphones were also synced with the visualisation, we'd probably approve the headphones hehe :) looking forward to your PR!

**Comment by Ahussein04** [comment]
Hi we just sent out a new pull request with the new plan if you are able to look at it.

**Comment by bellesea** [comment]
@Ahussein04 thank you! unfortunately since we'd consider this a new PR we'll have to review the backlog of PRs first :( don't worry though since you submitted the new PR before Jan 15, we'll definitely review it! thank you :)

**Pull request closed without merging**
