### PR TITLE
Split-flap display: linkai101

### PR DESCRIPTION
**Pull request by linkai101**
## Describe your project in 1-3 sentences
I'm building a split-flap display inspired from [this](https://www.youtube.com/watch?v=V4WQftf1Qio) project. This display will contain a row of 4-10 flippable characters and can be used to display time or other strings of text.

## Hack Club Slack handle
linkai101

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project it looks super cool hehe!)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by maxwofford — APPROVED** [review]
I've wanted to make one of these for the bank office for the longest time!

This is so cool that you're working on it. What do you want to display? Time?

This project is approved & @hackclub/bank-ops will be in touch shortly!

**Review by hackliv — APPROVED** [review]
LOL @linkai101 I laughed so hard at that video! I'm so excited to see you make this 😃 dming you now on Slack!

**Comment by linkai101** [comment]
Not sure what I wanna display yet, maybe a multi-use display for time, stats, or just any text that I can put up in places. Thank you so much!! — this would be my first hardware project so I'm super excited about the opportunity.

**Pull request merged**
