### PR TITLE
Create kaiz715.md

### PR DESCRIPTION
**Pull request by kaiz715**
## Describe your project in 1-3 sentences

I am planning on building a super accurate and waterproof electronic scale that can read up to 0.01 grams accuracy. I was inspired to do this because my kitchen scale broke from water damage, and I was wondering how electronic scales measured weight. By doing this, I can create a functional scale to replace the broken one I have while expanding my knowledge on electrical engineering and CS, which I plan on majoring in when I go to college.

## Hack Club Slack handle

Kai Zheng

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by Henrik753 — APPROVED** [review]
wow thats really cool actually

**Review by Henrik753 — APPROVED** [review]

**Comment by bellesea** [comment]
heyy @kaiz715  thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering, will you be designing your own 3d enclosure?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by kaiz715** [comment]
I updated to address your question.

**Review by cfanoulis — CHANGES_REQUESTED** [review]
hey, thanks for your proposal :) its very cool that you've decided to take a real life problem and solve it with your own hardware. however, i got some questions for you:

 - I see that the ADC & the load cell need soldering - do you have soldering tools & equipment available? (soldering iron, solder, wick, flux et.c.)
 - How do you plan on waterproofing your device?
 - How do you plan on powering this? I don't see any battery or power cables included
 
Also, please get an accurate amount for tax please :) you can try the checkout process (until your tax amount is displayed) at your retailer & just not click "confirm/send order"

**Comment by kaiz715** [comment]
Hi. 
I can borrow the soldering iron + flux + solder from my dad's workplace. I have soldered components together in the past, so I know how to solder.

The arduino that I have comes with battery pack, but when the arduino is connected to the computer, the computer supplies the power to the arduino. The arduino will then power the breadboard/circuit using its 5v line.

The enclosure that I will design will consist of two parts that I will super glue together to form a watertight seal. No water should be able to leak through the 3d print because the small layer heights of resin printing. see https://www.liqcreate.com/supportarticles/waterproof-airtight-resin-3dprinted-part/

I also updated it with the exact tax amount.

**Review by daisybanks — APPROVED** [review]
Hi @kaiz715! This sounds like a great project and a great way to expand your knowledge! Also an waterproof electronic scale sounds super useful to have in the kitchen for baking and cooking! I'm dming you on Slack now to talk about the next steps in getting you your grant. :)

**Pull request merged**
