### PR TITLE
Create Spycam.md

### PR DESCRIPTION
**Pull request by boyuan12**
## Describe your project in 1-3 sentences

I will add a camera in front of my door that will broadcast to my computer. If someone is within 2 meters, it will send me an SMS alert. 

## Hack Club Slack handle
Boyuan Liu

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by exu3 — APPROVED** [review]
I like how clear and concise your proposal is. The spy camera sounds interesting, and I can't wait to see how it turns out. 

@MelSmith104 will follow up with next steps soon!

**Review by MelSmith104 — COMMENTED** [review]
hey @boyuan12! i love this project! our next step is to schedule an onboarding call and set you up on hack club bank to receive your grant! we'll move communication over to slack :) can you send me your slack ID?

**Comment by boyuan12** [comment]
Sure, my user ID is U01CT5JDQJC and my username is Boyuan Liu

**Comment by MelSmith104** [comment]
hey @boyuan12 just dm'ed you!

**Pull request merged**
