### PR TITLE
Smart mirror with portable computer

### PR DESCRIPTION
**Pull request by DPR-4**
## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by DPR-4** [comment]
---
name: "@DPR-4"
project: "Smart mirror with portable computer"
---

# Smart mirror with portable computer

## Summary

Going to build smart mirror which can be use in free time for computer. It help to make things easier and enter in future era.
smart mirror will also help to detect stress level 


## Plan

What steps are you going to take to build it? What tools are you going to use? What will you do first, second, third, etc.?
first we need TV monitor 
second Raspberry Pi 3 Model B 2GB computer.
third we need frames 
forth two way mirror
fifth cables and micro sd card for os
after asembly of this. We are going to install smart mirror software in raspberry pi (https://magicmirror.builders/) this is link and documentation.
and also add stress detction software 


## Budget

| Product             | Supplier/Link                         | Cost   |
| ---------------     | ------------------------------------- | ------ |
| Raspberry Pi 3      | https://amzn.eu/d/3xqghZG             | $132.76|
| 32 inch"LED display | https://amzn.eu/d/fgnFrpA             | $138.86|
| Acrylic Mirror      | https://amzn.eu/d/b9tiNru             | $108.89|
| Total               |                                       | $380.51|

## cost optimized 
| Product             | Supplier/Link                         | Cost   |
| ---------------     | ------------------------------------- | ------ |
| Raspberry Pi 3      | https://amzn.eu/d/3xqghZG             | $132.76|
| 32 inch"LED display | https://amzn.eu/d/5z8p9DQ             | $96.60 |
| Acrylic Mirror      | i will buy by my money                | $0     |
| HDMI                | own                                   | $0     |
| speaker             | own                                   | $0     |
| mouse and keyboard  | own                                   | $0     |
| Micro SD Card       | own                                   | $0     |
| Total               |                                       | $229.36|

**Comment by bellesea** [comment]
hey @DPR-4 thanks for sharing this idea!! i noticed you didn't check that you were a "high schooler or younger" and that is a requirement to be eligible for this grant and event. hence, we won't be able to move forward with this project and will be closing this PR. 

please let us know if this was a mistake and we appreciate the effort and time you put into sharing the project idea!

**Comment by DPR-4** [comment]
This was by mistake I make sure to check all box

**Comment by DPR-4** [comment]
Hey Bella
Even after getting grant I am not able to spend that money in India to
build my dream project that's how it works
Unfortunately 😭 it's all about fate may be

**Comment by bellesea** [comment]
> 

@DPR-4 ahh cool! right now we're not super sure if you'll be able to spend the money in India but we are working hard to find a work around. could you please email us at bank@hackclub.com with your proof of being in high school (or younger)?

**Pull request closed without merging**
