### PR TITLE
Multi-Function Electronic Control/Steering Device

### PR DESCRIPTION
**Pull request by MostlyWhat**
## Describe your project in 1-3 sentences

I will be building a multi-function steering wheel/flight yoke combination.

## Hack Club Slack handle

@Mostly

## Checklist before submitting proposal:

- [Y] I am a current high school student (or younger).
- [Y] I have submitted an RSVP at <https://hackclub.com/winter>
- [Y] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [Y] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hii @MostlyWhat this is soo cool! i'm wondering, do you plan on purchasing a wheel/yoke type thing to mount your arduino? also, what type of input data do you need in order for you this to work? 

also, could you please include taxes and shipping within your budget?

thanks sm!

**Comment by MostlyWhat** [comment]
No, I will be building the entire system from scratch without a base. This includes the steering wheel thing, but also the yoke sensors. The input data for buttons will be digital and will be sent to the Arduino Mega that I own at home, because I will be needing a lot of ports. But for the steering and angles, then I will be using a potentiometer connecting to the analog port.

**Comment by MostlyWhat** [comment]
I will be connecting the Arduino to the Raspberry Pi, then use this https://github.com/milador/RaspberryPi-Joystick to turn it into a joystick.

**Comment by MostlyWhat** [comment]
Shipping the Raspberry Pi might be a bit slow but I can compensate by converting the arduino to a gamepad for now. But it will lack the wireless-ness that I was looking for. I've now also added the total shipping costs.

**Comment by bellesea** [comment]
@MostlyWhat thank you so much for this additional context, could you please include it under ##plan in your markdown file? and to check, you already have access to all of the additional items you mentioned? if so, could you please add it under your budget too but just state that it's $0 because you already own it :)

this is super exciting, thank you!!

**Comment by MostlyWhat** [comment]
Working on it right now.

**Review by MostlyWhat — COMMENTED** [review]
Final Edit has been completed now waiting for approval.

**Review by bellesea — APPROVED** [review]
@MostlyWhat thanks for pushing the changes!

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps :)

can't wait to see this project come to life :)

**Review by MelSmith104 — COMMENTED** [review]
hey @MostlyWhat ! i love your project idea! this sounds like a lot of fun and i really love how it ties back to you wanting to fly a plane! i've also always wanted to fly - i feel like it has to be one of the most exhilarating feelings in the world! i'm dm'ing you on slack right now so that we can chat about next steps :)

**Review by MelSmith104 — APPROVED** [review]

**Comment by Cohen-Koen** [comment]
This is a great idea, it gets very close to what I am doing with software hacking and dual screen emulation for my integrated MFD for flight sims and development!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
