### PR TITLE
🌈 🪩 ✨ Gramophone-502x!

### PR DESCRIPTION
**Pull request by sampoder**
## Describe your project in 1-3 sentences

> A phonograph, in its later forms also called a gramophone (as a trademark since 1887, as a generic name in the UK since 1910) or since the 1940s called a record player, or more recently a turntable, is a device for the mechanical and analogue recording and reproduction of sound. [Wikipedia]

Playing music just ain't as fun anymore. _**HEY SIRI**_ is no where near as cool as spinning a physical record. Team 502, here. We're going to create a modern version of the Gramophone called the "Gramophone-502x".

## Hack Club Slack handle

`@sampoder`, `@Arsh Shrivastava`, `@neil`

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by maxwofford — APPROVED** [review]
> A phonograph, in its later forms also called a gramophone...

_TIL_

This is amazing. I'm totally fine the Assorted Circuit Components as long as all receipts are uploaded! I can't wait to see this once it's done.

**Comment by hackliv** [comment]
Hey @sampoder love the emojis sm!! 😃🌈 Would Arsh and Neil also be able to comment on here verifying the checklist? ty!

**Comment by sampoder** [comment]
Last I heard they'd both lost access to their GitHub accounts! But... I will attempt to summon them.

**Comment by arshshrivastavaa** [comment]
Hello There 👋

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by sampoder** [comment]
It seems that @neiltheghosh has lost access to his GitHub account.... on his behalf:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by neiltheghosh** [comment]
- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by hackliv** [comment]
awesome, thanks for verifying @neiltheghosh & @arshshrivastavaa! I'm dming you all now on Slack to chat about next steps for the grant. 😃

**Review by hackliv — APPROVED** [review]

**Pull request merged**
