### PR TITLE
Home-Environment-Monitor (HEV) - Update

### PR DESCRIPTION
**Pull request by thomaswcy**
Documentation Update of https://github.com/hackclub/winter/pull/285
I've refunded the Redmi 27'' display because it is too big and there's no space on my desk.
I've changed it into Redmi 23.8'' rotatable display because it is smaller and could be converted into a portrait display.
The price is $107.05 including all fees and taxes and shipping
(Sorry for last time - didn't calculate the transaction fee)

### CODE REVIEW

**Comment by thomaswcy** [comment]
@maxwofford @daisybanks

**Comment by sanjay-nagesh** [comment]
Sorry, That was by mistake!

Anyways, Can you please all the other parts of the file (plan, summary etc)

**Comment by thomaswcy** [comment]
All the details are at #285 and in thomaswcy.md

**Comment by maxwofford** [comment]
Switching review assignment because I reviewed #285!

**Comment by maxwofford** [comment]
The additional name I added in [747681b](https://github.com/hackclub/winter/pull/433/commits/747681ba1499e239df8ce2d1cf6331644ef3a795) isn't changing the budget limit– it was approved in https://github.com/hackclub/winter/pull/285 but missing from the markdown.

**Review by maxwofford — APPROVED** [review]

**Comment by maxwofford** [comment]
Tagging @daisybanks & @hackclub/bank-ops to loop them in on this approved budget change.

**Review by daisybanks — APPROVED** [review]
Thanks for approving the new budget! I'll get that sent over ASAP. :)

**Pull request merged**
