### PR TITLE
Vr glove

### PR DESCRIPTION
**Pull request by covertimpala**
## Describe your project in 1-3 sentences

I am building a glove which allows the user to use their hand in VR and to feel things in VR

## Hack Club Slack handle

Joined

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hiii @covertimpala this is sooo cool! 

just to check, do you already have access to a 3d printer and can print the parts? also, you mentioned that it'll track motion using an accelerometer, magnetometer, and gyro... do you already have all of these?

could you please convert the total cost to USD? this will help with disbursement of the grant, thank you sm!

**Comment by covertimpala** [comment]
Hi, I do have a 3D printer capable of printing the parts and the nRF52840 Sense has an accelerometer, magnetometer and gyroscope. :) 
btw i have now changed the currency to USD

**Review by bellesea — APPROVED** [review]
@covertimpala thanks for the clarification! a fabulous member of @hackclub/bank-ops will be reaching out with nexts steps shortly :)

**Review by hackliv — APPROVED** [review]
looks awesome @covertimpala ! dming you on Slack now about getting set up on Hack Club Bank 🤩

**Pull request merged**
