### PR TITLE
DroneCar Idea

### PR DESCRIPTION
**Pull request by wehaveagod**
I am building a DroneCar powered by Raspberry Pi and Arduino.

### CODE REVIEW

**Comment by bellesea** [comment]
Hey @wehaveagod, thanks for submitting the project proposal. Unfortunately this was submitted after the extended deadline on Jan 15th, so we can't move forward with the grant. That said, you're welcome to participate in the [slack](https://hackclub.com/slack) and join in for the 10 day project building in public. Thank you for understanding!

**Comment by wehaveagod** [comment]
I believe there is a misunderstanding. On January 9th, you sent the email that the due date for submitting the project idea was one week after, which meant Monday, January 16th. It was never mentioned that the project idea was due on Sunday, January 15th. I submitted my idea on January 16th, which was the mentioned due date. Can you please look into this for me?

**Comment by bellesea** [comment]
> I believe there is a misunderstanding. On January 9th, you sent the email that the due date for submitting the project idea was one week after, which meant Monday, January 16th. It was never mentioned that the project idea was due on Sunday, January 15th. I submitted my idea on January 16th, which was the mentioned due date. Can you please look into this for me?

hey @wehaveagod ahh i hear that. with that we meant one week as in till the end of the week, I apologise for confusion with the wording. 

however, in the email we did include that "all pull requests made by January 15th 11:59 pm ET will be reviewed by the Hack Club Bank team." this deadline was later extended by 3 hours to 11:59pm PT and announced in #hardware-party in our slack.

so unfortunately your project submission is late and we won't be able to move forward :(

**Comment by wehaveagod** [comment]
That is unfair, but I understand.

**Comment by wehaveagod** [comment]
Is there any way I can be forgiven for this late submission? I only missed
it by a few hours.

**Comment by wehaveagod** [comment]
I spent a lot of time trying to figure what parts I need.

**Pull request closed without merging**
