### PR TITLE
Create abhisinghh501.md

### PR DESCRIPTION
**Pull request by abhisinghh501**
## Describe your project in 1-3 sentences
Smart mirror and a Temperature and humidity logger

## Hack Club Slack handle
Abhi Singh

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by mahajanasim2** [comment]
# Describe your project in 1-3 sentences
Smart mirror and a DIY multifunction device

# Hack Club Slack handle
Asim Mahajan

# Checklist before submitting proposal:
[yes] I am a current high school student (or younger).
[yes] I have submitted an RSVP at https://hackclub.com/winter
[yes] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[yes] I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
heyy @abhisinghh501 and @mahajanasim2 thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering if it'd be better to recreate your own open-source version of a flipper zero than modifying a ready consumer product...)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by abhisinghh501** [comment]
Hi @bellesea our project is actually taking inspiration off another project
that got approved hackclub/winter/MangoTornado.md

its pretty much impossible to make yoyr own flipper zero. Not taking into
account the extra hardware costs, the skill needed to make something like
that urself is off the charts

and we're not build a keyboard lol

**Comment by abhisinghh501** [comment]
@bellesea

**Comment by abhisinghh501** [comment]
and we're not copying them lol. We're only taking inspiration and building upon what they're doing. Our plan is more detailed and has extra steps for the relevant places

**Comment by bellesea** [comment]
> and we're not copying them lol. We're only taking inspiration and building upon what they're doing. Our plan is more detailed and has extra steps for the relevant places

@abhisinghh501 thanks for mentioning this! we'll review your PR within the next day or so :) thanks for your patience!

**Comment by abhisinghh501** [comment]
No worries, thanks for the update!

**Comment by abhisinghh501** [comment]
suggestion: maybe you could swap your flipper zero with a raspberry pi & host a logging server for temp and humidity then add an rfid reader etc. and make your own version of a flipper?

Yeah i was thinking of doing something similar given the flipper is out of stock everywhere too. Ill change my pr right away

you mentioned using magic mirror & smartmirror :) will you be writing your own modules or using existing ones?
Existing software, we could try our own too if we have time.
the fan that you linked looks like a super big and potentially loud one? would a passive cooling fan work better?
I'll look into this too right now

**Comment by abhisinghh501** [comment]
@bellesea

**Review by bellesea — CHANGES_REQUESTED** [review]
@abhisinghh501 thank you so much for pushing the changes!

a few small things:
- for the mirror we'd highly encourage you to write your own software or modify it in someway to make it your own so it's not really plugging together ready hardware & software parts :)
- with the temp & humidity logger, that was just a suggestion hehe but if you're actually interested in it we can definitely move forward with this! or you could look into building a specific part of the flipper zero eg. https://learn.adafruit.com/building-an-infrared-transmitter-and-receiver-board?view=all

please let me know how you'd like to move forward :) thank you!

**Comment by abhisinghh501** [comment]
for the mirror we'd highly encourage you to write your own software or
modify it in someway to make it your own so it's not really plugging
together ready hardware & software parts :)

yeahw we could definitely try this. We'll keep the magic mirror os as a
last resort in case we cant figure anything out.


with the temp & humidity logger, that was just a suggestion hehe but if
you're actually interested in it we can definitely move forward with this!
or you could look into building a specific part of the flipper zero

we would like to go forward with the temperature and humidity sensor simple
because its easier and we're complete beginners

**Review by bellesea — APPROVED** [review]
@abhisinghh501 sounds good!

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps :)

approving to move forward but can you please do some research on how you'd write your own code for the smart mirror and commit into your file under plan? thank you!

**Review by MelSmith104 — COMMENTED** [review]
hey @abhisinghh501 and @mahajanasim2! i love the idea of building a smart mirror :) having one seems like it would be so useful :) im dm'ing you both right now on slack to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
