### PR TITLE
create andy-phung.md!

### PR DESCRIPTION
**Pull request by andy-phung**
## Describe your project in 1-3 sentences
I'll be building three mini-projects: a pair of DIY AirPods, a desktop [Killjoy turret](https://media.tenor.com/ivAUHBeshMsAAAAC/valorant-killjoy.gif) that shoots Nerf bullets, and a ramen bowl lamp with glowing noodles!

## Hack Club Slack handle
andyp

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@andy-phung this looks really awesome and super fun!!

it looks like the tinys3 would be larger than the airpods, do you plan on attaching it on the side of the airpod / will you be making a case for it? also, are you referencing a guide/project for any of these 3 projects?

hacky new years!

**Comment by andy-phung** [comment]
hey! so the tinys3s would just be wired directly to the earpods' speakers on the sides of each earpod; and since the tinys3s are already slightly wider, i thought it'd look best without a casing

and i should be able to do all three of these projects without referencing any guides👍

hacky new years!!

**Comment by bellesea** [comment]
> hey! so the tinys3s would just be wired directly to the earpods' speakers on the sides of each earpod; and since the tinys3s are already slightly wider, i thought it'd look best without a casing
> 
> and i should be able to do all three of these projects without referencing any guides👍
> 
> hacky new years!!

@andy-phung thank you so much for pushing the changes! i've never experimented with bluetooth audio before... i'm wondering how do you plan on wiring the tinys3s to the earpods and how do you know it'll play? super appreciate you taking the time to explain :)

**Comment by andy-phung** [comment]
@bellesea no problem! so when a tinys3 decodes an a2dp packet (because audio data has to first be encoded into a smaller and more manageable format before being transmitted), it'll output to a pwm-capable gpio pin connected to its earbud's speaker input wire --- the pwm signal this pin outputs effectively simulates the analog signal required to drive the speaker; and the speaker's other wire (ground) would just be connected to the s3's ground pin

i haven't decided on the specifics yet (sampling rate, etc), but i know that a tinys3 can definitely supply enough current at a high enough voltage to play audio at a reasonable volume, assuming apple's earpods have something close to the typical 8 ohm speakers you'd expect to find in earbuds

let me know if you need any additional clarification!

**Review by bellesea — APPROVED** [review]
@andy-phung can't wait to see you work on this :)))

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by MelSmith104 — COMMENTED** [review]
hey @andy-phung! love the projects you're planning on building! especially the ramen bowl one - it sounds so cool! dm'ing you on slack right now to chat through next steps!

**Comment by MelSmith104** [comment]
hey @andy-phung im not able to find you on Slack - could you send me your Slack id?

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
