### PR TITLE
Weather Lamp

### PR DESCRIPTION
**Pull request by esjiko**
## Describe your project in 1-3 sentences
I am building an RGB weather lamp that has a switch and changes color depending on the current temperature range and sun/moon by using the openweathermap.org API. 

## Hack Club Slack handle
zuzu

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project since you only used a small portion of the project what do you think about expanding on it by maybe adding a screen or smth? completely optional haha)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — APPROVED** [review]
Love the project idea! I was wondering if you had ideas about how you could extend the project beyond the guide?

**Review by daisybanks — APPROVED** [review]
@esjiko - I love this project idea and agree it would so cute and easy to roll over in bed and look at your lamp's color to instantly know what the weather/temp is. I'm dming you now on Slack to talk about next steps in getting you your grant. :)

**Comment by esjiko** [comment]
>

**Comment by esjiko** [comment]
> 

Hi! Yeah, these past few days I've been talking with someone on slack on how I could add a switch to my lamp and I understand how it works but I'm still having trouble with what materials I would need to get, like the different jumper wires. Before I meet with Daisy should I edit my PR?

**Comment by bellesea** [comment]
hey @esjiko yes if possible, please edit your PR before you meet with daisy so we can have the updated budget hehe :)

on adding a switch, i think i might have been the one chatting to you hehe! take a look at this: https://www.youtube.com/watch?v=xDDYHzrV1QM

if you need any further help with this feel free to DM me! also, re-opening this PR so that daisy can merge it later on :)

**Pull request merged**
