### PR TITLE
Vitalii Kuzhdin - E-Book for Blind

### PR DESCRIPTION
**Pull request by vitaliikuzhdin**
## Describe your project in 1-3 sentences

I am building an e-book for blind

## Hack Club Slack handle

@vitaliikuzhdin 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by cfanoulis — COMMENTED** [review]
hi! this is very intriguing, i must say.

will you be following a guide? if so, please provide some links for us to see :)

**Comment by vitaliikuzhdin** [comment]
Hello!

I don't have any guides on how to comlpete the whole project, but I do have a few notes on how to set up certain parts of it. Either way, I have quite some experience I obtained from Summer of Hacking 2020 so it won't be a problem.

https://www.youtube.com/watch?v=nwVRMU9grSI
https://learn.adafruit.com/adafruit-pcf8575/overview
https://randomnerdtutorials.com/guide-to-sd-card-module-with-arduino/
https://roboticsbackend.com/arduino-push-button-tutorial/

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Great, thanks for that. Some few things:

- How will you contain all of this? Do you have a casing already or are you making one?
- Have you accounted for taxes & shipping?

**Comment by vitaliikuzhdin** [comment]
1. I have materials to make the casing
2. Yes

**Comment by cfanoulis** [comment]
Amazing! Please include the items you'll be using for the casing in your budget table (with a price of 0$) and we should be done!

**Comment by vitaliikuzhdin** [comment]
> Amazing! Please include the items you'll be using for the casing in your budget table (with a price of 0$) and we should be done!

Done, thank you!

**Review by cfanoulis — APPROVED** [review]
And with merely a click, I declare thee a grantee! A banker from @hackclub/bank-ops will reach out to get your grant setup - congrats!

**Review by MelSmith104 — COMMENTED** [review]
hey @vitaliikuzhdin this project is fascinating! i love the idea and am so excited to see you build this! im dm'ing you on slack right now to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
