### PR TITLE
added 05him.md

### PR DESCRIPTION
**Pull request by 05him**
## Describe your project in 1-3 sentences

I am building a arduino based car which will be controlled by drone transmittor

## Hack Club Slack handle

HiManshu

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: are you referencing any guides of sorts? i believe you mentioned searching on youtube? also, does your budget include shipping & taxes?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by alhardwarehyde — APPROVED** [review]
This is a really cool project! Can you link the YouTube video you referenced in your summary? or any other guides, resources, etc that you're looking at for this? 

Also we verify all the information for the checkboxes, can you edit your comment to add an X or other marking to clarify that you've signed off on everything?

@hackclub/bank-ops

**Review by daisybanks — APPROVED** [review]
Hi @05him! Thanks for completing the check list! I'm going to resume our conversation on Slack so we can continue talking about next steps for getting you your grant! :)

**Comment by cfanoulis** [comment]
hey @05him, congrats on the grant :) We've been trying to reach you for your ~car's extended warranty~ bank onboarding call - the next step to bring you close to your grant. However, your banker, Daisy, has been having difficulty reaching you to schedule a call. Can you please check Slack & reply to their DM?

a bank onboarding call is crucial for the grant process, as this is where you'll be seeing Hack Club Bank for the first time (unless you have a demo account!). Also, you'll go through the Fiscal Sponsorship contract - a legal document officially getting you on da hack bank

Please make sure to schedule a meeting within the next 2 days (that is, until Jan 26th) - else, your grant will be forfeited! (and nobody wants that). If you're having trouble, please get in touch with either me or your banker via Slack.

Toodaloo!

**Pull request closed without merging**
