### PR TITLE
Create Gregor-Davies.md

### PR DESCRIPTION
**Pull request by Gregor-Davies**
## Describe your project in 1-3 sentences

I am building a Greenpower Racing Go kart sensor telemetry system.
## Hack Club Slack handle

Gregor Davies

## Checklist before submitting proposal:

- [✔] I am a current high school student (or younger).
- [ ✔] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ✔] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✔ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@Gregor-Davies thank you for sharing this, it looks super cool! just to check, do you already have access to an arduino, wire crimper, and soldering station? also, how do you plan on interfacing with the data that you collect?

btw, could you please amend your budget w/ estimated budget and shipping?

thank you so much!

**Comment by Gregor-Davies** [comment]
Hello, Thanks for the reply. Yes I have access to those tools either at home or through my school/local clubs, I've included the shipping now. 

Thank you.

**Comment by bellesea** [comment]
> Hello, Thanks for the reply. Yes I have access to those tools either at home or through my school/local clubs, I've included the shipping now.
> 
> Thank you.

thank you so much!

**Review by bellesea — APPROVED** [review]
thank you @Gregor-Davies for this, it's super cool and can't wait to see this being built :) and absolutely love that it'll be open-sourced!

a fabulous member of @hackclub/bank-ops will be reaching out w/ next steps soon!

**Review by hackliv — APPROVED** [review]
Hey @Gregor-Davies this sounds super cool! I am a huge fan of this idea because I'm a bit obsessed with Mario Kart on my switch rn. Dming you on Slack now about next steps! 😃

**Pull request merged**
