### PR TITLE
Agriculture Drone

### PR DESCRIPTION
**Pull request by TKuijvenhoven**
## Checklist before submitting proposal:

- [ x ] I am a current high school student (or younger).
- [ x ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ x ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ x ] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@TKuijvenhoven thanks for sharing this! this is sooo cool! would you be willing to elaborate on your plan? like how do you plan on connecting your drone and your watering kit? and, how do you plan on using this drone?

thanks!

**Comment by bellesea** [comment]
> @TKuijvenhoven thanks for sharing this! this is sooo cool! would you be willing to elaborate on your plan? like how do you plan on connecting your drone and your watering kit? and, how do you plan on using this drone?
> 
> thanks!

hiii @TKuijvenhoven hope you're doing awesome! checking in to see if you're still interested in moving forward on this project?

**Comment by cfanoulis** [comment]
Hi @TKuijvenhoven! Thanks for your proposal. It's been a week since Belle's message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Hacky New Year!

**Comment by cfanoulis** [comment]
Hello! Unfortunately 2 days have passed, which means that I'll be closing this PR as stale. If you still wish to pursue a grant please let us know by replying to this PR before Jan. 15th

**Pull request closed without merging**
