### PR TITLE
Update Project Proposal For IoT Plant Watering System

### PR DESCRIPTION
**Pull request by Verisimilitude11**
This is an update to my earlier PR that adds the ability to power the IoT Plant Watering System via solar energy. I have already received $160 from Bank and the total price of this update is still less than $250.

I'm thinking of powering my IoT Plant Watering System via solar energy! This will be beneficial because I won't have to replace the batteries or have them continuously connected to a plug point which will allow me to use it outdoors (it'll also be better for the environment as a side bonus!)

I'm planning on using this guide: https://footprinthero.com/how-to-solar-power-an-arduino#:~:text=Let%E2%80%99s%20get%20started.-,1.%2[…]20Power%20Manager%205V,-This%20little%20board.

## New parts:

- LCD display to display power input and sensor data: https://www.amazon.com/gp/product/B08MPTND1V/ref=ox_sc_act_title_1?smid=A1JX4L5CBS4J9K&psc=1
- Battery with JST connector to store solar energy: https://www.amazon.com/gp/product/B08214DJLJ/ref=ox_sc_act_title_3?smid=A3JZ0E8P9D7DI&psc=1
- Solar panel + power manager: https://www.dfrobot.com/product-2000.html

Shipping: $21.00
Subtotal: $24.40 + $15.99 + $15.12 = $55.51
Taxes: $7.74
**Total added price: $84.26**

Would it be possible for you to add this to my bank: https://bank.hackclub.com/iot-plant-watering-system. My total cost from this shipment and the previous is still less than $250. Thanks!!

### CODE REVIEW

**Review by cfanoulis — CHANGES_REQUESTED** [review]
hey! that's so cool you want to power your device by solar! can you add your new parts to your budget table & update your total there? thaanks

**Comment by Verisimilitude11** [comment]
done @cfanoulis!

**Review by cfanoulis — APPROVED** [review]
perfect! lets get u your $$$! someone from @hackclub/bank-ops will reach out shortly - keep ur eyes peeled!

**Comment by Verisimilitude11** [comment]
thanks, will do!! 😀

**Review by MelSmith104 — APPROVED** [review]

**Comment by Verisimilitude11** [comment]
hi @MelSmith104, when can I expect to receive the updated grant?

**Comment by hackliv** [comment]
> hi @MelSmith104, when can I expect to receive the updated grant?

hey @Verisimilitude11, Mel's out of office so I was just able to send you the extra funds! Feel free to dm me @ liv on Slack if you need help with anything!

**Comment by Verisimilitude11** [comment]
thanks @hackliv!!

**Pull request merged**
