### PR TITLE
Mechanical Keyboard

### PR DESCRIPTION
**Pull request by InternetRamen**
## Describe your project in 1-3 sentences
I am building a mechanical keyboard.
## Hack Club Slack handle
Jaden

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
hii @InternetRamen thanks for making this PR, please give us another day to fully flesh out our policies on projects and we'll respond asap! thank you for understanding :)

**Review by bellesea — CHANGES_REQUESTED** [review]
heyyy @InternetRamen thank you for taking the time to share this project w/ us :) after discussions about what we're looking for in a project for this event/grant, unfortunately your PR does not **currently** qualify. we believe project should be something you spend a significant amount of time on, that you can add something to that makes it your own, and that you can learn from.

although i appreciate how much research that went into learning about keyboards, we're looking for something that has a little bit more making involved... it probably hits the third point, i'm not super sure if it fits the first and second?

perhaps you could add one more element of "you" to this? something that might add one layer of complexity to the project... [B's post has some resources](https://hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499) that might be useful!

because i feel like this project is super close to being something that would qualify, i'll keep the PR open for now but please let me know if you plan on making changes or would rather work on a different project :)

thank you so much for understanding!

**Comment by InternetRamen** [comment]
Sounds good, I'll see what I can do when I get back. Feel free to close the PR if it makes the project more organized!

**Comment by bellesea** [comment]
> Sounds good, I'll see what I can do when I get back. Feel free to close the PR if it makes the project more organized!

great, thank you so much! hacky holidays :)

**Pull request closed without merging**
