### PR TITLE
Create shojha24.md

### PR DESCRIPTION
**Pull request by shojha24**
## Describe your project in 1-3 sentences

I am building a modular lightsaber containing a string of LED lights that reflects onto retro-reflective tape, producing a practical "glow" effect that (quite literally) outshines lightsabers currently on the market.

## Hack Club Slack handle

@shojha24 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by svojha2029** [comment]
Hi, I'm working on this project with my brother.

**Comment by shojha24** [comment]
I added shipping and tax into the total price. Thank you for your consideration!

**Comment by bellesea** [comment]
great, thank you! we've started reviewing PRs in the order that they came in but since we had a huge influx last weekend, it might be a while before we review your PR :) thank you for your patience!

**Review by daisybanks — APPROVED** [review]
Hi @shojha24 - this sounds really fun and awesome! I have many friends who would LOVE to get their hands on this haha. I'm dming you now on Slack to talk about next steps in getting you on Bank and getting you your grant. :)

**Comment by maxwofford** [comment]
@shojha24 could you have your other member post the checklist and slack username to confirm?

**Comment by svojha2029** [comment]
https://github.com/hackclub/winter/pull/387 this is my checklist, my slack username is @svojha29

**Pull request merged**
