### PR TITLE
Electric Skateboard

### PR DESCRIPTION
**Pull request by ivoinestrachan**
## Describe your project in 1-3 sentences

The skateboard safety alert system is a device that uses sensors to detect potential collisions and sounds an alarm to alert the skateboarder. It includes a microcontroller, sensors, and an audio output device and requires code to be written to process sensor data and play the alarm sound. The system aims to improve skateboard safety by alerting skateboarders to potential collisions and helping them avoid accidents.

## Hack Club Slack handle
sike(thinking)

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hiii @ivoinestrachan thank you so much for sharing this, it looks awesome!! i'm wondering, what sensors are you planning do use to detect potential collision? and, do you need a speaker of sort? 

also, could you please recommit the exu3.md file?

thank you sm!

**Comment by ivoinestrachan** [comment]
sup So I'm using the sensor that comes with the Arduino set and I wouldn't need a speaker there's something in the ardunio set that goes off when it comes close to something. I'll recommit ella file

**Comment by bellesea** [comment]
> sup So I'm using the sensor that comes with the Arduino set and I wouldn't need a speaker there's something in the ardunio set that goes off when it comes close to something. I'll recommit ella file

sup :) ahhh awesome!!

**Review by bellesea — APPROVED** [review]
@ivoinestrachan can't wait to see you work on this!! a fabulous member of the @hackclub/bank-ops team will reach out soon w/ next steps :)

**Comment by hackliv** [comment]
@ivoinestrachan !!! this sounds so awesome. Feel free to dm me on Slack, and we can coordinate the contract and getting set up on Bank. :)

**Review by hackliv — APPROVED** [review]

**Pull request merged**
