### PR TITLE
Update on Bonus Lector

### PR DESCRIPTION
**Pull request by Arpan-206**
Had to upgrade the 3D Printer as the one I linked turns out to be incompatible for this project.

Also, added a new team member to factor in for the upgrade in budget. Will ask him to send the checklist here.

Cc: @hackliv @cfanoulis

### CODE REVIEW

**Comment by Arpan-206** [comment]
Team members: @dhruvchaudhry @simranpundirr @srishti-pandey-14 @Arpan-206

**Comment by cfanoulis** [comment]
Hi, please have your new teammate send the checklist asap, thanks

@hackliv do we need a new contract here?

**Comment by hackliv** [comment]
> Hi, please have your new teammate send the checklist asap, thanks
> 
> @hackliv do we need a new contract here?

no worries here about contract! I've been dming with Arpan & Dhruv about this :)

**Review by hackliv — APPROVED** [review]

**Comment by dhruvchaudhry** [comment]
## Describe your project in 1-3 sentences

We are going to build our own eBook Reader (like Kindle) using the Raspberry Pi with a custom OS image, books store etc.

## Hack Club Slack handle

Dhruv S

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by exu3** [comment]
> Had to upgrade the 3D Printer as the one I linked turns out to be incompatible for this project.

@Arpan-206: What about the printer made it incompatible? And what feature of the new printer makes it better fit for your project? I think it would be helpful to know so we can look out for such details in other project proposals involving 3D printers.

**Comment by Sheepy3** [comment]
> > Had to upgrade the 3D Printer as the one I linked turns out to be incompatible for this project.
> 
> @Arpan-206: What about the printer made it incompatible? And what feature of the new printer makes it better fit for your project? I think it would be helpful to know so we can look out for such details in other project proposals involving 3D printers.

Seconded, I think you need to include more information on what you need to get specifically out of this printer. if you're just printing a chassis for your e-reader, I think this Flashforge Adventurer 3 may be a bit overkill. That filament spool may also be incompatible with the Flashforge! 

I also worry you may be overpaying for that E-ink display. I found the [same one](https://www.amazon.in/7-5inch-Two-Color-Interface-Raspberry-Pi/dp/B0BHWTVLQC/ref=sr_1_1?crid=CERBQ8ENS2IO&keywords=7.5inch+e-ink&qid=1674109381&s=computers&sprefix=7.5inch+e-in%2Ccomputers%2C123&sr=1-1) for a lot less :)

**Comment by Arpan-206** [comment]
> > Had to upgrade the 3D Printer as the one I linked turns out to be incompatible for this project.
> 
> @Arpan-206: What about the printer made it incompatible? And what feature of the new printer makes it better fit for your project? I think it would be helpful to know so we can look out for such details in other project proposals involving 3D printers.

I selected the FabX but it was way too small, as I found out during a call with one of my friends who is an electronics engineer.

**Review by cfanoulis — APPROVED** [review]
great, thanks for bearing with uh :) @hackliv send them their cash pls 🙏

**Pull request merged**
