### PR TITLE
Create devramsean0.md

### PR DESCRIPTION
**Pull request by devramsean0**
## Describe your project in 1-3 sentences

I am building a temperature sensor for monitoring water environments safely, displaying temperature on adafruit IO and a oled display

## Hack Club Slack handle

devramsean0

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@devramsean0 oh wow this looks really cool! is there a guide or existing project of sort that you're referencing?

also, do you have an estimate for what the PCB will cost? 

thanks!

**Comment by devramsean0** [comment]
I'm not following any guides of any sort, but it's been an ongoing project for a few years and I have done some extensive research. and I can't see the PCB's costing more than like $10 excluding shipping and taxes

**Comment by bellesea** [comment]
> I'm not following any guides of any sort, but it's been an ongoing project for a few years and I have done some extensive research. and I can't see the PCB's costing more than like $10 excluding shipping and taxes

@devramsean0 fully makes sense, this is super exciting! can you please update your budget with $10 for the PCB + include shipping and taxes estimates for all your parts?

**Comment by devramsean0** [comment]
just updated for that!

**Review by bellesea — APPROVED** [review]
@devramsean0 this looks awesome!! thanks sm for the rapid changes :) @daisybanks will reach out with next steps :)

can't wait to see you build this project!

**Comment by daisybanks** [comment]
hi @devramsean0! This project seems really cool and I'd love to hear more about it on a Zoom call! I'm going to reach out to through Slack to make communications a bit easier moving forward. My Slack handle is @daisy :)

**Review by daisybanks — APPROVED** [review]

**Pull request merged**
