### PR TITLE
Toys come to life

### PR DESCRIPTION
**Pull request by Jackson-Turner**
## Describe your project in 1-3 sentences

 I am building a camera to track what your toys do when you are not around. This project could also be ported to any other thing like pets. 

## Hack Club Slack handle
Cloned Dog

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — COMMENTED** [review]
@Jackson-Turner this looks awesome!! out of curiosity, why did you choose this particular camera?

**Comment by Jackson-Turner** [comment]
@bellesea i chose this camera due to its stereoscopic 3d which will allow for tracking in 3 dimensions. The camera also has a range of features that makes it easier to do computer vision with like de warping.

**Review by bellesea — APPROVED** [review]
@Jackson-Turner this looks awesome!!! can't wait to see how it turns out :) an awesome member of @hackclub/bank-ops will reach out w/ next steps soon!

**Review by MelSmith104 — COMMENTED** [review]
hey @Jackson-Turner !! i love this idea! it makes me think so much of toy story lol :) i'm dm'ing you on slack now to chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
