### PR TITLE
Add Urban Kayak Project Proposal

### PR DESCRIPTION
**Pull request by thekyleliao**
## Describe your project in 1-3 sentences

I am building an urban kayak with an arduino controlled "marine" led light system. Fancy words for its a folding kayak with waterproof leds.

## Hack Club Slack handle

@ Kyle Liao 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x ] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by exu3** [comment]
@thekyleliao Could you please fill out the PR description https://github.com/hackclub/winter/pull/132#issue-1512248951?

**Review by exu3 — APPROVED** [review]
@thekyleliao this is fascinating; it's very creative! 

I think your project proposal is detailed, and your plan is clear. The @hackclub/bank-ops team will follow up with next steps for receiving your grant through Hack Club Bank.

Excited to see how you build this!

**Comment by thekyleliao** [comment]
Thanks, I forgot to write a description.

**Review by arianna-m — APPROVED** [review]
Hi @thekyleliao! WOW, this is awesome! I love this idea, and it sounds so cool. I'm so excited to see your urban kayak come to life. Next steps for us would be to move communications over to Slack so we can move forward! We can schedule a Zoom call, so I can explain how you get the grant and share with you the fiscal sponsorship contract which you'll have to sign with a parent/guardian. Looking forward to working together! :)

**Pull request merged**
