### PR TITLE
Create Raymond131&MarcoKurepa.md

### PR DESCRIPTION
**Pull request by Raymond131**
## Describe your project in 1-3 sentences
Build a lidar capable 250mm sized drone using a stereo camera and Raspberry Pi Zero W setup.
The drone will be capable of 3D position and pose estimation using april tags or some other visual fiducials

## Hack Club Slack handle
Raymond Wu
Marco Kurepa

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by MarcoKurepa — APPROVED** [review]
This comment confirms officially I hope) that I am collaborating on this project with Raymond. My hack club slack handle is "Marco Kurepa"

**Comment by Raymond131** [comment]
My hack club slack handle is "Raymond Wu".

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — APPROVED** [review]
Hey Raymond & Marco! Sick project you've got here. Curious to hear, what's your plan for using the drone?

**Comment by MarcoKurepa** [comment]
> Hey Raymond & Marco! Sick project you've got here. Curious to hear, what's your plan for using the drone?

Well we're both on our school's robotics team and we started working with visual fiducials (april tags specifically) for this year's season, and through research into visual fiducials and how to calibrate cameras, get pose estimations, finding distance to tags and more we ran across a lot of implementations with drones. This sparked our interest in LIDAR and using computer vision for robotics. We're hoping to learn more with this drone and to maybe make some cool projects along the way. One of our ideas for the future once we've become more familiar with the coding process and such is to buy a bigger frame and try to hack up some form of ground penetrating radar and see if we could simulate conditions to search for land mines! This is a far fetched idea and we figured this project would be a good first step towards that:) Thanks for approving us:)

**Review by arianna-m — APPROVED** [review]
Hi @Raymond131 and @MarcoKurepa! This looks awesome! So excited to see your drone come to life! Next steps for us would be to move communications over to Slack so we can move forward! We can schedule a Zoom call, so I can explain how you get the grant and share with you the fiscal sponsorship contract which you'll have to sign with a parent/guardian. Looking forward to working together! :)

**Pull request merged**
