### PR TITLE
Proposal for FPV Drone with controllable arm

### PR DESCRIPTION
**Pull request by ArhanBaner**
## Describe your project in 1-3 sentences

I want to build a FPV drone that has the ability to pick up/drop off small objects around the house. After assembling the drone, I will need to write software using BetaFlight in order to calibrate the drone and make it able to pick/drop objects.

## Hack Club Slack handle

Arhan Banerjee

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@ArhanBaner thank you so much for sharing this!! it's a super cool idea! i noticed that you didn't add a part for the controllable hook (or did i miss it)? 

do you need a power distributor board, batteries, etc.? and, how do you plan on controlling this drone?

btw, is there a drone that you're modelling this after?

thank you!!

also, just to check, do you already have access to a soldering kit?

**Comment by ArhanBaner** [comment]
> @ArhanBaner thank you so much for sharing this!! it's a super cool idea! i noticed that you didn't add a part for the controllable hook (or did i miss it)?

Hey, sorry, I actually already own the controllable hook. It is a 3D printed part that I can print on my own. Here is an [example ](https://www.thingiverse.com/thing:2440453)(but I plan on modifying this file so it can interface with the flight controller chip)

> do you need a power distributor board, batteries, etc.? and, how do you plan on controlling this drone?

There is no need for a power distributor as the flight controller board with the transmitter VTX/ receiver should be enough. I already own the batteries and controller I need from a previous project. I have updated the file with the equipment I already own.

> also, just to check, do you already have access to a soldering kit?

Yup!

**Review by bellesea — APPROVED** [review]
@ArhanBaner thank you so much for the rapid response and changes! this project looks incredible! @daisybanks will reach out with next steps soon.

can't wait to see what you build!

**Review by daisybanks — COMMENTED** [review]
Hi @ArhanBaner - your project sounds really cool (I'm always down for something to make cleaning up a little easier!). Just a head's a up though, it looks like some of the items you planned on ordering are more expensive now than what you budgeted for.

**Comment by ArhanBaner** [comment]
> Hi @ArhanBaner - your project sounds really cool (I'm always down for something to make cleaning up a little easier!). Just a head's a up though, it looks like some of the items you planned on ordering are more expensive now than what you budgeted f

Hi Daisy, thanks for looking into my project! Yeah, I see some of the prices have gone up (in the last two days, haha!) but I don't mind paying a little extra from my own money to purchase some of the components. Does all the components have to under the budget or is it possible for me to cover the small difference if it goes over?

> Also, you'll want to make sure you're budgeting for cost of shipping and taxes as well. :)

I was planning on buying all the components at once, so the shipping should end up being free as its over $50. Similar question to above, can I cover the taxes on my own or do I also have to make it fit in the budget?

Thanks for all your help!

**Comment by daisybanks** [comment]
@ArhanBaner you can be over budget and you're more than welcome to add funds to your project on Bank. :) I'm going to move communications over to Slack so that we can move on to the next step which is schedule an onboarding call to get you set up on Bank!

**Pull request closed without merging**
