### PR TITLE
Quadruped Robot

### PR DESCRIPTION
**Pull request by Scott170c**
## Describe your project in 1-3 sentences

I am building a robot quadruped similar to spot from boston dynamics

## Hack Club Slack handle

Scott Chiang

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hiii @Scott170c this is soooo awesome!! 

could you please do a little more research on finding a design for the robot and getting a vague quote for the parts that will need to be 3d printed? this will help ensure we provide the right amount for you :) please take your time in researching this as we'll be giving out grants till Jan 15!

someone else actually made a PR for a similar project hehe [#50](https://github.com/hackclub/winter/pull/50) if you're interested in checking it out :) fyi: it's 100% cool that your projects are similar, it will not cause your proposal to be rejected.

**Comment by Scott170c** [comment]
> hiii @Scott170c this is soooo awesome!!
> 
> could you please do a little more research on finding a design for the robot and getting a vague quote for the parts that will need to be 3d printed? this will help ensure we provide the right amount for you :) please take your time in researching this as we'll be giving out grants till Jan 15!
> 
> someone else actually made a PR for a similar project hehe [#50](https://github.com/hackclub/winter/pull/50) if you're interested in checking it out :) fyi: it's 100% cool that your projects are similar, it will not cause your proposal to be rejected.

Hi, I am currently in the process of finding a place :). Hopefully I can get that out of the way before jan :)

**Comment by bellesea** [comment]
> > hiii @Scott170c this is soooo awesome!!
> > could you please do a little more research on finding a design for the robot and getting a vague quote for the parts that will need to be 3d printed? this will help ensure we provide the right amount for you :) please take your time in researching this as we'll be giving out grants till Jan 15!
> > someone else actually made a PR for a similar project hehe [#50](https://github.com/hackclub/winter/pull/50) if you're interested in checking it out :) fyi: it's 100% cool that your projects are similar, it will not cause your proposal to be rejected.
> 
> Hi, I am currently in the process of finding a place :). Hopefully I can get that out of the way before jan :)

great! the final date for projects review is Jan 15 so anytime before then would be perfect :) if you want, you could connect with other people doing this event in [#hardware-party](https://hackclub.slack.com/archives/C0168BR5PDE) to see if they have suggestions for places you could source from :)

**Comment by Scott170c** [comment]
> > > hiii @Scott170c this is soooo awesome!!
> > > could you please do a little more research on finding a design for the robot and getting a vague quote for the parts that will need to be 3d printed? this will help ensure we provide the right amount for you :) please take your time in researching this as we'll be giving out grants till Jan 15!
> > > someone else actually made a PR for a similar project hehe [#50](https://github.com/hackclub/winter/pull/50) if you're interested in checking it out :) fyi: it's 100% cool that your projects are similar, it will not cause your proposal to be rejected.
> > 
> > 
> > Hi, I am currently in the process of finding a place :). Hopefully I can get that out of the way before jan :)
> 
> great! the final date for projects review is Jan 15 so anytime before then would be perfect :) if you want, you could connect with other people doing this event in [#hardware-party](https://hackclub.slack.com/archives/C0168BR5PDE) to see if they have suggestions for places you could source from :)

Hi, sorry for the incovinence. I have been very busy lately and I am not sure if I can get my model done in time to get a quote for it. Is it ok if I could estimate how much it would be by getting a quote from a similar design?

**Comment by bellesea** [comment]
@Scott170c yes 100%, an estimate is perfect!

**Comment by Scott170c** [comment]
> @Scott170c yes 100%, an estimate is perfect!

I got an estimate quote, hopefully it is less than what I anticipate. Is there anything else I need to do before my project is approved?

**Comment by bellesea** [comment]
@Scott170c thanks sm for pushing the changes! if you do know, could you please add where you plan on getting the 3d printed parts from? also, could you please also credit the robot design that you're basing your model off?

also, if you want, we'd probably be able to approve you purchasing a 3d printer and filament for this project (since it's necessary to you being able to work on this...), so if you want that could be another option... you might have to foot in some of your own money if the total goes over 250 though. we've had PRs with https://www.amazon.com/Comgrow-Creality-Ender-Aluminum-220x220x250mm/dp/B07BR3F9N6 in the budget...

**Comment by Scott170c** [comment]
@bellesea I'll try fitting a 3D printer in the budget, as it allows me to have more room for error (which will most likely happen). Thanks!

**Comment by Scott170c** [comment]
> @Scott170c thanks sm for pushing the changes! if you do know, could you please add where you plan on getting the 3d printed parts from? also, could you please also credit the robot design that you're basing your model off?
> 
> also, if you want, we'd probably be able to approve you purchasing a 3d printer and filament for this project (since it's necessary to you being able to work on this...), so if you want that could be another option... you might have to foot in some of your own money if the total goes over 250 though. we've had PRs with https://www.amazon.com/Comgrow-Creality-Ender-Aluminum-220x220x250mm/dp/B07BR3F9N6 in the budget...

Got it done, I will cover the costs of the things going over the budget and buy the filament myself. Can you deposit money from Cashapp into Hackclub bank?

**Comment by bellesea** [comment]
> Got it done, I will cover the costs of the things going over the budget and buy the filament myself. Can you deposit money from Cashapp into Hackclub bank?

@Scott170c thanks for pushing the changes! i'm not sure but we could figure out the logistics when you connect with a hack club bank person hehe :)

i'll be approving the project for now to move it along the process but could you please include the filament in your budget (eventhough it's over) just for record keeping purposes? 

can't wait to see you work on this, it's super exciting!

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by bellesea — APPROVED** [review]

**Review by MelSmith104 — COMMENTED** [review]
hey @Scott170c! im so excited about your robot! this is such a cool project :) im dm'ing you on slack to chat through next steps regarding the grant and will also be able to answer any questions you might have!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
