### PR TITLE
Create rahulkarda.md

### PR DESCRIPTION
**Pull request by rahulkarda**
## Describe your project in 1-3 sentences
I am building a weather station using Raspberry Pi 4 with a Sense HAT.

## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by daisybanks — CHANGES_REQUESTED** [review]
Hey there! I just noticed that the box for "I am a current high school student or younger" was not checked. Are you 18 years old or younger? This is one of our requirements for this project and grant and checking the box is our first step in our age verification process. I love your excitement for your project and it sounds awesome! :)

**Comment by rahulkarda** [comment]
I'm 18+

**Comment by daisybanks** [comment]
@rahulkarda are you still in high school?

**Comment by rahulkarda** [comment]
No, I'm in college

**Comment by daisybanks** [comment]
Hi @rahulkarda - I'm sorry for any confusion, but this project and this grant are only for high schoolers or younger and so unfortunately we won't be able to move forward with your project.

**Pull request closed without merging**
