### PR TITLE
Voice controlled car

### PR DESCRIPTION
**Pull request by priyamurugesan24**
## Describe your project in 1-3 sentences

I'm going to build a arduino Voice Controlled Car. This car is designed to be controlled by voice commands. This car is built using arduino uno board,Beardboard(generic), DC motor 12V, micro motors, grippy wheels, Voltage Regulator, DC/Dc gate driver, Jumper wires(Generic), HC-05 Bluetooth module, Bluetooth Low Energy (BLE) Module (Generic),Texas Instruments Dual H-Bridge motor drivers L293D, Battery 12 V. The car operates by having a voice receiver box on it where it receives your voice commands. The car has a 50 foot radius from where it is initially place on the ground. The child interacts with the car by shouting out commands like "faster", "slower", "right", "left", and "stop". The child will be able to feel like they are in full control of the car by doing this, thus giving them the sense of being important. The child programs their own voice into the receiver so that only they can operate the car. The car has an emergency shut down when it reaches the boundary of the 50 foot radius. The child must also be within that 50 foot radius when shouting commands in order for the car to initiate the desired command.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

(note: i understand there's no shipping costs but do you have any taxes?)

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by alhardwarehyde — APPROVED** [review]
I think this an interesting project and it's cool that you are thinking of the broader applications  available with this tech. 

@hackclub/bank-ops for their part

**Review by hackliv — APPROVED** [review]
Omg this sounds so cool @priyamurugesan24 !! I can't wait to hear more about it. 😊 What's your Slack handle so I can dm you about next steps for the grant?

**Comment by priyamurugesan24** [comment]
My slack handle is Priyadharshini. Looking forward to your reply. Thank You ☺.

**Comment by priyamurugesan24** [comment]
Any updates !?

**Comment by hackliv** [comment]
> Priyadharshini

Sending you a dm now! Thanks for your patience 😊

**Comment by priyamurugesan24** [comment]
okay 😊.

**Comment by hackliv** [comment]
> okay 😊.

hey, did you get my dm on Wednesday? just double checking!

**Comment by priyamurugesan24** [comment]
I don't get your dm @hackliv .
Can you check? Then, send again.

**Comment by priyamurugesan24** [comment]
I messaged you in Slack. Check it out.

**Comment by hackliv** [comment]
> I messaged you in Slack. Check it out.

just responded!

**Pull request merged**
