### PR TITLE
Create acornitum

### PR DESCRIPTION
**Pull request by acornitum**
## Describe your project in 1-3 sentences

I am building mini four key keyboards that I would then be able to program various tasks/shortcuts into. The function would be similar to stream decks, and would make workflow much faster.  

## Hack Club Slack handle

Acon 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy @acornitum thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project it looks like your keyboard does not fall under this category but will have to review more in-depth later on)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @acornitum this is super cool! 

a few questions:
- are you building 4 keypads in total so chaining it together to make a 4 by 4? if so, do you have any plans for how you'll be connecting all 4 to your computer at the same time? and, would it be better to instead of buying 4 aluminium keypad shells perhaps custom print your own keypad shell?
- am i right to assume that you'll be writing your own custom keymaps and that's where most of your customisation will be?

thank you!

**Comment by acornitum** [comment]
@bellesea 

1 - that's a good idea! I think what I'm going to do now is to have one mini 4-key keyboard, but then combine the other three to make a bigger 12 key keyboard! I'm going to see if I can find any local 3D printing services and design everything in Tinkercad :) (I can't figure out how to make changes on this file (I'm very inexperienced with github)... the cost would vary and I think would be _probably_ less than 50, which basically replaces the cost for 3 aluminium shells, so the total sum for money would be the same. However, I can't tell how much it'll cost until after it prints because places I've checked prints stuff by material used and I can't determine that before printing. Btw where can i find instructions on how to make changes on file? 🥲 )
2 - yup! I'll be writing my own keymaps for the keyboards. Also, now that I'll be designing my own shell as said above, that'll also be part of the customization! 😄 

Thank you so much for looking over this! :D

**Comment by bellesea** [comment]
@acornitum wahoo these modifications are awesome :)) please let me know if you have any questions and once you push the changes we should be good to move forward!

head to this link: https://github.com/hackclub/winter/pull/293/files

https://user-images.githubusercontent.com/65808924/213756565-bbf2cb1c-8e35-4628-8221-5613dfba8fed.mov

**Comment by acornitum** [comment]
@bellesea 

Thank you so much! I've made the changes, let me know if it's alright now or if it needs any extra changes 😄 Really appreciate the video guide on how to edit too!!

**Review by bellesea — CHANGES_REQUESTED** [review]
@acornitum thanks so much for pushing the changes! one more question: how do you plan on connecting all of your Picos to your computer at the same time? do you need some sort of special connector?

thanks!

**Comment by bellesea** [comment]
hey @acornitum i'm wondering, are you still interested in moving forward with this PR? if so, can you please try and update your PR by this Friday or latest this weekend? If not, we might not have enough time to move forward with the grant and allow you to get your parts in time for the event! thanks :)

**Comment by acornitum** [comment]
Oh yeah def sorry! I've found slightly cheaper sites to buy materials by bulk so I'm changing a few of the prices, along with the connecting Pico thing. Since I'm 3D printing a case, I found that my budget probably fits to build a 4-key keyboard and then another 40% keyboard, since it's not too different from what I have right now and has much more utility. I'll probably get it done by today or tommorow!

As for the Picos, my current plan is to just connect them all to computer, since I have multiple USB ports here. 
Thank you so much!

**Comment by bellesea** [comment]
> Oh yeah def sorry! I've found slightly cheaper sites to buy materials by bulk so I'm changing a few of the prices, along with the connecting Pico thing. Since I'm 3D printing a case, I found that my budget probably fits to build a 4-key keyboard and then another 40% keyboard, since it's not too different from what I have right now and has much more utility. I'll probably get it done by today or tommorow!
> 
> As for the Picos, my current plan is to just connect them all to computer, since I have multiple USB ports here. Thank you so much!

hey @acornitum no worries at all! great, a small note about your 40% keyboard, if it's similar to your current set up with hosting the firmware on a pico etc. it should be fine but if your 40% keyboard is mostly assembling ready made parts (like purchasing a pcb, case, keycaps, etc.) then we are less likely to approve it as it doesn't fully adhere with the intentions of this event/grant. thanks!

**Comment by acornitum** [comment]
Yup it's the same as assembling it with Pico! I'm going to do something very very similar, the only major difference should be that it just has more keys :D

**Comment by acornitum** [comment]
@bellesea 

I have made quite a few changes to the buylist - instead of using the Pico microcontroller, I'm using another microcontroller called Elite-C V4 and the Elite-pi (pretty sure these are made to replicate arduino microcontrollers). (This is partially to save on shipping costs as I'm also getting switches and other stuff from the same site.) Also, I've added a few more links in the middle of the build instructions, to show the wiring for bigger keyboards which I will be loosely following. 

Once again, thank you for checking this over!

**Review by bellesea — APPROVED** [review]
@acornitum apologies for the delayed review! this looks awesome :)

a fabulous member of @hackclub/bank-ops will be reaching out early next week with next steps :)

also, i'd recommend starting the 3d design phase before the 10 days so you can start working on your keyboard then :)

**Comment by acornitum** [comment]
THANK YOU!! I'm so excited to build this keyboard!

and yup, I've already started with the 3d design phase for both the case and plate :D

**Review by daisybanks — APPROVED** [review]
Hi @acornitum! This looks super awesome and fun to build out! I love your enthusiasm for your project! I'm dming you now on Slack to talk about getting you set up on Bank with your grant! :)

**Pull request merged**
