### PR TITLE
AmanTonk15

### PR DESCRIPTION
**Pull request by AmanTonk15**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@AmanTonk15 thank you so much for sharing this project idea, it's super cool! for your summary, could you please also add a few lines about why you're personally interested in building this?

do you need an RFID module or reader of sorts? 

small formatting thing: could you please move the parts that are your plan to under the plan heading instead of summary?

also, could you please update your budget? i think an arduino uno rev3 costs $25 dollars or so? and, could you please also factor in shipping and taxes?

thank you sm!

**Comment by bellesea** [comment]
@AmanTonk15 thanks for pushing the changes! does this total now include shipping and taxes? also, under sumary, could you please add why you'd be interested in building this?

**Comment by bellesea** [comment]
> @AmanTonk15 thanks for pushing the changes! does this total now include shipping and taxes? also, under summary, could you please add why you'd be interested in building this?

heyy @AmanTonk15  hope you're doing awesome! checking in to see if you still interested in moving forward on this project?

**Comment by cfanoulis** [comment]
Hi @AmanTonk15! Thanks for your proposal. It's been a week since Belle's message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Hacky New Year!

**Comment by cfanoulis** [comment]
Hello! Unfortunately 2 days have passed, which means that I'll be closing this PR as stale. If you still wish to pursue a grant please let us know by replying to this PR before Jan. 15th

**Pull request closed without merging**
