### PR TITLE
added BohemaRapsody.md

### PR DESCRIPTION
**Pull request by BohemaRapsody**
## Describe your project in 1-3 sentences

We are going to be constructing a high-speed RC car with the aim of optimising the body car shape to maximise its speed. This will be achieved by completing fluid simulations in Fusion 360 to optimise the aerodynamics on the shell. To manufacture the shell, we will employ FDM 3D printing in a range of materials. Furthermore, we will utilise our school's CNC machine to experiment in other materials such as polycarbonate, acrylic etc... We will also complete generative design studies to generate a chassis that is both lightweight and strong.

## Hack Club Slack handle

Alex Volkovoy
Sebastian Hill
Ibrahim Jamal
Gautham Ravisankar
Aiyush Gupta  *(Does Not Require Grant)*

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a **lower level than a pre-assembled kit of parts & ready software**

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

(note: absolutely love that so many of you are working together on this hehe)

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by Sebulad** [comment]
Thanks, we are really looking forward to start this project, and can confirm that I meet the criteria for PR.

**Comment by Sebulad** [comment]
Hi thanks so much, @Aiyush-G meets the criteria for this project! :). Just to let you know ima also working on another project so I don't need to qualify for this grant in specific. However, the others have only worked on only this project and this is reflected in our PR within the budget section. Note: I have already started working on my individual project but I'm also fully committed to this project within the hackathon period! Can't wait to get started!

**Comment by Aiyush-G** [comment]
Hi thanks so much, @Aiyush-G meets the criteria for this project! :). Just to let you know ima also working on another project so I don't need to qualify for this grant in specific. However, the others have only worked on only this project and this is reflected in our PR within the budget section. Note: I have already started working on my individual project but I'm also fully committed to this project within the hackathon period! Can't wait to get started!

**Comment by BohemaRapsody** [comment]
Hi Belle, thanks for letting us know about the review period 👍 I can confirm that I also meet the checklist criteria.

**Comment by BIBROJAM** [comment]
Hello, thanks for the information, I can also confirm I meet the critera

**Comment by The0mniscient** [comment]
Thank you!! I confirm I meet the criteria. And as mentioned by the others, I am also very excited to see where this project is going to take us.

**Comment by bellesea** [comment]
thank you so much everyone for your rapid response :) we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by Sheepy3 — CHANGES_REQUESTED** [review]
Awesome Idea! As an aerospace nerd I love aerodynamics. I think this project has enough creative design required to justify the purchase of a pre-assembled car.

The only issue I noticed is that you said you wanted to use IPA to smooth ABS. You can't use IPA to smooth ABS I don't believe. You need to use Acetone. I believe you can smooth PVB with IPA though!

Not to backseat your project, but you *might* be interesting in checking out [Lightweight PLA](https://colorfabb.com/lw-pla-natural) over wood fiber PLA. Wood does have lower density than PLA though, so it's a valid choice, apart from it's abrasion issues (which you'll need to research if you havent already). Otherwise, I think this is a good plan! you should definitely publish your data afterwards :)

**Comment by BohemaRapsody** [comment]
Hi Sheepy3,

Great to hear from you - thanks for the ideas. The PR file has now been updated: changed smoothing chemical to acetone; included Light-weight PLA to budget (though we chose to buy from Amazon due to preferable price and delivery time). We will be sure to record and publish results from our project :)

Thank you!

**Review by Aiyush-G — COMMENTED** [review]
@Sheepy3 Changes have been made in the latest version :)

**Review by Aiyush-G — APPROVED** [review]

**Review by Sheepy3 — APPROVED** [review]
Lookin good now!

**Review by MelSmith104 — COMMENTED** [review]
hey everyone! wow! this project looks like so much fun! im so excited for you all to start building :) im dm'ing you all on slack right now to get started on the next steps!

**Pull request merged**
