### PR TITLE
rcyaon.md

### PR DESCRIPTION
**Pull request by rcyaon**
## Checklist before submitting proposal:

- [ ✓ ] I am a current high school student (or younger).
- [ ✓ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ✓  ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ✓ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@rcyaon OMG THIS IS SOOO AWESOME!! 

will you need any wires/breadboard etc.? also, when you say register the button clicks, do you plan on 3d printing the button and wiring it to the Arduino or will you be purchasing a button?

thanks :)

**Comment by rcyaon** [comment]
thank you! sorry i completely forgot to mention that i already have wires
and the breadboard. i’m not sure about the situation with the button yet
since i still haven’t modified the .stl file but either way i already have
the button and 3d printing is free at my school!

would you like me to note these changes on the github?

**Comment by bellesea** [comment]
yes please, thank you sm!

**Comment by rcyaon** [comment]
Done!

**Review by bellesea — APPROVED** [review]
@rcyaon this is super super exciting hehe :) can't wait to see you work on it!

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Comment by rcyaon** [comment]
Awesome, thanks for the update!

**Review by hackliv — APPROVED** [review]
Hey @rcyaon this sounds so cool! I'm dming you now on Slack to set up some time to meet and move forward with the grant through Hack Club Bank. :)

**Pull request merged**
