### PR TITLE
Create xkboo

### PR DESCRIPTION
**Pull request by xkboo**
## Describe your project in 1-3 sentences

I'm building a computer with my friends!

## Hack Club Slack handle

@xkboo

## Checklist before submitting proposal:

- [ ✅ ] I am a current high school student (or younger).
- [ ✅ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ✅ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ✅ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Staleappleslice** [comment]
I am participating in this project with @xkboo 
## Hack Club Slack handle

@Hongyi Xie

## Checklist before submitting proposal:

[ ✅ ] I am a current high school student (or younger).
[ ✅ ] I have submitted an RSVP at https://hackclub.com/winter
[ ✅ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[ ✅ ] I have self-reviewed my project proposal

**Comment by kaavtriv** [comment]
I am completing this project with @xkboo
## Hack Club Slack handle: @kaavya trivedi


## Checklist before submitting proposal:

- [✅ ] I am a current high school student (or younger).
- [✅ ] I have submitted an RSVP at https://hackclub.com/winter
- [✅ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [ ✅] I have self-reviewed my project proposal.

**Comment by LatteMeow** [comment]
I am completing this project with @xkboo
## Hack Club Slack handle
@Claire Mao 

## Checklist before submitting proposal:

- [✅ ] I am a current high school student (or younger).
- [✅ ] I have submitted an RSVP at https://hackclub.com/winter
- [✅ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [ ✅] I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
hiiii @xkboo @kaavtriv @LatteMeow @Staleappleslice, thanks for submitting a project proposal.

Unfortunately, this proposal doesn't quite meet the goals of the event.

The goal of Winter Hardware Wonderland is to make hardware hacking (creatively building things using the details of how electronics work) available to more people, but building a PC in the more mainstream sense (buying a motherboard, processor, etc. then assembling them) doesn't really count. It just should be more lower level than plugging a few components together. To be forthcoming, it's really hard to having a PC as a "hardware project" because it requires a lot of extremely low level knowledge and understanding but here's an example of a project we accepted: https://github.com/hackclub/winter/blob/main/Cooper7196.md

I'm going to close this pull request for now, but feel free to open a new one with a revised project proposal, or re-open this one if it's easier.

Let me know if you have any questions! Thank you and i'm sorry that I don't have better news :(

**Pull request closed without merging**
