### PR TITLE
Create DevinGagnon&

### PR DESCRIPTION
**Pull request by DevinGagnon**
## Describe your project in 1-3 sentences

We are making a high altitude balloon which will be armed with scientific instruments such as a barometer, altimeter, and GPS, to learn more about the atmosphere. this will enable us to learn more about the atmosphere firsthand. We will also have cameras which will be able to capture the ground and the curve of the Earth.
## Hack Club Slack handle

@DevinGagnon 

## Checklist before submitting proposal:

- [yes ] I am a current high school student (or younger).
- [ yes] I have submitted an RSVP at <https://hackclub.com/winter>
- [ yes] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ yes] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by DevinGagnon** [comment]
Sorry this is late, I'm new to GitHub and I couldn't figure out how to get it to work in time.

**Comment by Kiruchan** [comment]
Hack Club Slack handle

Matthew Ong
Checklist before submitting proposal:

    ✅ I am a current high school student (or younger).
    ✅ I have submitted an RSVP at https://hackclub.com/winter
    ✅ I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
    ✅ I have self-reviewed my project proposal.

**Comment by ViraPachima** [comment]
## Describe your project in 1-3 sentences

I want to touch space with my hands

## Hack Club Slack handle

Elliot1221



## Checklist before submitting proposal:

- ✅ I am a current high school student (or younger).
- ✅ I have submitted an RSVP at https://hackclub.com/winter
- ✅ I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- ✅ I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
thanks for pushing changes! we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by alhardwarehyde — APPROVED** [review]
It sounds like you have a good handle on the local laws involved and have considered the safety concern which is great! Just please continue to be aware of local laws and safety when launching this! But it is a really cool project!

@hackclub/bank-ops

**Review by MelSmith104 — COMMENTED** [review]
hey everyone! this project sounds so cool! i too want to touch space with my hands! im dm'ing you all right now on slack to get the process going for the grant!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
