### PR TITLE
Musical Painting

### PR DESCRIPTION
**Pull request by revaga**
## Describe your project in 1-3 sentences

I am building painting that will make music when you touch it.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by cfanoulis** [comment]
hello! from your planning, this sounds like a very cool project! however, I'm having difficulties on understanding _exactly_ what it is. Can you pls provide a 1-3 sentence overview of your project? thanks

**Comment by cupcakes** [comment]
Can you please remove my linked @username from this, thanks!

**Comment by cfanoulis** [comment]
Oops, fixed that, sorry!

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hey! This is a very novel idea, congratulations! However, will you be following a guide to make this? Could you please give us some links that inspired you? Thanks :)

**Comment by revaga** [comment]
I used this video to make my project: https://www.tiktok.com/@muhtanya/video/7046606440378879278?is_copy_url=1&is_from_webapp=v1&lang=en
and this guide: https://www.instructables.com/Touch-Sensitive-Musical-Painting/
(added them to the file too)

**Review by cfanoulis — APPROVED** [review]
Thankchuuu! A member of the @hackclub/bank-ops will be in touch to get you setup with Bank.

**Review by MelSmith104 — COMMENTED** [review]
hey @revaga! this project is so so cool! im so excited to see you build this! im dm'ing you in slack right now so that we can chat about next steps :)

**Comment by revaga** [comment]
Can I update with shipping costs? I also want to remove a product and take two products from a different source.
($6.19 shipping from Digikey)

**Comment by MelSmith104** [comment]
of course! feel free to update as needed :)

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
