### PR TITLE
Plant Watering System 🌱

### PR DESCRIPTION
**Pull request by arjver**
## Describe your project in 1-3 sentences
Me and my brother are making an automated plant watering system. It adapts to the weather, displays information in a web interface, and lets you water your plants remotely.

Note: we're not following any guide on this, but we have a pretty good idea of what the end result should do.

## Hack Club Slack handle
blobbybilb

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by UnstoppableBlob** [comment]
## Hack Club Slack handle
unstoppableblob


## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i really appreciate the elaborate explanations hehe :))_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by kognise — APPROVED** [review]
This looks SUPER awesome! I've always wanted to build one of these myself and even came up with a similar design (although not as aesthetically pleasing as yours, I didn't plan to have a cool access panel) but never actually... had any plants to water.

Just a heads up, this goes $19.80 over the $500 budget, would you be okay with paying that remainder yourself? Otherwise we would love to sponsor this, tagging in @hackclub/bank-ops to get you your money :>

P.S. If you have a Micro Center near you, you could save a bit of money [buying the Ender 3 v2 there](https://www.microcenter.com/product/623606/creality-ender-3-v2-3d-printer).

Please DM me pics on Slack @Kognise when you're done! Looking forward to seeing what you do with the LED matrix.

**Comment by blobbybilb** [comment]
Thanks!

Yes, we're okay with the remaining $19.80 over budget

Unfortunately, there isn't a Micro Center anywhere near me, so that wouldn't work...

BTW, we're thinking about using the LED matrix to display status when not in use, and a plant number when there's something in progress/when choosing what to water. I'll send pics when we've made it!

**Review by MelSmith104 — COMMENTED** [review]
@blobbybilb and @UnstoppableBlob this looks like such a cool project!! my plants always die because i don't water them enough so i feel this project in my soul. im dm'ing you right now to get the process started for the grant!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
