### PR TITLE
pikca-c's project

### PR DESCRIPTION
**Pull request by pikca-c**
## Describe your project in 1-3 sentences

I'm trying to build a desktop sized UK (train) departure boards that looks the same as those you see at National Rail stations! All the data will be obtained from Network Rail and updated in real time.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by cfanoulis — CHANGES_REQUESTED** [review]
oh my god finally a UK train person! im so happy for this project!

Quickly confirm you've budgeted for  taxes & shipping and I'll have you on track for your grant

**Comment by pikca-c** [comment]
Yea, that's £2 ($2.39) in tax for raspberry pi and $2.46 in shipping fees
for the display.

**Comment by cfanoulis** [comment]
Great, one last thing: Would you need extra filament? I don't remember if your 3D printer comes with enough out of the box

**Review by cfanoulis — APPROVED** [review]
Great then! A banker from @hackclub/bank-ops will be in touch shortly

While we wait, can you include any links to tutorials or guides in your proposal? thanks :)

**Review by hackliv — APPROVED** [review]
Hey @pikca-c this sounds so cool!! I love that you're bringing your passion for railway into your project. 😁 Would you be able to share your Slack handle with me so we can chat more about the grant? I couldn't seem to find @ pikca-c on there.

**Comment by pikca-c** [comment]
Oh sorry I forgot to attach my username
Its @PikcaC (U04HJHZ3Y0M)
Thanks!

**Comment by hackliv** [comment]
> PikcaC

ty! dming you now. :)

**Pull request merged**
