### PR TITLE
CodingForAddicts.md

### PR DESCRIPTION
**Pull request by CodingForAddicts**
---
name: @CodingForAddicts
project: TheSleepBuddy

3DLOGO

# TheSleepBuddy (cross project with my friend @LiricTech)
## Summary

I’m going to build a smart litle box with many functionalities like an alarm clock, a temperature sensor, leds that wakes you up or speakers to play calm music to sleep. The idea behind this project is that my friend will make a replica with different functionalities/sensors and the two boxes will connect together to send informations like kind messages (idk). My friend will also make his own pull request when he'll be ready.

## Hack Club Slack handle

@Antoine

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

## Plan

1) Order everything

2) Prototype printing the case in my local FabLab

3) making the final case with polypropylene and wood

4) Program the arduino to do everything I want
 
	4.1) Program the Adafruit LEDS 
	[4.2) Program and connect the temperature sensor to the arduino and to the LEDS.][only if I have the budget after CNC machining and buying the polypropylene parts ]
	4.2) Program the speakers to connect to them in bluetooth with your phone 
	4.3) Program the Segemented display to make a timer before sleep
	4.4) program the LCD display to show the current weather and room temperature with the temperature sensor
5) Assemble everything !
	

## Budget

| Product   | Supplier/Link  | Cost (including some taxes) |
|:--|:--|:--|
| Arduino UNO REV 2 WIFI/Bluetooth (Wifi is needed to connect to my friend’s sleep buddy) | [arduino](https://store.arduino.cc/products/arduino-uno-wifi-rev2?variant=35570905743511) | 55,90 $ (there is a promo code so idont know the exact price)|
| Arduino UNO Mini  (i need two arduinos because i need many ports and the mini one is great because of its footprint.)|  [arduino](https://store.arduino.cc/products/uno-mini-le?variant=41377078542487) | 59,90 $ (there is a promo code so idont know the exact price)|
| Stereo Enclosed Speaker - 3W 8Ω (x2) (for the music) | [arduino](https://store.arduino.cc/products/stereo-enclosed-speaker-3w-8ω?variant=40119999103127) | 9,60 $ (there is a promo code so idont know the exact price)|
| NeoPixel RGB 8 LEDs ADA1426 | [gotronic](https://www.gotronic.fr/art-stick-neopixel-rgb-8-leds-ada1426-22886.htm) | 8,50 $ |
| 5 LEDS RGB ADAFRUIT NEOPIXEL | [gotronic](https://www.gotronic.fr/cat-leds-adressables-1552.htm) | 7 $ |
|  NeoPixel RGB 1m 30 leds ADA1376 | [gotronic](https://www.gotronic.fr/cat-leds-adressables-1552.htm) | 21,86 $ |
| Grove - Touch Sensor (button on the top to stop the alarm) | [arduino](https://store.arduino.cc/products/grove-touch-sensor?variant=35573916991639) | 8,07 $ |
| Jumper Wires |  [amazon](https://www.amazon.fr/YXPCARS-câbles-jumper-femelle-Arduino/dp/B08HQ7K6M7/ref=sr_1_5?crid=TV7B8USTG35U&keywords=jumper+cable&qid=1671636526&sprefix=jumper+ca%2Caps%2C108&sr=8-5) | 11,66 $ |
| Polypropylene parts | ??? | max 10 $ |
| wood parts | ??? | max 15 $ |
| AZDelivery Display Module Vert LCD |  [amazon](https://www.amazon.fr/azdelivery-HD44780-1602-Module-écran-16-caractères-Arduino/dp/B01N3B8JMN/ref=sr_1_5?keywords=ecran%2Blcd%2Barduino&qid=1671636943&sr=8-5&th=1) | 6,89 $  |
| AZDelivery LED Display |  [amazon](https://www.amazon.fr/AZDelivery-Digital-Display-Arduino-Raspberry/dp/B06X952QXS/ref=sr_1_11?__mk_fr_FR=ÅMÅŽÕÑ&crid=FRXJMXVZ4D40&keywords=segmented%2Bi2c%2Bdisplay%2Barduino&qid=1671637038&sprefix=segmented%2Bi2c%2Bdispal%2Barduino%2Caps%2C82&sr=8-11&th=1) | 6,89 $ |
|Breadboard | [amazon](https://www.amazon.fr/gp/product/B08R2YM6RK/ref=ox_sc_act_title_1?smid=A2FA71JYWLOOYW&psc=1) | 6,27 $|
| SUBTOTAL  |  | 221,27 $ |
| TOTAL including taxes + shipping costs |  |  31,76$ + 42,22$ + 120,84$ + 15$ +10$ + shipping costs of the polypropylene parts that I can't know right now = 219,82$

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@CodingForAddicts AHHH THIS IS INCREDIBLE :) love that you're working together w/ a friend too hehe.

since you're purchasing jumper wires, i'm assuming you plan on breadboarding your creation? do you already have a breadboard with the right size to fit inside the box you're designing?

also, thanks for adding taxes, could you please also factor in shipping?

thank you!

**Comment by CodingForAddicts** [comment]
Oh you're right completely forgot to add the breadboard !

**Comment by CodingForAddicts** [comment]
I'm currently calculating the shipping costs :)

**Comment by CodingForAddicts** [comment]
@bellesea I added the shipping costs and calculated the taxes for the things I'm buying on the Arduino store (I completely forgot to haha)

**Comment by bellesea** [comment]
> @bellesea I added the shipping costs and calculated the taxes for the things I'm buying on the Arduino store (I completely forgot to haha)

@CodingForAddicts i see the change in the comments but could you please also add this change to the markdown file? also, could you please check your budget again to make sure you have the right numbers (right now your total is less than your subtotal?)? this helps ensure we disburse the right amount for you hehe. thank you so much!

**Review by bellesea — CHANGES_REQUESTED** [review]
@CodingForAddicts i see the change in the comments but could you please also add this change to the markdown file? also, could you please check your budget again to make sure you have the right numbers (right now your total is less than your subtotal?)? this helps ensure we disburse the right amount for you hehe. thank you so much!

**Comment by CodingForAddicts** [comment]
hey ! it's because I've not included the parts for the box since I don't know the price of it right now

**Comment by bellesea** [comment]
> hey ! it's because I've not included the parts for the box since I don't know the price of it right now

@CodingForAddicts ahhh ok, cool!

**Comment by CodingForAddicts** [comment]
cool !!!

**Review by hackliv — APPROVED** [review]
Hey @CodingForAddicts this looks awesome!! I really love the design you made for it too. :) I'm dming you on Slack now to coordinate getting on to Hack Club Bank with the grant

**Pull request merged**
