### PR TITLE
Dual Compute Work Station with custom work

### PR DESCRIPTION
**Pull request by SiruX21**
## Describe your project in 1-3 sentences

We are building a dual compute workstation with a custom, 3D printed case alongside dual integrated monitors. We will do our best at creating a PCB to connect these monitors to our system.

## Hack Club Slack handle

Siru

## Checklist before submitting proposal:

- [✔️ ] I am a current high school student (or younger).
- [ ✔️] I have submitted an RSVP at <https://hackclub.com/winter>
- [✔️ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✔️ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by RartedRussian** [comment]
I am Eric Zazovsky collaborating with @SiruX21 
[✔️ ] I am a current high school student (or younger).
[ ✔️] I have submitted an RSVP at https://hackclub.com/winter
[✔️ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[✔️ ] I have self-reviewed my project proposal.

**Comment by Look-Its-Sky** [comment]
I'm working with @SiruX21 for this project.
[✔️ ] I am a current high school student (or younger).
[ ✔️] I have submitted an RSVP at https://hackclub.com/winter
[✔️ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[✔️ ] I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by Cimbobimb** [comment]
I'm Andres Perez working with @SiruX21 for this project.
[✔️ ] I am a current high school student (or younger).
[ ✔️] I have submitted an RSVP at https://hackclub.com/winter
[✔️ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[✔️ ] I have self-reviewed my project proposal.

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hey, thanks for the proposal. Unfortunately this proposal is not very different from your earlier proposal - #276

as belle had mentioned, winter wonderland grants are intended to get students working with the very low-level components of electronics. Unfortunately, commercially-available PC components are not "low-level enough", so to speak. As for the custom adapter, we need you to be certain you'll be building it before we take it into account :wink:

I'm able to offer you a **2-day extension, starting today** in order to submit a new proposal. If you're feeling (hardware) creative, please open a new PR, mentioning this PR's ID (#390) by Jan 22nd, 23:59PT. Feel free to use existing proposals as inspiration (but please don't plagiarize!) and, as always, if you want some help about this, feel free to dm me (I'm char on Slack)

**Pull request closed without merging**
