### PR TITLE
thaddeuskkr's proposal - diy smart home

### PR DESCRIPTION
**Pull request by thaddeuskkr**
## Describe your project in 1-3 sentences

I am building a smart home for myself and my family, additionally I'm adding in a home server to stream content or store content. Maybe I'll experiment with Home Assistant.

## Hack Club Slack handle

tk (thaddeus kuah)

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@thaddeuskkr love the idea of building something for your family :) i noticed the pi 4 you linked is out of stock right now, is there another place you migth be able to purchase one?

also, how do you plan on linking your pi to devices around the house? 

and, are you following/modelling after a guide of sorts to help guide you in building this set up?

thanks sm!

**Comment by thaddeuskkr** [comment]
> @thaddeuskkr love the idea of building something for your family :) i noticed the pi 4 you linked is out of stock right now, is there another place you migth be able to purchase one?
I've directly contacted Cytron via WhatsApp, I got a reply that they have a few units left. I assume these aren't shown on the website since it was out of stock before that, but if those aren't available when I need them, I'll probably buy it someplace else online, though I'll keep this updated if that happens.

> also, how do you plan on linking your pi to devices around the house? 
I haven't had experience with this before so I'll probably be playing around with a bunch of software, but based on my searches I'd probably be sticking to Home Assistant the most.

> and, are you following/modelling after a guide of sorts to help guide you in building this set up?
Nope, but imo that's the fun of it :>

**Comment by bellesea** [comment]
> I've directly contacted Cytron via WhatsApp, I got a reply that they have a few units left. I assume these aren't shown on the website since it was out of stock before that, but if those aren't available when I need them, I'll probably buy it someplace else online, though I'll keep this updated if that happens. Was actually quite worried about this originally, even considered purchasing it first, but decided to wait instead.
thanks for the update!!

> I haven't had experience with this (setting up a smart home) before so I'll probably be playing around with a bunch of software, but based on my searches I'd probably be sticking to Home Assistant the most. I might do something on my own with the displays tho. I do however know my way around Linux quite well, after using it as my daily driver OS for a few months - then switching back to Windows 😅, so I guess my experience with the terminal will be useful.
awesome! part of the process is just learning and figuring it out hehe!


> Nope, but imo that's the fun of it :>
haha i love that attitude! might be helpful to take a look at some guides etc. to ensure you have the right parts you need :)

**Review by bellesea — CHANGES_REQUESTED** [review]
@thaddeuskkr i love this idea but am personally a little hesitant to approve the project as i don't really see a clear plan of how you'll use your Pi as an hub to control different electronics around your house... would you be able to do a little more research on the approach? just to make sure you have the parts that you would need... like perhaps you need to purchase some smart home appliances too? or do some research on what devices you'd already have in your house to see if you need to buy any additional modules to connect to it...

please let me know if there's anything i can do to help!

can't wait to review this again :)

**Comment by thaddeuskkr** [comment]
@bellesea Thanks for the feedback! I've now added a guide that I can use, done some research. My bad for being ignorant probably, but I've added 2 dongles as well that I might need to communicate / support more devices. However as to purchasing smart home appliances, I wouldn't include that in my budget as those are things that my family plans to do anyway. As long as I can make sure that my solution can connect to those I should be fine with just having one appliance for now to test. As I haven't moved yet, I'm still not sure as to what devices we will have, but we'll be figuring that out in the next few weeks, after renovation too. I'll also ensure the devices we purchase are compatible with the WebThings software I plan to use. With the 2 modules I've added, there should be a much wider range for device support.

**Comment by bellesea** [comment]
> @bellesea Thanks for the feedback! I've now added a guide that I can use, done some research. My bad for being ignorant probably, but I've added 2 dongles as well that I might need to communicate / support more devices. However as to purchasing smart home appliances, I wouldn't include that in my budget as those are things that my family plans to do anyway. As long as I can make sure that my solution can connect to those I should be fine with just having one appliance for now to test. As I haven't moved yet, I'm still not sure as to what devices we will have, but we'll be figuring that out in the next few weeks, after renovation too. I'll also ensure the devices we purchase are compatible with the WebThings software I plan to use. With the 2 modules I've added, there should be a much wider range for device support.

hiii @thaddeuskkr thanks for the rapid change! no worries at all, and you're not being ignorant at all, it's 100% cool to figure things out along the way (best way to learn is by actually doing it haha). this sounds like a good plan!

**Review by bellesea — APPROVED** [review]
@thaddeuskkr good luck with this!!! i'm sure it'll be awesome and can't wait to see you work on this :)) i'd love to see what your eventual set-up looks like hehe.

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by MelSmith104 — COMMENTED** [review]
hey @thaddeuskkr ! this project sounds so awesome! i love the thought you put into your proposal and i can't wait to see what you build! im dm'ing you on slack so that we can chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
