### PR TITLE
char uses "request a winter grant" - it's very effective!

### PR DESCRIPTION
**Pull request by cfanoulis**
## Describe your project in 1-3 sentences

I'm bringing Assemble voting to the masses :). Users are able to submit their projects for voting, and the system prints out a QR label for them to display. Users scan the label to assign their vote(s), and in the end, the system tallies up and declares* a winner. This all runs locally of a raspberry pi which means it should be very very fast - and can run inside firewalls, airgaps and tight IT admins - just connect to a wifi!

\* actually planning to have humans do that - you shouldnt trust computers to do this :)

**Hack Club Slack handle**: @fanoulis

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>) (~~you tell me~~)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by cfanoulis** [comment]
Yknow what? YOLO.

**Comment by cfanoulis** [comment]
brrrrrr

**Review by bellesea — APPROVED** [review]
@cfanoulis this looks awesome!!! a fabulous member of @hackclub/bank-ops will be reaching out w/ next steps soon :) can't wait to see this being built hehe!

**Review by MelSmith104 — COMMENTED** [review]
@cfanoulis i love this! very eeby deeby of you! dm'ing you on slack for next steps :)

**Comment by cfanoulis** [comment]
for trasparency's sake and due to supply chain issues the total grant awarded for this project has been raised to 205$

Veeby Desby's financials are transparent, enjoy them on da hack bank: https://bank.hackclub.com/veeby-deeby

**Comment by bellesea** [comment]
> for trasparency's sake and due to supply chain issues the total grant awarded for this project has been raised to 210$
> 
> Veeby Desby's financials are transparent, enjoy them on da hack bank: https://bank.hackclub.com/veeby-deeby

@cfanoulis ahhh i love that! could you please open another PR and commit this to the file?

**Pull request merged**
