### PR TITLE
IOT remote control system(IRCS)

### PR DESCRIPTION
**Pull request by xingyujie**
## IOT remote control system(IRCS)
Do you want to remotely turn on your home devices, computers, etc. when you are out? IRCS did just that. When you are on the go, you only need to click on the intuitive visualization panel, and your corresponding equipment will be turned on. Through IRCS, you can monitor your home conditions anywhere in the world, and remotely/wirelessly turn on any device in your home, which is very cool!

## Hack Club Slack handle
@Edward Hsing

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by thomaswcy — COMMENTED** [review]
Cool

**Review by bellesea — CHANGES_REQUESTED** [review]
hiii @xingyujie this is super awesome!!

i'm wondering:
- you mentioned a voltage converter but i don't see it in your budget? do you laready have it?
- are you following any guides of sort?
- does this include shipping and taxes?

please commit the appropriate changes in your file :) thank you sm!

**Comment by xingyujie** [comment]
Shipping is free and there is no tax. I already have a voltage converter. I have committed the updated file. Thank you. Wish you a wonderful day.

**Comment by xingyujie** [comment]
I didn't follow any guides, but I've seen some similar ones, and I found them very interesting, I've implemented a similar project using esp8266, but esp8266 is a microcontroller, so it's not based on Linux, there is no intuitive visual panel, and It is also impossible to realize that one terminal device controls the devices in multiple rooms. But this new project has achieved these.
Thank you very much

**Comment by bellesea** [comment]
> For this project, I didn't follow any guides, but I saw some similar guides, I found it very interesting, I originally implemented a similar project using esp8266, but esp8266 is a microcontroller, so it is not based on Linux, there is no intuitive visualization panel, and it is also impossible for one terminal device to control devices in multiple rooms, etc. But this new project has achieved these. Thank you very much

@xingyujie thanks for pushing the changes! could you please elaborate on how you'd use esp32 to control devices wirelessly? is their role basically to just extend the reach of your pi? and when you say integrate it into different devices do you mean integrating it into non-smart devices (and making them "smart")?

**Comment by xingyujie** [comment]
Thanks for your question. You're all right, the role of the ESP32 can be to smart (and make them "smart") in non-smart devices. Moreover, since ESP32 is wireless, after integrating these non-smart devices with ESP32, they become wireless remote control devices, and IRCS can remotely control these non-smart devices integrated with ESP32. Therefore, IRCS can directly control devices connected to IRCS via cable (DuPont line), or remotely control smart devices modified with ESP32 through wireless

**Review by bellesea — CHANGES_REQUESTED** [review]
@xingyujie ahh cool! could you please add that within your file? and, do you need relays or other electronic components?

thank you :)

**Comment by xingyujie** [comment]
Thank you for your reply! I'll add it to the file right away, and I love hardware so I have lots of electronics. I can get this project done! Thank you
:)

**Review by bellesea — APPROVED** [review]
@xingyujie this looks awesome!!

an awesome member of @hackclub/bank-ops will be reaching out next week (likely tuesday/wednesday) with next steps :)

fyi since your budget is over $250, you'd have to cover the difference yourself OR if you work together with a friend on this we can expand the budget by another $250 :)

**Review by daisybanks — APPROVED** [review]
Hi @xingyujie! This sounds like a cool and fun project! I'm dming you on Slack now to talk about next steps in getting you a new org set up on Bank to receive your grant with!

**Pull request merged**
