### PR TITLE
Project - Pomodoro Timer/TODO List

### PR DESCRIPTION
**Pull request by ByteAtATime**
## Describe your project in 1-3 sentences

I’m building a Pomodoro timer integrated with a TODO list.

## Hack Club Slack handle

`@ByteAtATime`

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@ByteAtATime wahoo this is awesome!! could you please expand a little on what your timer/todo list would actually look like + what you would need in order to build it? it's cool if you want to link a few guides that you'll be referencing :)

and, do you have what you need to program the orange pi? eg. an SD card, HDMI cable, etc.?
https://www.instructables.com/Orange-Pi-PC-Get-Started/
https://orangepione.tumblr.com/post/143493344733/setup-orange-pi-one-without-a-monitor-or-keyboard

and out of curiosity, why are you purchasing an orange pi instead of a rpi?

also, could you please update your budget to include shipping and taxes? 

thank you sm!!

**Comment by ByteAtATime** [comment]
I’m getting an orange pi cause it’s cheaper and also actually in stock, and yeah I currently have an SD card and an HDMI cable.

**Comment by bellesea** [comment]
> I’m getting an orange pi cause it’s cheaper and also actually in stock, and yeah I currently have an SD card and an HDMI cable.

great! what about the rest of the stuff, like a keyboard and linux/windows host computer? OR if you do a headless set up, an ethernet cable or smth?

**Comment by ByteAtATime** [comment]
Yeah, should have everything I need: computer, keyboard, mouse, ethernet, SD card, power adapter, HDMI, OS for pi, etc. I also just updated the doc, should have everything.

**Review by bellesea — APPROVED** [review]
@ByteAtATime thank you so much for taking the time to share your project idea hehe and updating the plans! can't wait to see this being built :)

a member of @hackclub/bank-ops will be reaching out soon with next steps!

**Review by MelSmith104 — COMMENTED** [review]
hey @ByteAtATime ! i love this project idea :) i 100% get where you're coming from with time management! im especially bad in the morning lol. im dm'ing you on slack right now so that we can chat about getting you set up on Bank!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
