### PR TITLE
Gestured Firearm Tank

### PR DESCRIPTION
**Pull request by Aarushgdr**
## Describe your project in 1-3 sentences

I am building a gesture controlled tank which can be controlled by the movement of anyone's hand who is wearing the controller[Glove]. It also has a weapon which can shoot 3d printed bullets and the bullets will be hollow so no one will get harmed from it . By the command of the controller it can also follow anyone if the operator has given command to follow it.

## Hack Club Slack handle

Aarush_Jain

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project it looks like there's a potential for harm, and though i understand the bullets would be hollowed, calling it a weapon kinda sets the tone for this project negatively affecting people around it, which would be a reason we'd reject it.)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by Aarushgdr** [comment]
@bellesea the weapon can be considered as a toy as I will change hollow bullets  to orbeez and then it would not harm anybody and it will work as a shooter only to play. Please let me know if I should change anything.

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
Hi! Could you rename your file so it ends with `.md`? It makes it easier for me and the other reviewers to read about your project.

Other than that, your project sounds great! You didn't talk much about how the gun is going to be able to shoot; do you think you could discuss that in a little more detail?

**Comment by Aarushgdr** [comment]
Hi @jianmin-chen I have renamed my file as Aarushgdr.md. The shooter will be powered by bo motors so whenever the bo motor will spin, it will shoot the orbeez.

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
Thanks for converting the file to `.md`! Could you please fix the table? Here's an example of how the snippet should look:

| Product         | Supplier/Link                         | Cost   |
| --------------- | ------------------------------------- | ------ |
| Pack of wires   | https://www.adafruit.com/product/1957 | $1.95  |
| 1.8"LCD display | https://www.adafruit.com/product/358  | $19.95 |
| Total           |                                       | $21.90 |

In Markdown, that'll look like:

```md
| Product         | Supplier/Link                         | Cost   |
| --------------- | ------------------------------------- | ------ |
| Pack of wires   | https://www.adafruit.com/product/1957 | $1.95  |
| 1.8"LCD display | https://www.adafruit.com/product/358  | $19.95 |
| Total           |                                       | $21.90 |
```

**Comment by bellesea** [comment]
hey @Aarushgdr hope you're doing awesome! it's been two days since jc's request for review, i'm wondering, when do you think you'll be able to make the changes? we'd love to move forward with reviewing this PR so you can get your parts in time for the event :) thanks!

**Comment by cfanoulis** [comment]
Heyoo! It's been a while since we last heard from you. If you're still interested in the grant, please reply to this PR (by email or GitHub) within the next 48 hours (that is, until Jan 26th) so that we can continue with the grant process - else we will be closing this request. If you have decided you will not be pursuing a grant, thank you for your time o7

**Comment by cfanoulis** [comment]
Hello

We have unfortunately not received a reply within the 48 hour timeframe, so we'll be closing this PR. Thanks for taking time to submit a grant request :) have a hacky day

**Pull request closed without merging**
