### PR TITLE
Line following robot

### PR DESCRIPTION
**Pull request by BloggingKIng**
## Describe your project in 1-3 sentences

I am creating a Path following robot that will follow a certain path. It will be designed it a way that it should be able to perform good at even the most difficult tracks!
## Hack Club Slack handle

@Huzaifa Azhar

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @BloggingKIng this is a super cool project! how do you plan on building the casing for your car? do you have the necessary materials/tools for that?

btw, did you factor in shipping and taxes?

thank you sm!

**Comment by BloggingKIng** [comment]
Oh let me fix these

**Comment by BloggingKIng** [comment]
Have added shipping rates. For the chasing part I will try to cover much of the expenses myself. Also I have a question what do you guys consider high school grade 9-12?

**Comment by bellesea** [comment]
> Have added shipping rates. For the chasing part I will try to cover much of the expenses myself. Also I have a question what do you guys consider high school grade 9-12?

sounds good! yep, high school is grade 9-12 (or equivalent) and we're open to anyone that's high school aged or younger. if you're not sure you qualify, please reach out to us at bank@hackclub.com and expand on your situation? we do have a verification process before disbursing the grant that will confirm you're a high school student or younger. 

thank you sm!

**Review by bellesea — CHANGES_REQUESTED** [review]
@BloggingKIng thank you sm for the quick response! could you please add your plan for casing within the budget (even if you'll pay for most of it yourself) just so we can have a "complete public record" of your plan for the project?

thank you!!

**Comment by BloggingKIng** [comment]
Hi there, I have added the price of chasing in the project folder

**Comment by BloggingKIng** [comment]
Also, I just wanted to ask if it's necessary to purchase the product from the same supplier whose link is present in this github pull request? Or we can purchase it from any supplier as long as we upload the transcript of the payment!

**Comment by bellesea** [comment]
@BloggingKIng thanks for adding it! we ask that you order from the link that you listed as that helps us 1. make sure you're spending the grant on what you planned and 2. we give you enough to buy the parts (because we disburse up to $250).

however, it's cool if while researching and actually buying the parts you find that another supplier might be a better fit, if you just check w/ the Hack Club Bank team member you'll be in contact with, i think it should be fine :)

**Review by bellesea — APPROVED** [review]
@BloggingKIng can't wait to see this robot come to life :) an awesome member of @hackclub/bank-ops will be reaching out soon!

**Review by daisybanks — APPROVED** [review]
@BloggingKIng this project sounds wicked cool! It kind of reminds me of those videos you see where someone draws a circle around a bug and then the bug won't leave the circle.. idk that's just the first thing that came to mind. anyway, thew next step for us would be to move communication over to Slack and then set up a time to meet on a Zoom call so I can explain how you can receive the hardware grant! :)

**Comment by BloggingKIng** [comment]
ok

**Review by daisybanks — APPROVED** [review]

**Pull request merged**
