### PR TITLE
Created MnKBuild.md | submitted keyboard proposal

### PR DESCRIPTION
**Pull request by silvermango9927**
## Describe your project in 1-3 sentences
I'm building a simple, yet cool (personally) 75% mechanical keyboard from a keychron DIY starter kit and sourced keycaps and switches. This will involve lubing, assembling the case and PCB, assembling switches, and even designing macros and customizable buttons. To complement this, I will be using an M720 mouse to pair along amazingly.

## Hack Club Slack handle
abhayy(silvermango)

## Checklist before submitting the proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project it looks like it might not be the right project for this event given that this looks mostly like a keyboard assembled from consumer components and the goal of this event really is to encourage and make possible engaging with hardware on a lower level than ready parts... some customizations I might suggest: creating a custom layout, designing your own PCB, or compiling your own firmware. for ideas, I'd highly recommend checking out the links in this Slack message: [hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499](https://hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499))_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey Abhay! Hope all is well :D As Belle mentioned, we're veering away from keyboards for WHW; do you have any other project ideas you could propose?

**Comment by silvermango9927** [comment]
Hey Sam,How’s it going ? Okay that’s alright so in the back of my mind, i was thinking more of a jetson nano and creating an AI program with code to hook it up. Can i cook up the details and update it during the CNY holidays ?thanks,Abhah Sent from my iPhoneOn 19 Jan 2023, at 12:43 AM, Sam Poder ***@***.***> wrote:﻿
@sampoder requested changes on this pull request.

Hey Abhay! Hope all is well :D As Belle mentioned, we're veering away from keyboards for WHW; do you have any other project ideas you could propose?

**Comment by sampoder** [comment]
@silvermango9927 doing well myself! Sounds like a plan, try and get it in early so you're all set in time.

**Comment by sampoder** [comment]
@silvermango9927: go for it! Try and get in soon so you can get your parts in time.

**Comment by cfanoulis** [comment]
Heyoo! It's been a while since we last heard from you. If you're still interested in the grant, please reply to this PR (by email or GitHub) within the next 48 hours (that is, until Jan 26th) so that we can continue with the grant process - else we will be closing this request. If you have decided you will not be pursuing a grant, thank you for your time o7

**Comment by cfanoulis** [comment]
Hello! We unfortunately haven't heard back from you - so I'm closing this proposal. Thanks for taking the time to submit a winter wonderland grant request :)

**Pull request closed without merging**
