### PR TITLE
Create ahnedmohamed57.md

### PR DESCRIPTION
**Pull request by ahnedmohamed57**
## Checklist before submitting proposal:

- [ x] I am a current high school student (or younger).
- [ x] I have submitted an RSVP at <https://hackclub.com/winter>
- [ x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: are you following any sorts of guides for this and that looks like less parts than needed for a 3d printer from scratch, do you already have parts? if so, can you please still add it under budget but just put it as $0?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by ahnedmohamed57** [comment]
I updated it!
Also, I am following a guide to create it for sure! This was my capstone project the last year but it was not completed.

**Comment by bellesea** [comment]
> I updated it! Also, I am following a guide to create it for sure! This was my capstone project the last year but it was not completed.

@ahnedmohamed57 cool! could you please also link the guide within your file? :)

**Comment by ahnedmohamed57** [comment]
Done!

**Comment by ahnedmohamed57** [comment]
Done!
Is there anything else should I do?

‫في الأحد، 15 يناير 2023 في 9:37 م تمت كتابة ما يلي بواسطة ‪Belle‬‏ <‪
***@***.***‬‏>:‬

**Comment by bellesea** [comment]
hey @ahnedmohamed57 like mentioned in the initial message, we'll be reviewing the PRs starting Tuesday so might have more changes then when we're able to do a full review hehe but for now you're all good! thank you :)

**Comment by ahnedmohamed57** [comment]
Great!
Thank you so much

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
Hi there! Could you rename your file so it ends with `.md`? It makes it easier for me and other reviewers to read about your awesome project :)

Other then that, I don't see the link to the guide - could you please include that in the file?

**Comment by ahnedmohamed57** [comment]
Done!

‫في الأربعاء، 18 يناير 2023 في 2:30 ص تمت كتابة ما يلي بواسطة ‪Jianmin
Chen‬‏ ***@***.***‬‏>:‬

**Comment by jianmin-chen** [comment]
The guide looks cool! Is there a specific guide you're going to be following though? I noticed a couple of 3D printer guides on the wiki.

**Comment by ahnedmohamed57** [comment]
I think it is the same process. There are no significant differences. Also,
I will rely on myself.

‫في الأربعاء، 18 يناير 2023 في 3:55 م تمت كتابة ما يلي بواسطة ‪Jianmin
Chen‬‏ ***@***.***‬‏>:‬

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
Okay! Before I approve - it looks like the total cost is a bit off. Do you mind recalculating and updating the table with the appropriate value?

**Comment by ahnedmohamed57** [comment]
I did not get you well!
But this is the actual cost from amazon with the shipping fees.
It is good for me, if you have any misunderstandings or any problem, please
let me know!

‫في الاثنين، 23 يناير 2023 في 4:06 م تمت كتابة ما يلي بواسطة ‪Jianmin
Chen‬‏ ***@***.***‬‏>:‬

**Comment by jianmin-chen** [comment]
Okay - can you take a screenshot for me so I can clarify?

**Comment by jianmin-chen** [comment]
Hmm, I only see `[image: image.png]`. Let's try this a different way. Did you forget to add shipping + taxes? That could be why the total in your table doesn't add up to the total you provided.

**Comment by ahnedmohamed57** [comment]
Is it clear rn?

‫في الاثنين، 23 يناير 2023 في 11:06 م تمت كتابة ما يلي بواسطة ‪Jianmin
Chen‬‏ ***@***.***‬‏>:‬

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
The total in the table adds up to $173.50. I can update the total for you, but it doesn't add to $230. Are you missing anything? If not, I'll update the total to reflect the cost in the table as I see it.

**Comment by ahnedmohamed57** [comment]
So sorry!
I forgot to update the shipping and import fees deposit. I updated it now!
Is it okay now?

‫في الثلاثاء، 24 يناير 2023 في 4:17 م تمت كتابة ما يلي بواسطة ‪Jianmin
Chen‬‏ ***@***.***‬‏>:‬

**Review by jianmin-chen — APPROVED** [review]
Awesome! A member of @hackclub/bank-ops will be reaching out soon :)

**Comment by ahnedmohamed57** [comment]
Great, thanks!

‫في الخميس، 26 يناير 2023 في 3:52 م تمت كتابة ما يلي بواسطة ‪Jianmin Chen‬‏
***@***.***‬‏>:‬

**Review by hackliv — APPROVED** [review]
Hi @ahnedmohamed57 this sounds so awesome!! I'm dming you now on Slack to coordinate some time to meet and chat more about the grant. 🎉

**Pull request merged**
