### PR TITLE
Omay238 - pong

### PR DESCRIPTION
**Pull request by Omay238**
## Describe your project in 1-3 sentences

I am building a pong table. There will be paddles and a ball, controlled by magnets. All of the hardware will be controlled by an Arduino Uno.

## Hack Club Slack handle

Omay

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@Omay238 omg are you building atari pong (similar to this? https://www.youtube.com/watch?v=kA6oYQE96aI)? sooo cool!!

could you please expand a little bit on what kind of software you need to write? and, is there a pong board or build guide you're referencing? you also mentioned using a 3d printer, do you plan on designing the parts you're printing or are you able to find existing models online?

also, could you please factor in shipping and taxes?

thank you sm!

**Comment by Omay238** [comment]
I believe I have added your requested changes. Can you please confirm it? The order qualifies for free shipping, so that shouldn't be an issue. Also, I believe that is the same board I saw at the pinball place.

**Comment by bellesea** [comment]
> I believe I have added your requested changes. Can you please confirm it? The order qualifies for free shipping, so that shouldn't be an issue. Also, I believe that is the same board I saw at the pinball place.

@Omay238 thanks so much for updating it! one small thing, do you have a USB cable that would allow you to connect your arduino to your computer?

**Comment by Omay238** [comment]
> @Omay238 thanks so much for updating it! one small thing, do you have a USB cable that would allow you to connect your arduino to your computer?

Yes, I do.

**Review by bellesea — APPROVED** [review]
@Omay238 can't wait to see you work on this!! 

a member of @hackclub/bank-ops will reach out next week w/ next steps! hacky holidays :)

**Review by arianna-m — APPROVED** [review]
Hi @Omay238! Wow, this sounds awesome! I love how you have a classic game but you're taking it to the next level. I'm so excited to see IRL Pong come to life. Next steps for us would be to move communications over to Slack so we can move forward! We can schedule a Zoom call, so I can explain how you get the grant and share with you the fiscal sponsorship contract which you'll have to sign with a parent/guardian. Looking forward to working together! :)

**Pull request merged**
