### PR TITLE
DIY Tablet

### PR DESCRIPTION
**Pull request by Caninish**
## Describe your project in 1-3 sentences

It's a DIY tablet. I want to make this to sketch with, but at the same time learn something.

## Hack Club Slack handle

@Caninish

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a **lower level than a pre-assembled kit of parts & ready software**

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by Sheepy3 — CHANGES_REQUESTED** [review]
Hey Cainish! I love this project. as someone who draws a bunch, this is a project that speaks to me. However, we feel as if your project is too simplistic as it stands. There's a lot of things you could add to this project, such as:
-a custom & more compact battery
-more advanced case design (stand & pen holder, I suggest in conjunction with one other idea)
-active cooling
-integrated macro keys for undo/pen/eraser etc
-speakers
-battery indicator
You've still got a bit of budget left, so I think you could fit one or more of these ideas into your project. if you'd like to scrape a few bucks off, [I found a similar spec screen you could take a look at.](https://www.amazon.com/SunFounder-Raspberry-Touchscreen-1024%C3%97600-Capacitive/dp/B07Y889J3X?th=1)

Would love to approve of this project when you improve it :)

**Comment by bellesea** [comment]
hey @Caninish it's been a few days since sheepy3's request for changes :) i'm wondering, are you still interested in moving forward with this PR? we look forward to reviewing this soon so you can get your parts in time for the event! thanks :)

**Comment by Caninish** [comment]
Sorry for the late reply. Yeah, I'll still be going forward with this.
Thanks Sheepy3 for the suggestions. I'll add a penholder to the case and a undo button. (That would be soooo useful.)

**Comment by Sheepy3** [comment]
hey, looking good! final thing, do you already own a button to implement into your tablet, or do you need to buy one? If I'm not mistaken, I don't believe you added one to your PR.

**Comment by Caninish** [comment]
I already have one. I've fixed the PR to include it.

**Review by Sheepy3 — APPROVED** [review]
Approved!

**Comment by bellesea** [comment]
an awesome member of @hackclub/bank-ops will be reaching out next week with next steps :)

**Review by hackliv — APPROVED** [review]
wow @Caninish this is so cool! I am so excited to see you make this!! Dming you now on Slack to set up some time next week to chat about the grant 😃

**Comment by hackliv** [comment]
I'm closing this PR due to Slack dms being unresponded to.

**Pull request closed without merging**
