### PR TITLE
3D printed mechanical keyboard

### PR DESCRIPTION
**Pull request by iwang-1**
## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by tinuh** [comment]
Hey @iwang-1, really love your idea of 3D printing custom keycaps, looking forward to seeing how you customize your keycaps. Before we get you set up with the grant I have a few suggestions.

- Can you update your budget to take into account shipping and taxes?
- I see that you're working with your sister on this, just to verify that she'll be working with you on this, could you have her comment on this pull request? Also, could you update your comment on this pr with your slack handle as well as your sisters? That way you can also expand your budget to $500
-  How do you plan on creating a 3D scan of a keycap? Instead of scanning it, I recommend using a 3D model of a keycap online as a reference for creating your custom designs.
- Do you need any other tools for building your keyboard such as tools to open keycaps and/or brushes to use when lubing your switches? If so be sure to add that to your budget too.
-  If you have a micro center nearby here is a more cost-efficient [resin 3D printer](https://www.microcenter.com/product/657436/creality-ld-002r-lcd-resin-3d-printer) that has a really good deal I think.

**Comment by kelly2582** [comment]
Hey, I'm very excited to start creating this keyboard!

**Comment by iwang-1** [comment]
Hey, my github is Ivan Wang and my id is U04G4SC76FK. My sister's is Kelly Wang and id is U04HSFGSK1N

**Comment by tinuh** [comment]
Hey, just checking in, make sure you separate the 4 items into their own respective row

**Comment by iwang-1** [comment]
> Hey, just checking in, make sure you separate the 4 items into their own respective row

I just redid the budget. I put the shipping and tax of all items form the same website onto the most expensive item from said website. lmk if I need to change anything else!

**Comment by tinuh** [comment]
Hey, could you respond to the other suggestions that I posted earlier?

**Comment by iwang-1** [comment]
> Hey @iwang-1, really love your idea of 3D printing custom keycaps, looking forward to seeing how you customize your keycaps. Before we get you set up with the grant I have a few suggestions.
> 
> * Can you update your budget to take into account shipping and taxes?
> * I see that you're working with your sister on this, just to verify that she'll be working with you on this, could you have her comment on this pull request? Also, could you update your comment on this pr with your slack handle as well as your sisters? That way you can also expand your budget to $500
> * How do you plan on creating a 3D scan of a keycap? Instead of scanning it, I recommend using a 3D model of a keycap online as a reference for creating your custom designs.
> * Do you need any other tools for building your keyboard such as tools to open keycaps and/or brushes to use when lubing your switches? If so be sure to add that to your budget too.
> * If you have a micro center nearby here is a more cost-efficient [resin 3D printer](https://www.microcenter.com/product/657436/creality-ld-002r-lcd-resin-3d-printer) that has a really good deal I think.

I have updated the budget to take shipping and tax into account. My GitHub is Ivan Wang and my id is U04G4SC76FK. My sister's is Kelly Wang and id is U04HSFGSK1N. To scan the keycap, I plan to use the iPhone's scanning feature. I might also go on Thingiverse to find the dimensions needed for a keycap. I have added all the tools needed for this project to the cart. I have swapped from a resin 3D printer to a filament printer as a resin printer seems to be a little more dangerous compared to a filament printer.

**Comment by tinuh** [comment]
Hey Ivan, you provided the same link for 4 of the items that you plan on purchasing, it would be great if you could provide the actual link for each of those items. Also, it would be helpful if you put Taxes and Shipping as separate items because it would provide a more clear breakdown. I totally understand the safety concerns with a resin 3D printer but it may provide better-quality keycaps and an overall better keyboard in your case, so I would consider that again, but it's totally fine if you want to move forward with a filament-based printer.

**Comment by iwang-1** [comment]
> Hey Ivan, you provided the same link for 4 of the items that you plan on purchasing, it would be great if you could provide the actual link for each of those items. Also, it would be helpful if you put Taxes and Shipping as separate items because it would provide a more clear breakdown. I totally understand the safety concerns with a resin 3D printer but it may provide better-quality keycaps and an overall better keyboard in your case, so I would consider that again, but it's totally fine if you want to move forward with a filament-based printer.

ok I changed the budget so the links are right (mb). There are two main concerns I have about resin printing. One is that I heard that the chemicals could be dangrous to inhal which I dont want to deal with in my house. The other is that the print bed of a resin printer is generally just smaller and doesn't look big enough to print the keyboard case. Also buying resin is a lot more expensive compared to buying filament for the amount of quantity you get.
lmk if there's anything else I gotta do

**Comment by tinuh** [comment]
Everything looks good, just to make sure, are you able to cover the amount past the $500 grant limit?

**Comment by iwang-1** [comment]
> Everything looks good, just to make sure, are you able to cover the amount past the $500 grant limit?

yea thats fine, anything after 500 we can cover.

**Comment by tinuh** [comment]
Alright since everything looks good an awesome member of @hackclub/bank-ops will reach out to you soon to get you setup with the grant! Looking forward to seeing your project come to life!

**Review by tinuh — APPROVED** [review]

**Review by hackliv — APPROVED** [review]
hey @iwang-1 and @kelly2582 this looks awesome! I'm dming you both now on Slack to chat about next steps for the grant. 😃

**Comment by iwang-1** [comment]
> hey @iwang-1 and @kelly2582 this looks awesome! I'd love to dm you both on Slack to chat about next steps for the grant. 😃 Are you able to share your handles with me? ty!

yea! My slack ID is U04G4SC76FK my display name is Ivan Wang. My sister's ID is U04HSFGSK1N. Her display name is Kelly Wang. lmk if u need to have anything else!

**Comment by hackliv** [comment]
> > hey @iwang-1 and @kelly2582 this looks awesome! I'd love to dm you both on Slack to chat about next steps for the grant. 😃 Are you able to share your handles with me? ty!
> 
> yea! My slack ID is U04G4SC76FK my display name is Ivan Wang. My sister's ID is U04HSFGSK1N. Her display name is Kelly Wang. lmk if u need to have anything else!

thanks! just dmed you both 😃

**Comment by hackliv** [comment]
Hi @kelly2582 real quick before I merge the PR, are you able to reply with answers to the checklist? Please also add your Github @ to the name section on your PR!  😃 thanks

**Comment by kelly2582** [comment]
> * [x]  I am a current high school student (or younger).
> * [x]  I have submitted an RSVP at https://hackclub.com/winter
> * [x]  I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
> * [x]  I have self-reviewed my project proposal.

@kelly2582

**Review by hackliv — APPROVED** [review]

**Pull request merged**
