### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by neomycin05**
## Describe your project in 1-3 sentences
I am building a LED light display that can be controlled through an app.

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

(note: i don't think we can view your file as i think it's encoded as a pdf... can you please make sure it's a markdown file? thank you sm!)

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by bellesea** [comment]
hey @neomycin05 it looks like you added a zip file? and, we're still unable to view your markdown file :( please let us know if you need any help with this and no rush at all! we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Comment by neomycin05** [comment]
me and my friend both converted our pdf documents into a markdown file the
same way, but you guys can see his but not mine.

**Comment by maxwofford** [comment]
I've just added the markdown I found in [Output.zip](https://github.com/hackclub/winter/pull/394/files#diff-99d751145d0c81482526f1120f784d0e2f21db9d455cd2a60c378e859974500a)

**Review by Sheepy3 — CHANGES_REQUESTED** [review]
Hey, custom keyboards are awesome! However, we're looking to fund projects which go farther than assembling existing components, as you've described here. I won't close this immediately though; there are are a few ways you could improve this. a Custom PCB or custom layout which require much lower level design (custom chassis, PCB design, etc.)  would make this project line up better with our requirements. 

I also ask that you add your budget total to your plan :)

**Comment by bellesea** [comment]
hey @neomycin05 it's been a few days since Sheepy3's request for changes. i'm wondering, are you still interested in moving forward with this PR? if so, please update your PR by this Friday at 11:59pm ET so that you to get your parts in time for the event! thanks :)

**Comment by neomycin05** [comment]
Yes, I am working on it. Thank you!

**Comment by cfanoulis** [comment]
Hi! As we need to wrap up on proposals this week, please reply to @Sheepy3's request for changes within the next 24 hours - else we will be closing this PR.

**Comment by cfanoulis** [comment]
As it has been more than 24h since my last message and we haven't heard from you, this PR is stale and I'll be closing it. Thank you for submitting a WHW proposal!

**Pull request closed without merging**
