### PR TITLE
xhaidendsouza 3d mechanically coded robot

### PR DESCRIPTION
**Pull request by xhaidendsouza**
## Describe your project in 1-3 sentences

We are building a 3d printed robot that can be coded mechanically.

## Hack Club Slack handle

Xhaiden D'Souza

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project it looks really cool and i'm wondering: do you plan on 3d printing everything other than the motors? is that possible? also, what's the reason for wanting to 3d print most of the robots? how will yours be different?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by bellesea** [comment]
@xhaidendsouza cool! thank you sm :) we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Comment by xhaidendsouza** [comment]
No worries, thanks for the update!

**Review by alhardwarehyde — COMMENTED** [review]
a Mechanically Coded Robot sounds like a really great project! Can you get us a few more details, like will you need cables, batteries etc? 

And I see you're getting a high max temp 3d printer but not getting the appropriate filament. Have you considered getting a cheaper printer with a larger area and using the other funding for a raspberry pi to run octoprint to remotely monitor prints?

**Comment by xhaidendsouza** [comment]
Hello. As for the cables and batteries, we will need those and a single
switch, just so the motor can be turned on and off. It doesn't need to be
very complicated, but we are having a lot of trouble finding that for some
reason. I will try to add that to the budget soon. We also may try to
switch to a smaller motor.

As for the filament, I just noticed that our most recent commit did not
actually get committed. We were planning and getting a red, blue, and black
PLA+ filament
https://store.creality.com/products/ender-1-75mm-pla-3d-printing-filament-1kg-2p0t?variant=d5d31413-15ce-4ba6-b3cb-255ab1c99847.
And I will update the budget accordingly when I am next available later
today.

Most of the reasons why we got this specific 3d printer are that there were
a lot of other features unique to it like the PEI spring steel build plate
and many others, and it was rated very high overall. The reviews of print
quality, ease of use, leveling accuracy, easy assembly, and many other
things were especially high for this printer (especially the print
quality), which is why we wanted to get it. While the high temp is just one
thing that we are not necessarily making too much use of in this project,
the variety of other features this printer has to offer made us feel that
this investment would make more sense than something like remotely
monitoring prints and larger build area, which we found less essential for
our specific project. Since we prefer the focus to be the highest quality
prints possible on this, especially considering the number of 3d printed
parts we would need, we felt that this printer would best suit our needs.
This printer is also tested by Creality with the PLA+ filament we are
planning to use, and this ensured compatibility would be extremely
beneficial. Overall, we did consider buying a cheaper printer and using the
other funds for other things, but after extensive research, we feel that
this is the best printer for the multitude of high-quality and precise
prints needed for the job.

**Review by Sheepy3 — CHANGES_REQUESTED** [review]
Hey guys, cool project!
I'd like to bring up the overspec'd 3D printer again, I've read your comment, and I think you'd be better off getting the S1 rather than the S1 Pro. It has all the features you want, and costs a lot less. You may also want to consider other components outside of exclusively 3D printed ones. I'm not the best mechanical designer in the world, but you'll want to think about screws, ball bearings, etc. as plastic isn't the best in the world for fastening and rotating parts. I'd also suggest having a method to alter the speed of your motor. I know these are things you addressed earlier, but you may want to reconsider. these are ultimately just suggestions though .

I like this project, but given your very vague plan, I'm worried about your budget almost exclusively focused on printing components. I'd love to approve this soon!

**Comment by xhaidendsouza** [comment]
The S1 doesn't have all of the features we want like the PEI spring steel
and the touch screen, and although we would prefer getting the S1 Pro, we
would be fine with getting the S1 instead of the Pro, since it doesn't make
too much of a difference.
As for your concern about the motor speed we were planning on that being
changed with a gear ratio.
As for your concern about only printing pieces, and us needing parts like
screws and ball bearings, we were planning to have the pieces mostly snap
together, and use hot glue or the glue in the kit that we have in the
budget if necessary. For example, in one of the reference videos we went
to, that robot is almost entirely made of plastic, except for the axles,
which should be 3d printable as well.

**Review by Sheepy3 — APPROVED** [review]
Thank you for the response, Im interested in seeing your gear ratio speed control. I think you guys are good to go!

**Comment by xhaidendsouza** [comment]
Thanks, just to confirm, do we need to change the printer to the S1?

**Comment by Sheepy3** [comment]
> Thanks, just to confirm, do we need to change the printer to the S1?

nope, was just a suggestion :)

**Comment by lolguineapig** [comment]
Ok thank you

**Comment by lolguineapig** [comment]
@devramsean0 For some reason, the checklist is already filled out for me. 
image

**Comment by devramsean0** [comment]
Do it like the person at  https://github.com/hackclub/winter/pull/358#issuecomment-1383274116 hsve done it

**Comment by lolguineapig** [comment]
Here is the checklist:

 [x] I am a current high school student (or younger).
 [x] I have submitted an RSVP at https://hackclub.com/winter
 [x] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
 [x] I have self-reviewed my project proposal.

**Comment by daSeaTurtle** [comment]
Here is my checklist.
- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at https://hackclub.com/winter
- [x] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [x] I have self-reviewed my project proposal.

**Comment by lolguineapig** [comment]
Sorry if my last one checklist didn't work. Here is my new one:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at https://hackclub.com/winter
- [x] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [x] I have self-reviewed my project proposal.

**Review by MelSmith104 — COMMENTED** [review]
hey @xhaidendsouza, @daSeaTurtle and @lolguineapig! awesome project idea! it sounds like its going to be such a fun first project to work together on as a team! im dm'ing you all on slack right now to get started with next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
