### PR TITLE
DIY Portable Monitor

### PR DESCRIPTION
**Pull request by Songrocks**
## Describe your project in 1-3 sentences

I am building a portable monitor with @unblinding that you can use with your laptop as a DIY project. It will give you an extra screen to use anywhere and make multitasking easier. The added screen will increase productivity and give you the flexibility to work and move around.

## Hack Club Slack handle
songrocks

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by unblinding** [comment]
## Describe your project in 1-3 sentences

I am building a portable monitor with @Songrocks  that you can use with your laptop as a DIY project. It will give you an extra screen to use anywhere and make multitasking easier. The added screen will increase productivity and give you the flexibility to work and move around.

## Hack Club Slack handle
unblinding


## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Review by maxwofford — CHANGES_REQUESTED** [review]
I've always wanted to build one of these! Great write-up on the project & thanks for linking me the tutorial.

Just one question– I didn't see any filament in your budget & didn't see any mentioned in the amazon link for the 3d printer. Do you already have your hands on some you can use for the project?

P.S. Wow, love the background music in https://www.youtube.com/watch?v=CfirQC99xPc.

**Comment by Songrocks** [comment]
> I've always wanted to build one of these! Great write-up on the project & thanks for linking me the tutorial.
> 
> Just one question– I didn't see any filament in your budget & didn't see any mentioned in the amazon link for the 3d printer. Do you already have your hands on some you can use for the project?
> 
> P.S. Wow, love the background music in https://www.youtube.com/watch?v=CfirQC99xPc.

thanks! we do have a filament, but it doesn't match the recommended specification of the printer we were originally planning on buying. I just changed the printer we were using to use the filament we already have.

**Review by maxwofford — APPROVED** [review]
Sounds good! Just to confirm you're good to cover the additional $27.15 that the grant won't cover.

I'm approving the hardware components here and tagging in @hackclub/bank-ops to take it from here!

**Review by MelSmith104 — COMMENTED** [review]
hey @Songrocks and @unblinding! this is such a cool project :) it sounds like it would also be great to have around! im dm'ing you right now to start on the next steps!

**Comment by MelSmith104** [comment]
closing pr due to inactivity on Slack

**Pull request closed without merging**
