### PR TITLE
Toby Pull Request

### PR DESCRIPTION
**Pull request by sactoa**
## Describe your project in 1-3 sentences

I am building a surveillance robot that uses wheels to get around and watches moving objects, which I can control using bluetooth.

## Hack Club Slack handle

Toby Saunders

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by sactoa** [comment]
Hi!
A personal touch would come with smaller features. For example, I had thought of the visual feed zooming in or out and the camera rotating with certain hand motions and clipping the feed with audio commands(so it is easier to edit videos!). The first feature would be useful if I have a whiteboard, and I want the camera to follow my hand as I write. The second would be cool because of its showmanship: I could point to something behind the camera, and the camera would turn to face it!
Yes--I plan to cover any excess with my own funds.
Thank you,
Toby Saunders

**Comment by sactoa** [comment]
Also, I wrote the last comment a while ago, but forgot to re-request. I apologize.

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hi, sorry for the late review, but I'm having issues with accepting your proposal and this lines sums it up perfectly:
> The ingenuity on my part will be within the code
We want to see _hardware_ ingenuiety, not software

Winter Wonderland grants are supposed for students to create something _new_ for hardware - getting creative with the nitty-gritty of electric engineering. Unfortunately, your proposal consists of a raspi & peripherals - I don't see any low-level hardware to make f.e. your own tilting mechanism

If you want to consider making your own tilting mechanism - please go for it! We'll be more than happy to accept this! But as this stands, it's a no from me

**Comment by bellesea** [comment]
Hi @sactoa :) Thanks for your proposal. It's been a few days since cf's message and we want to know if you're still interested in the grant. Please reply in the next 48 hours to this PR (or this email) if you're still interested, else we'll be closing this proposal. Hacky New Year!

**Comment by bellesea** [comment]
hey @sactoa just to check, did you mean to close this PR?

**Comment by sactoa** [comment]
I had not meant to close the request. As for the project, I am having a bit of trouble understanding the process of bringing hardware to code without the use of a microcontroller. I am new to hardware engineering. For example, one project I had thought of was a battery-powered toy that just does push-ups, but I don't know where to begin.

**Comment by bellesea** [comment]
hey @sactoa cool! hmm, i would also find that hard haha, is there a reason why you're trying to connect hardware and software w/o a microcontroller? with the idea of a battery powered toy that does pushups, searching for guides on making perhaps robots could be a good start? https://www.instructables.com/ has lots of cool projects and i've also DMed you on slack to a channel where you could look for more help! so, how would you like to proceed? would you like to make another PR with a new project or try to modify this one?

**Comment by sactoa** [comment]
I was told by Fanoulis that Arduino and Raspberry Pi are too high-level, and I had thought that what makes them high-level are their microcontrollers. I suppose I would like to modify this one, but I would need to research a little.

**Comment by cfanoulis** [comment]
Hi, to set the record straight - I had an issue with the creativity and novelty of this project being in software & not hardware.

If you'd like to discuss this off the record, I'd be happy to talk to you in the Slack - either dm me (@char) or join #chars-corner

**Comment by sactoa** [comment]
I don't think I currently have enough experience in hardware to make a creative project, so I'll close this request, and try again next year.

**Pull request closed without merging**
