### PR TITLE
Create Custom Antennas

### PR DESCRIPTION
**Pull request by sswangg**
## Describe your project in 1-3 sentences

I am iteratively designing and creating a biquad yagi antenna. CAD in fusion, create the antenna, take measurements, and repeat.

## Hack Club Slack handle

Sophia
(with the galaxy pfp)

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: this looks super cool! can you please make your file a markdown file by adding .md at the end of the filename? also, i'm not familiar with making antennas... is there any other way to test your antennas? given that it's the majority of the budget i'm wondering how essential it is to your project :) thank you!)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by sswangg** [comment]
Hi Belle! I've updated the filename. There are other ways to test antennas, namely, plugging the antenna in and seeing how well it works. However, that doesn't give any information about if the antenna is working as well as it could be or how to make it better.

It's always possible to design an antenna, it'll just probably have a lot of signal loss. Adding any sort of analyzer makes it much easier to design a _good_ antenna. And, in antenna design communities I'm in, I've always seen people in antenna design communities talking about how helpful they are for troubleshooting and improving antennas. 

So yes, there are other ways to test antennas, but an analyzer is the only way to measure antenna properties to determine signal loss and easily see how to improve the antenna and how much it can be improved instead of blindly guessing. Also, though I feel kind of guilty for saying this, I just really want one :) A VNA is something I'd never be able to afford or justify buying without this and it'd be incredibly useful for the design process.

**Comment by bellesea** [comment]
hey @sswangg i appreciate the honesty and additional context hehe :) we'll need to do a full review to be able to let you know if the VNA is ok :) a heads up that we've started reviewing projects but due to the flurry last weekend (100+ PRs ksdjhfkjdshf) it might take a while before we review yours, thank you for your patience!

**Review by alhardwarehyde — APPROVED** [review]
I really admire your clear passion for antennas, which is a super cool project! And you've clearly already put a lot of effort towards it already! Which is great!

@hackclub/bank-ops

**Review by daisybanks — APPROVED** [review]
@sswangg - This project sounds really awesome and I love how passionate and excited you are! I'm dming you now on Slack to talk about next steps in getting you your grant. :)

**Pull request merged**
