### PR TITLE
Create hchristy1234.md

### PR DESCRIPTION
**Pull request by hchristy1234**
## Describe your project in 1-3 sentences
I'm building a custom 60% mechanical keyboard with specific custom keycaps that can control my room and assist in productivity (in addition to acting as a keyboard). I will also make a custom coiled USB cable for the keyboard.

## Hack Club Slack handle
@christy 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! **we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)**

(note: how will you be building the "custom modes"? thank you!)

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts & ready software

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by exu3** [comment]
@hchristy1234: could you fill out the PR description with the appropriate information so the Bank team can reach out on Slack when needed?

image

**Review by alhardwarehyde — APPROVED** [review]
This looks like a great project! The custom USB cable is especially cool! Passing this off to @hackclub/bank-ops for their review!

**Review by MelSmith104 — COMMENTED** [review]
hey @hchristy1234! this project sounds so cool! i love how it'll control multiple things in the room to make it super convenient. i'm dm'ing you right now to chat about next steps!

**Comment by MelSmith104** [comment]
hey @hchristy1234! can you please send me your slack id or dm me on slack (im @mel)? there are multiple people with the same slack name and i want to make sure i reach out to the right person :)

**Review by MelSmith104 — APPROVED** [review]

**Comment by christy** [comment]
Hello,

Please stop sending me these emails, it was not me who signed up for this!

Thanks!

**Pull request merged**
