### PR TITLE
Smart home System!

### PR DESCRIPTION
**Pull request by ProbablySwifty**
## Describe your project in 1-3 sentences

We are creating a smart home system that processes everything locally and never sends your information to the cloud. It will process everything locally, identify people, recognize voice lines, and all the fancy things a smart home does as well as send you text alerts based on our custom built carbon monoxide alarm. It will recycle old phones and reduce e-waste by utilizing old Android phones as the cameras of the system. 

## Hack Club Slack handle

Alen Skormin

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by ShortyPhantom** [comment]
I am working with @ProbablySwifty.
[Yes] I am a current high school student (or younger).
[Yes] I have submitted an RSVP at https://hackclub.com/winter
[Yes] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[Yes] I have self-reviewed my project proposal.

**Comment by CulturedAsian** [comment]
I am working with @ProbablySwifty.
[Yes] I am a current high school student (or younger).
[Yes] I have submitted an RSVP at https://hackclub.com/winter
[Yes] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[Yes] I have self-reviewed my project proposal.

**Comment by JesusDonCarlos23** [comment]
I am working with @ProbablySwifty. This is Avin Olvera
[Yes] I am a current high school student (or younger).
[Yes] I have submitted an RSVP at https://hackclub.com/winter
[Yes] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[Yes] I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
heyy @Songrocks and @unblinding thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering whether you actually need a $300 graphics card...)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
Sounds like a cool project! I have a couple of questions:

1. Can most of this be done in ten days? I know this is among four people so y'all should have no trouble but just wanted to make sure.
2. The CPU and motherboard link redirects to a page for RAM. Could you fix that please?
3. About the custom LAN - how is that going to work? And are y'all also planning to build the dashboard as well?
4. "The phones connect directly to the system to allow for minimal latency and faster response times. By doing it this way, we can also ensure that the" Could you fill out the rest of this as needed?
5. **Could you please recalculate the total? I think it's a bit off.**

**Comment by jianmin-chen** [comment]
Could you guys also replace "Yes" with "X" so the checklists are checked off? I just want to make sure - it makes it easier for us. Thanks! :)

**Comment by ProbablySwifty** [comment]
1. Yes, with the way that it's structured we'll have one person work on the website for a majority of the ten days to get it setup all and running. Another person will work learning how to train the AI model for both audio and video inputs. One person will work on setting up the system itself and installing all the necessary pre-requisites. This person will also setup the system connecting the phones and modify Droidcam's driver to handle multiple streams. The last person will work on getting the multi-purpose detector functioning. Once anyone finishes with their part, we'll assign them to assist with the creation of the dashboard as well as the creation of the warning system. The way this project is structured ensures that each person works in their own specialty and once done can easily contribute by assisting the other members with their respective tasks.
2. Sorry about that! I messed up copying our budget from our Excel sheet. That should cover both 2 & 5 as I've updated the links and indicated what we're buying as well.
3. We plan on creating our own Wi-Fi network from the built-in Wi-Fi with the motherboard. This will facilitate the network that the phones will connect to. This will all be hosted locally within the PC so that there is no other part to the connection. This Wi-Fi network will not have its' own internet connection and instead only be placed in a LAN with the PC. For the dashboard, we plan on hosting it on the VM, and we plan on making our own dashboard through React Native. This will have a basic login system and will allow viewers to see the cameras, control what the cameras do when it detects things that it knows, configure custom commands on top of the already built-in ones for voice speakers, and configure the notification system.
4. Apologies for that! We must've gotten carried away with writing things that we forgot to finish a part. We've updated that part now.

**Comment by ProbablySwifty** [comment]
Checklist before submitting proposal:
[X] I am a current high school student (or younger).
[X] I have submitted an RSVP at https://hackclub.com/winter
[X] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[X] I have self-reviewed my project proposal.

**Comment by JesusDonCarlos23** [comment]
I am Avin working with
@ProbablySwifty.
[X] I am a current high school student (or younger). 
[X] I have submitted an RSVP at https://hackclub.com/winter 
[X] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack) 
[X] I have self-reviewed my project proposal.

**Comment by ShortyPhantom** [comment]
I am working with @ProbablySwifty. - This is Ethan Chiles
[Yes] I am a current high school student (or younger).
[Yes] I have submitted an RSVP at https://hackclub.com/winter
[Yes] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[Yes] I have self-reviewed my project proposal.

**Comment by CulturedAsian** [comment]
I am George working with @ProbablySwifty. 
[X] I am a current high school student (or younger).
[X] I have submitted an RSVP at https://hackclub.com/winter
[X] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[X] I have self-reviewed my project proposal.

**Comment by ProbablySwifty** [comment]
Ah sorry about that! I'm asking the rest of my group members to update it we're just at school right now so it might take a little while.

**Comment by ProbablySwifty** [comment]
All done now!

**Review by jianmin-chen — APPROVED** [review]
Okay, awesome! @hackclub/bank-ops will be reaching out soon to get your project moving :)

**Review by MelSmith104 — COMMENTED** [review]
hey everyone! really awesome project idea! this seems it'll be so much fun to build as a team :) im dm'ing you all on slack right now to chat about next steps!

**Review by cfanoulis — APPROVED** [review]

**Pull request merged**
