### PR TITLE
Smart alarm clock

### PR DESCRIPTION
**Pull request by YodaLightsabr**
## Describe your project in 1-3 sentences

I'm building a smart alarm clock that can show weather, set alarms, control my lights, and more. 

## Hack Club Slack handle

<@U022XFD2TML>

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by jianmin-chen — COMMENTED** [review]
Sounds like a cool project! Are you planning to directly connect it to an outlet, or...? Also, I know you're only using the button, so no soldering, I'm assuming - just the breadboard and wires, right?

**Comment by YodaLightsabr** [comment]
I'm planning to plug it in with the RPi power supply. The button won't need soldering.

**Review by jianmin-chen — APPROVED** [review]
Alrighty, awesome! A member from @hackclub/bank-ops should be in touch with you soon!

**Review by MelSmith104 — COMMENTED** [review]
hey @YodaLightsabr! i love how convenient your project is :) im dm'ing you right now to get started with the grant process!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
