### PR TITLE
Create akapoor07.md

### PR DESCRIPTION
**Pull request by akapoor07**
## Checklist before submitting proposal:

- [ ] I am a current high school student (or younger).
- [ ] I have submitted an RSVP at <https://hackclub.com/winter>
- [ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project, this looks awesome and i'm wondering: are you referencing any sort of guides for this? do you have plans to write any of your own software/code outside of connecting to the google assistant SDK?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — CHANGES_REQUESTED** [review]
Hey! :D Following up on @bellesea's comments.

**Comment by bellesea** [comment]
hey @akapoor07 hope you're doing awesome! it's been two days since sam's request for changes, i'm wondering, when do you think you'll be able to make the changes? we'd love to move forward with reviewing this PR so you can get your parts in time for the event :) thanks!

(i believe he was referring to this part of my message)
> (note: from a first glance of your project, this looks awesome and i'm wondering: are you referencing any sort of guides for this? do you have plans to write any of your own software/code outside of connecting to the google assistant SDK?)

**Comment by akapoor07** [comment]
Hi! I am so sorry for the late response, I did not see the message. I referenced a few different guides in order to make sure that I was using the needed materials. I believe that it is necessary to write some of my own code outside of connection to the google assistant SDK, especially in order to ensure that audio will work.

**Comment by cfanoulis** [comment]
Hi! As we need to wrap up on proposals this week, please reply to sam's questions within the next 24 hours - else we will be closing this PR.

**Comment by akapoor07** [comment]
> Could you expand on the code you intend to write in your plan?

I plan to add an LED light which could act as an indicator for the google home. This means that when the google home is turned on and in use, the LED light will turn on. Once the google home is finished with the conversation the LED light will turn off. This will require additional code in order to determine when the LED light should be turned on or off.

**Comment by bellesea** [comment]
hey @akapoor07 apologies for the delayed response! unfortunately in this current state, your project is a mostly software project where most of the work has already been done for you so it doesn't fit the criteria/intentions for this event and we won't be able to proceed with this PR. 

however, we'd like to offer you a chance to amend it so there's a stronger hardware component and a lot of code you write yourself eg. adding temperature sensors and tracking it over time in a dashboard they create. 

_(small note: we cannot approve ready consumer products like a bluetooth speaker & headphone unless they are essential to your project and you're modifying it in a significant way so if you do update your project please remove these two items)_

please let us know how you'd like to proceed by updating your PR OR closing it by tomorrow (3 Feb) at 4pm ET or it will be too late to purchase your items in time for the 10 day event. thank you sm!

**Pull request closed without merging**
