### PR TITLE
AI-Powered RC Car

### PR DESCRIPTION
**Pull request by SiruX21**
## Describe your project in 1-3 sentences

We are constructing a self-driving car that is powered by AI. It will listen to voice commands and move to where requested. This is a new proposal from #390 from the same members of that group.

## Hack Club Slack handle

Siru

## Checklist before submitting proposal:

- [✔️ ] I am a current high school student (or younger).
- [ ✔️] I have submitted an RSVP at <https://hackclub.com/winter>
- [✔️ ] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [✔️ ] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by Look-Its-Sky** [comment]
I am working with @SiruX21 for this project.
[✔️ ] I am a current high school student (or younger).
[ ✔️] I have submitted an RSVP at https://hackclub.com/winter
[✔️ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
[✔️ ] I have self-reviewed my project proposal.

**Review by jianmin-chen — CHANGES_REQUESTED** [review]
Hey there! After some discussion with the rest of the HC team working on approving Hardware Wonderland projects, we think something like a Jetson Nano would be more suitable for your project. We all agree that your project sounds awesome, so do you think you could adjust the PC parts a bit? The Ryzen 9 and 16GB RAM is a little too overkill for a PC that will simply be running a web interface. 

Let me know if you have any questions or clarifications.

**Comment by SiruX21** [comment]
> The Ryzen 9 and 16GB RAM is a little too overkill for a PC that will simply be running a web interface.

The Ryzen 9 is not only running the web interface, it's running the Facial Detection algorithm, Object Detection algorithm, and path finding algorithm. The Jetson Nano can definitely run the facial detection and object detection algorithm, but we don't think it will work with the path finding algorithm. In order to make the car successfully go from one point to another, it needs to have some sort of path finding algorithm that makes it move from one place to another. This is an algorithm we are looking at making ourselves since the Google Maps API does not explicitly provide this information in a way that's suitable for our needs. Hence, we want to utilize the processor in order to run this compute-intensive task. We've had some experience writing this sort of algorithm on a limited scale, so we want to sort of expand our scope with it and do it with actual vehicles. In this sense, the computer would act as the, "brains", of the car and directly control it, providing commands, instructions, and processing all the information. Ideally, we'd want to have this all in one package, but we don't have a car on hand that we could easily modify to fit this all in and be powered by electricity.
So at the end, the Jetson Nano would necessitate the cut down in scope that we mentioned in our original draft, it would have to be instead an RC car within a home since plotting directions would simply put, be impossible.

**Review by cfanoulis — CHANGES_REQUESTED** [review]
heyo! I unfortunately have to request you cut down on the scope of your project. We really want you to have something to present on Feb. 23rd - and I feel like this project is too extensive for such a timeframe (considering all work has to be done *only* during 14/02-23/02).

Also, I can't help but notice that you have kept the PC parts from your previous PR - this leads me to believe that under the hood you're still trying to get a computer, which means this proposal would be in bad faith.

**Comment by SiruX21** [comment]
We've updated our project accordingly then.

**Review by hackliv — COMMENTED** [review]
Hey @SiruX21 this sounds so cool! Would your other 3 team members be able to comment here with the checklist? Once they're able to do that, I can dm you all on Slack about next steps for the grant!

**Comment by RartedRussian** [comment]
[✔️ ] I am a current high school student (or younger). 
[ ✔️] I have submitted an RSVP at https://hackclub.com/winter
[✔️ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack) (Eric Zazovsky on Slack)
[✔️ ] I have self-reviewed my project proposal.

**Comment by Look-Its-Sky** [comment]
Hey! I'm working with @SiruX21.
[✔️ ] I am a current high school student (or younger).
[ ✔️] I have submitted an RSVP at https://hackclub.com/winter
[✔️ ] I am a member of the Hack Club Slack (Join at https://hackclub.com/slack) (Eric Zazovsky on Slack)
[✔️ ] I have self-reviewed my project proposal.

**Comment by SiruX21** [comment]
Hey @hackliv! Sorry, our friend @Cimbobimb is unable to join this project anymore as he has some personal matters to attend to. We still think this project is viable with just 3 people instead of 4 because we cut it down a lot. Everybody else has commented above now. As for how we'll divide the work, I'll personally handle fitting everything together and putting together the RC, @Look-Its-Sky will handle connecting the Pis and the Nanos together and developing the underlying script powering the system, and @RartedRussian will handle training the AI models for image and speech. We could've definitely completed it faster with Andres' help, but it's still absolutely possible to do within a 10 day timeframe.

**Comment by SiruX21** [comment]
These are all the Slack Handles of the group:
Eric Zazovsky
Jude Joubert
Siru

**Pull request merged**
