### PR TITLE
Robot Puppy

### PR DESCRIPTION
**Pull request by parathb**
## Describe your project in 1-3 sentences

I am building a robot puppy, a similar to Spot by Boston Dynamics with my younger brother @DavDivbizziz that is autonomous using a Raspberry Pi with sensors such LiDAR and ultrasonic sensors thus having the ability to navigate itself and avoid obstacles. This robot puppy will be able to be autonomous with the LiDAR that tracks the surroundings and ultrasonic sensors that give the data such as distance that report back to the code and tells the servos to move away; in addition to be autonomous it can also be manually controlled via a PS4 Controller via Bluetooth.

## Hack Club Slack handle

ParathB & DivDav (brother)

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@parathb this looks sooo awesome!! super exciting hehe :) can your brother please add a comment to this PR confirming that have done the below?
- [ ]  I am a current high school student (or younger).
- [ ]  I have submitted an RSVP at https://hackclub.com/winter
- [ ]  I am a member of the Hack Club Slack (Join at https://hackclub.com/slack)
- [ ]  I have self-reviewed my project proposal.

also, i'm not super familiar w/ how the mechanics of a robot puppy will work so out of curiosity, why are you purchasing have 5 sets of motors w/ controllers and 3 sets of just motors?

thank you so much!!

**Comment by parathb** [comment]
spot-gxp2x

Apologies for my awful diagram, but for this to work with a much better balance it requires the 8 servos; one for the main joint and another for the small joint (knee) per each leg. In addition, it was way cheaper to the buy that 5 sets of servos + controller + 3 set of servos then buying it separately as the results I found for that were selling the combine package of 5 + controllers were a better option then buying all of them separately.

**Comment by DavDivbizziz** [comment]
# My Slack Handle: DivDav

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

**Comment by bellesea** [comment]
> spot-gxp2x
> 
> @bellesea Apologies for my awful diagram, but for this to work with a much better balance it requires the 8 servos; one for the main joint and another for the small joint (knee) per each leg. In addition, it was way cheaper to the buy that 5 sets of servos + controller + 3 set of servos then buying it separately as the results I found for that were selling the combine package of 5 + controllers were a better option then buying all of them separately.

ahh thank you so much for explaining this, and that makes sense :)

**Review by daisybanks — APPROVED** [review]
@parathb and @DavDivbizziz I love the diagram! And I love the idea for the robot puppy! Next steps for us would be to move communications over to Slack so we can communicate a little easier. We can schedule a Zoom call so I can explain how to get you the grant and I can explain our fiscal sponsorship contract which you'll have to sign with a parent/guardian in order to receive the grant. Looking forward to working together! :)

**Pull request merged**
