### PR TITLE
Custom Resin Printed Keycaps

### PR DESCRIPTION
**Pull request by samanthahuaa**
## Describe your project in 1-3 sentences

We are building custom keycaps using a resin 3D printer. We will test out these keycaps in the mechanical keyboards we make.

## Hack Club Slack handle

@Samantha H and @Courtney Huang

## Checklist before submitting proposal:

- [x] We are both current high school students (or younger).
- [x] We have both submitted an RSVP at <https://hackclub.com/winter>
- [x] We are both members of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] We have both self-reviewed our project proposal.

### CODE REVIEW

**Comment by courtneyhg** [comment]
HI, I'm the other partner working on this!

**Comment by exu3** [comment]
> Hi, I'm the other partner working on this!

Screenshot 2023-01-05 at 7 25 18 PM

@courtneyhg, can you confirm you meet the requirements (screenshot above)?

**Comment by courtneyhg** [comment]
Yes, I meet all the requirements!

**Review by exu3 — CHANGES_REQUESTED** [review]
Hey @samanthahuaa / @courtneyhg, sorry for the delayed review here.

I'm not sure that this project meets the requirement of being technically challenging as it seems mostly CAD-based and assembling things. Is there a world where you could adapt this project to be more oriented around building things with electronics parts or programming/software?

**Comment by samanthahuaa** [comment]
I see what you're saying. After talking and researching about this with Courtney, we were able to find many QMK tutorials to
guide us in programming our keyboards for a more custom layout. We feel confident moving forward in the direction of using
QMK software after our keyboards have been built. We would use it for layer switching and lighting sequences. This is in line
with our original goal of making our keyboard more fitted to our needs and wants. Is this technical enough? Or should we look
at other/more ways to extend this project?

**Review by exu3 — COMMENTED** [review]
Ok! I think that would qualify for the grant if your project is centered around learning how to use QMK instead of designing custom keycaps. You can of course, still design custom keycaps, but that should not be the main focus.

Also, I noticed your budget includes a keyboard kit which I'm not sure we can approve. It's preferable that you source your own parts as you get to learn more about each component (and it's usually possible to get it cheaper by sourcing parts on your own). 

Building a keyboard in the mainstream sense (buying components and assembling them) wouldn't qualify for the grant; however, if you can make the focus of your project something more technically challenging such as designing your own PCB, writing your own firmware so that your keyboard does unconventional/hacky things, etc, that may qualify.

With that in mind, if you feel that making these revisions would substantially change your current proposed project, I would suggest closing this PR and opening a new one to keep the comment thread more readable.

If you have any questions feel free to reach out on Slack in #hardware-party for a faster response. Thanks!

**Comment by samanthahuaa** [comment]
thank you for your reply!

**Pull request closed without merging**
