### PR TITLE
Arduino Amphibious Rover!

### PR DESCRIPTION
**Pull request by thelouisgan**
## Describe your project in 1-3 sentences
The rover will be built using an Arduino microcontroller, a variety of sensors, and waterproof motors and hardware to enable it to move through water. I plan to use readily available components, however the entire project will be new and original, leaving myself to experiment with new concepts rather than following a strict tutorial.

## Hack Club Slack handle
@louisgan

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hiii @thelouisgan ahh this is so cool!!! 

i'm wondering:
- could you please elaborate a little more  under plan on how you'd be using each component listed in your budget?
- what would it look like to use the rover as a user?

thank you sm!
(ps. i'm malaysian too hehe)

**Review by bellesea — APPROVED** [review]
@thelouisgan this is super awesome and can't wait to see you build this!!

a fabulous member of @hackclub/bank-ops will be reaching out soon with next steps :)

ps. just to confirm do you already have wires and anything other supporting materials you might need? and, i assume you've checked that the specific items you've listed are arduino compatible?

thank you :)

**Review by MelSmith104 — COMMENTED** [review]
hey @thelouisgan! this is awesome :) i love the idea behind building it to go both in water and on land. i can't wait to see it in action! im dm'ing you on slack right now to chat about next steps for the grant!

**Review by MelSmith104 — APPROVED** [review]

**Comment by thelouisgan** [comment]
> @thelouisgan this is super awesome and can't wait to see you build this!!
> 
> a fabulous member of @hackclub/bank-ops will be reaching out soon with next steps :)
> 
> ps. just to confirm do you already have wires and anything other supporting materials you might need? and, i assume you've checked that the specific items you've listed are arduino compatible?
> 
> thank you :)

Hi, yes I already have the supporting materials eg. jumper wires, breadboard etc..I have a past experience with Raspberry Pis and Arduino, so it should be similar to the arduino Mega. In answer to the item compatibility they will all be controlled with the onboard microcontroller and the Pwm.

Thanks! 👍

**Comment by thelouisgan** [comment]
IMG20230117225839
IMG20230117225818
Also here are more planning info and diagrams for personal reference

**Pull request merged**
