### PR TITLE
Create Dcm4mcD.md

### PR DESCRIPTION
**Pull request by Dcm4mcD**
## Describe your project in 1-3 sentences

A smart irrigation system is a precision agriculture technology that optimizes the use of water for crops by adjusting watering schedules based on real-time data. It uses sensors, IoT devices, and software to monitor soil moisture levels and weather conditions to increase crop yields and reduce water waste. The system can be controlled and monitored remotely via a web or mobile app interface

## Hack Club Slack handle

Username: Aditya Pradeep 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by devramsean0** [comment]
I saw you included tax, but did you include  shipping?

**Comment by Dcm4mcD** [comment]
omg im so sorry! not sure why but all the emails i was getting saying that i was getting comments were going to my spam. since all the items are from amazon the shipping should be free

**Review by devramsean0 — APPROVED** [review]
Looks good! A member of @hackclub/bank-ops will be in touch

**Review by hackliv — APPROVED** [review]
Hey @Dcm4mcD this sounds so cool! I'd love to hear more about your plans for building and using it. 😃 I'm dming you now on Slack to see if we can schedule some time to meet!

**Comment by hackliv** [comment]
Hey @Dcm4mcD I'm closing this PR since I haven't heard back from you on the Slack.

**Pull request closed without merging**
