### PR TITLE
Create sebrod06.md

### PR DESCRIPTION
**Pull request by sebrod06**
So excited to build this project!

## Hack Club Slack handle
Display Name on Slack: sebrod06

## Checklist before submitting proposal:

- [Check] I am a current high school student (or younger).
- [Check] I have submitted an RSVP at <https://hackclub.com/winter>
- [Check] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [Check] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project this is soooo cool and i'm sure you one day will be an imagineer for disney)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by MelSmith104 — COMMENTED** [review]
hey @sebrod06 this is so cool! and that's such an awesome dream job :) im dm'ing you right now to chat about next steps and talk more about your project!

**Comment by sebrod06** [comment]
> hey @sebrod06 this is so cool! and that's such an awesome dream job :) im dm'ing you right now to chat about next steps and talk more about your project!

**Comment by bellesea** [comment]
hey @sebrod06 did you mean to close your project?

**Comment by sebrod06** [comment]
> hey @sebrod06 did you mean to close your project?

Hello! I was actually working on editing my plan to build this project today as well as some prices for the parts (Amazon seems to fluctuate prices a bit and have products on sale), so hopefully that is okay. I'm really glad my proposal was approved, though! Thank you so much!

Also, I think I might have accidentally closed this pull request, or have done something that I shouldn't have by accident. I'm not very familiar with these replies/comments. I did not mean to close my project

**Comment by sebrod06** [comment]
Is there a way I can reopen it? I'm so sorry for the inconvenience.

**Comment by bellesea** [comment]
no worries, just reopened it for you :)

**Comment by sebrod06** [comment]
Thank you so much @bellesea !

**Pull request merged**
