### PR TITLE
Create 1mPink.md

### PR DESCRIPTION
**Pull request by 1mPink**
## Describe your project in 1-3 sentences

I am building a server capable of doing virtual machines and experiment with it.

## Hack Club Slack handle

@ Mario

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
@1mPink thank you for sharing this, it looks super cool!! could you please add shipping / taxes/ and a total to your budget?

thank you sm :)

**Comment by 1mPink** [comment]
Changes Commited.

**Review by bellesea — APPROVED** [review]
@1mPink thanks for pushing the changes!! this looks awesome and can't wait to see you work on this :)

a fabulous member of @hackclub/bank-ops will be reaching out with more information soon!

**Review by hackliv — APPROVED** [review]
Hey @1mPink excited to hear more about this! Dming you on Slack now to set up some time to meet and chat about next steps for getting the grant on Hack Club Bank. 🤩

**Pull request merged**
