### PR TITLE
Agility65

### PR DESCRIPTION
**Pull request by mattkrnwn**
## Describe your project in 1-3 sentences

It's a 65% mechanical keyboard! The case will be modeled and printed by me, the switches will be hardwired to a microcontroller. It will be compatible with MX switches, Cherry stabilizers, and Cherry keycaps.

## Hack Club Slack handle

Matthew Kurniawan

## Checklist before submitting proposal:

- [ X] I am a current high school student (or younger).
- [ X] I have submitted an RSVP at <https://hackclub.com/winter>
- [ X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [ X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by cfanoulis — CHANGES_REQUESTED** [review]
Hello Mathhew - thanks for putting in the time to write a proposal

Unfortunately I'm not going to approve this request. As B Smith points out in [this](https://hackclub.slack.com/archives/C0168BR5PDE/p1671582550645499) Slack message, the point of Winter Wonderland is to encourage creative, educative tinkering - and unfortunately I feel like building a keyboard from premade components lacks both aspects.

We'd be more than happy to receive another proposal from you! Remember, you have until 01/15 to send it in!

**Comment by mattkrnwn** [comment]
> hey so I'll actually be keeping this open in case you have ideas on how to add a personal touch to it - maybe macro keys, maybe even a windows hello touch key?
> 
> cant wait to see what you come up with :)

hey! I appreciate the reply and I understand what you're getting at, but in my opinion, there are still custom components here since I'm not using a premade PCB (I'm instead hard wiring each of the switches to a microcontroller), nor premade plate or case (both of which I'm designing in CAD and printing to accommodate for my own exploded keyboard layout), and no preinstalled firmware(will likely need to compile my own to accommodate the rotary dial).

So there're elements of wiring, 3D modeling/printing, and software that I'd be practicing that wouldn't happen with a basic keyboard build. I apologize if this wasn't clear in the plan section ;) 

Though if you believe it's not enough, I could try implementing a programmable slider which I've yet to see on a 65% keyboard but I wouldn't be confident about being able to figure it out within the time window 😅

**Review by cfanoulis — APPROVED** [review]
Oh, that's actuallly... great! You've managed to precisely capture the spirit of Winter Wonderland, congrats! A banker from @hackclub/bank-ops will reach out shortly to get you setup of Bank

And sorry for misunderstanding your proposal earlier, it's just that we're trying to make sure everyone's having a creative, educative time with their grant. Can't wait to see you hackin' away in the Slack!

**Comment by mattkrnwn** [comment]
> Oh, that's actuallly... great! You've managed to precisely capture the spirit of Winter Wonderland, congrats! A banker from @hackclub/bank-ops will reach out shortly to get you setup of Bank
> 
> And sorry for misunderstanding your proposal earlier, it's just that we're trying to make sure everyone's having a creative, educative time with their grant. Can't wait to see you hackin' away in the Slack!

That's awesome, don't worry about it, and thank you so much!

**Review by hackliv — APPROVED** [review]
hey @mattkrnwn this sounds awesome, and I can't wait to hear more about it! I'm dming you now on Slack to set up some time to meet and chat about next steps for getting the grant!

**Pull request merged**
