### PR TITLE
Roh101.md

### PR DESCRIPTION
**Pull request by Roh101**
## Describe your project in 1-3 sentences
Building custom 3D printed/electrical engineered wifi boosters and antennas through making an 3-D printer with custom upgrades. Hoping to provide these antennas in the future in impoverished communities as well as for other personal events, and the project will help in mechanical as well as electrical engineering for me.

## Hack Club Slack handle
Slack Username: Rohan Kilaru; Slack ID: U04JRRKFNFQ;  Rohan Kilaru U04JRRKFNFQ

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — CHANGES_REQUESTED** [review]
Wahoo! This sounds like a total blast to build. Where are you thinking of using the extenders?

**Review by sampoder — APPROVED** [review]
(sorry I meant to approve; @hackclub/bank-ops will be in touch soon)

**Review by daisybanks — APPROVED** [review]
Hi @Roh101! This project sounds really cool and I love that you are already thinking of ways this project can expand and grow and give you lots of opportunity for learning! I'm dming you on Slack now to talk about next steps in getting you your grant!

**Pull request merged**
