### PR TITLE
whatwareweb

### PR DESCRIPTION
**Pull request by whatwareweb**
## Describe your project in 1-3 sentences
I am designing a high quality stereo amplifier. This amplifier can play audio from a smartphone, CD player, TV, etc.

## Hack Club Slack handle
@whatware

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project i'm wondering: are you referencing any sort of guide for this?)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Comment by whatwareweb** [comment]
Hi! To answer your question, I am not referencing any sort of guide. I am basically just taking everything I know about electronics and applying it here, learning as I go. Pretty much every part here is bare components except for the AC adapter power supply thing (I don't want to burn the house down :grimacing:). Thanks so much!

**Review by sampoder — APPROVED** [review]
Hey @whatwareweb! This looks like a great project. A couple of years ago, my friends and I used to salvage old parts from this great electronics dumpster and hack together little things so I'm sure this will be a bunch of fun :D

**Review by arianna-m — APPROVED** [review]
Hi @whatwareweb! So excited to see your Stereo Amp come to life! It sounds amazing! Next steps for us would be to move communications over to Slack so we can move forward! We can schedule a Zoom call, so I can explain how you get the grant and share with you the fiscal sponsorship contract which you'll have to sign with a parent/guardian. Looking forward to working together! :)

**Pull request merged**
