### PR TITLE
Secure VPN Travel Router with own DNS & VPN server

### PR DESCRIPTION
**Pull request by singhgurmehar**
## Describe your project in 1-3 sentences

In Winter Hardware Wonderland, I plan to build a Secured Wifi Router using Raspberry Pie for travel with its own VPN server and DNS server  for providing an advanced security layer over public Wifi's and also blocking ads and trackers from websites.

## Hack Club Slack handle

Gurmehar Singh

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came in, thanks for your patience :)

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a **lower level than a pre-assembled kit of parts & ready software**

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

our Jan 15 deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by bellesea — CHANGES_REQUESTED** [review]
hey @singhgurmehar thank you so much for your patience with a review!

unfortunately, this doesn't fully meet the intentions of the event/grant as there's very little hardware hacking AND the software component includes using ready made parts. a modification we could consider is if you wrote your own DNS server from scratch or did something that required you to learn about networking on a low level. eg. https://github.com/EmilHernvall/dnsguide

or you could also submit a different project idea :)

please let me know how you'd like to proceed, thank you!

**Comment by bellesea** [comment]
hey @singhgurmehar it's been a few days since my request for changes :) i'm wondering, how would you like to proceed? we look forward to moving forward soon so you can get your parts in time for the event! thanks :)

**Comment by singhgurmehar** [comment]
@bellesea i will try to write my own dns server from scratch. will be changing the repo soon...

**Comment by bellesea** [comment]
> @bellesea i will try to write my own dns server from scratch. will be changing the repo soon...

@singhgurmehar great! looking forward to reviewing it :)

**Comment by bellesea** [comment]
hey @singhgurmehar we're very excited by your PR and you wanting to change the PR hehe :) we're now drawing closer to the date of the event so could you please **push your the changes by Friday (27th) at 11:59pm ET **. this is because you're unlikely to get your parts in time if there's any further delay. thank you sm!

**Comment by singhgurmehar** [comment]
hi @bellesea actually i am figuring out to run my own dns server. within 1 day i will be pushing changes.

**Comment by bellesea** [comment]
> hi @bellesea actually i am figuring out to run my own dns server. within 1 day i will be pushing changes.

incredible! thank you sm :)

**Comment by cfanoulis** [comment]
Hi! As we need to wrap up on proposals this week, please reply to belle's request for changes within the next 24 hours - else we will be closing this PR.

**Comment by singhgurmehar** [comment]
sure changing in few minutes....

**Comment by singhgurmehar** [comment]
@bellesea Please have a look :)

**Review by bellesea — APPROVED** [review]
@singhgurmehar awesome!! thank you :)

a fabulous member of @hackclub/bank-ops will be reaching out soon with next steps :)

looking forward to seeing what other cool things you build on top of your travel router :) if you do end up doing any of the ideas it'd be great to see you update your file!

**Review by hackliv — APPROVED** [review]
hey @singhgurmehar this sounds so awesome for traveling! I'm dming you now on Slack to chat about next steps for the grant. 😊

**Comment by singhgurmehar** [comment]
sure!

**Pull request merged**
