### PR TITLE
Update samarth641.md

### PR DESCRIPTION
**Pull request by samarth641**
## Describe your project in 1-3 sentences

My drone project involves designing and building a small unmanned aircraft that is capable of stable, controlled flight, and that can perform a variety of tasks depending on its design and purpose. The project involves combining engineering, design, and programming skills to create a functional and reliable drone that can be used for a wide range of applications.

## Hack Club Slack handle

@Samarth Verulkar or Sam 

## Checklist before submitting proposal:

- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by bellesea — CHANGES_REQUESTED** [review]
hii @samarth641 can you please elaborate under plan how you'll be using each of the additional things you added to your budget? thank you :)

**Comment by samarth641** [comment]
ok so lets start with the the fishing rope and the elastic rope it will be used to tie up the ecg we are using we cannot use any other kind of adessive because it will damage it so fishing rope for strength and elastic rope for flexibility as ecg may expand  
3DR Radio Telemetry to control with laptop pc or phone TS832 48Ch 5.8G 600mW Wireless Audio/Video Transmitter for transferring video signals  5.8G UVC OTG Android AV Phone Receiver to Receive the video signals Servo m16*5 to make the landing stand retractable for 4 stand 1 extra for safety Orange 2200mAh 3S 30C/60C (11.1V)Lithium Polymer Battery Pack battery to power the video transmitter module Caddx Baby Ratel 2 1/1.8″ 1200TVL Camera as a video interface  Flex Sensor * 4 each for every stand it will be used to measure the bending of the stand so it doesn't break while  retracting

**Comment by samarth641** [comment]
@bellesea

**Review by samarth641 — COMMENTED** [review]
.

**Comment by bellesea** [comment]
hey @samarth641 what do you mean by ecg?

- how do you know that the 3dr is compatible w/ your flight controller?
- are you 3d printing your own retractable stands? 
- how will you be controlling the servos?

please commit the changes as additional context under your plan :)

thank you!

**Comment by samarth641** [comment]
Sorry by mistake I have written ecg it  was actually esc they are used to control speed of the aircraft's electric motors we have 4 of them placed for each motor  I know that 3dr is compatible with my flight controller because it is written in the documentation that it is compatible with apm2.8 which is the One we are using  yes we are indeed 3d printing the stand  we will control the servos directly through Apm 2.8 as there are extra channels for servo or we can also use the the receiver in drone as it also has channel outputs   but we are thinking to use apm instead .

**Comment by bellesea** [comment]
@samarth641 ahhh cool! thank you :) i don't think i see escs in your budget? do you already have it? and thank you! could you please add all the additional information that you've commented as an elaboration under your plan? 

eg. printing out the 3d parts (frame and stands);I created the necessary STL files in Fusion 360

**Review by samarth641 — COMMENTED** [review]
hey @bellesea I am sorry I forgot to add esg on budget I already have those I have added it as $0 dollars and also added the plans you told me

**Comment by samarth641** [comment]
sorry for the delay my exams were going on

**Pull request merged**
