### PR TITLE
MicroGeiger: DIY Geiger counter

### PR DESCRIPTION
**Pull request by geschmit**
## Describe your project in 1-3 sentences
I am building and programming a hackable, nRF-based Geiger counter utilizing the SBM-20 Geiger-Muller tube. This device will be portable, running off of a Li-Ion battery with embedded touchscreen for easy access to readings. Additionally, data can be logged and monitored to a different device via Bluetooth capabilities.

## Hack Club Slack handle
My Slack handle is @geschmit. If needed, my user ID is `U04C66A6US0`.

## Checklist before submitting proposal:
- [x] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [x] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [x] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by geschmit** [comment]
After checking the website today, the ESP32 feather V2 has gone out of stock. I will find a replacement shortly.

**Comment by geschmit** [comment]
Reviewers: Apart from the items requested, I have all the tools needed to create this(soldering gun, USB cable, etc). If you have further questions, please feel free to ask either on here or on the Slack.

**Review by bellesea — APPROVED** [review]
@geschmit thanks so much for this PR! It's such a cool project and can't wait to see you work on this :)

an awesome member of @hackclub/bank-ops will be reaching out soon with next steps!

**Comment by geschmit** [comment]
Thank you!

**Review by MelSmith104 — APPROVED** [review]

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
