### PR TITLE
PC w/ my sister :)

### PR DESCRIPTION
**Pull request by hard-shutdown**
## Describe your project in 1-3 sentences

I will be building a PC with my sister to further my knowledge of the interactions between hardware/software and will also be building my own Linux-based operating system to finish it off.

## Hack Club Slack handle

hardshutdown

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [X] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Review by exu3 — CHANGES_REQUESTED** [review]
This is great. I think your reasoning for the project makes your proposal very compelling.

Could you put your project proposal into a single document with @k1tt3nb4by (using either #103 or #104 is fine, & combining the info in both)? Grants are given on a per-project basis, so you'll be sharing a Hack Club Bank account with her.

**Comment by hard-shutdown** [comment]
Hi! I saw your comment asking for us to merge the project onto on of our PR's, so I have included her summary onto mine. Please let me know if there is anything I need to do. Thanks! :)

**Review by exu3 — APPROVED** [review]
Nice work @hard-shutdown, I'm excited to see what you both ship!

I noticed that your budget exceeds the grant amount ($500 for a team of 2)—you'll be responsible for covering the difference. If you aren't able to do that, please edit the budget accordingly.

The @hackclub/bank-ops team will follow up with next steps on receiving the grant through Hack Club Bank when you and @k1tt3nb4by ready!

**Review by MelSmith104 — COMMENTED** [review]
hey @hard-shutdown! im so excited about your project and that you're going to be building with your sister! this seems like its going to be so much fun and i can't wait to see it shipped! im dm'ing you on slack right now so that we can chat about next steps!

**Review by MelSmith104 — APPROVED** [review]

**Pull request merged**
