### PR TITLE
Sprig gaming controller

### PR DESCRIPTION
**Pull request by cytronicoder**
## Describe your project in 1-3 sentences
I will build a case for the Sprig console to make it into an actual gaming controller. Why? Because the Sprig console is a great piece of hardware, but it's not very portable. It looks a bit bulky and is not easy to carry around. It's also not very cool-looking (for anyone who doesn't know what it is).

## Hack Club Slack handle
@cytronicoder

## Checklist before submitting proposal:

- [X] I am a current high school student (or younger).
- [x] I have submitted an RSVP at <https://hackclub.com/winter>
- [X] I am a member of the Hack Club Slack (Join at <https://hackclub.com/slack>)
- [X] I have self-reviewed my project proposal.

### CODE REVIEW

**Comment by cytronicoder** [comment]
There we go! Please let me know if y'all have any questions about this project since there are a lot of open ends (+ I'm very new to hardware development, so there might be gaps in the proposal that I failed to address).

**Comment by bellesea** [comment]
heyy thanks so much for making a PR! we're back on tuesday and will start reviewing PRs in the order that they came on. 

to make the process smoother, please ensure you double checked that your file is properly formatted, you have all the parts you need, and that your plan is detailed enough for us to imagine how you're using the components in your budget to build your project and visualise you work on it :)

and fyi, we're looking for projects where/that:
- you can spend at least 10 days building (from Feb 14th to 23rd)
- you are able to modify or make your own in some ways
- you can learn something new from
- involves working with electronics or software on a lower level than a pre-assembled kit of parts

and, we normally don’t approve projects where you buy consumer components w/o modification like keyboards (buying PCB, keycaps, switches, and assembling it), PCs (buying motherboard, cpu, memory and plugging it together), and kits (eg. closed-sourced consumer drone kits). 

_(note: from a first glance of your project, this looks awesome and we can't wait to review it!!)_

our Jan 15 11:59pm ET deadline is for PRs to come in and not for final approval so we'll work with you to either accept this project OR give you a chance to submit another PR. 

if you have any questions, please do not hesitate to ask her or DM me (i'm belle on slack), thank you!

**Review by sampoder — APPROVED** [review]
Love the idea! Can't wait to see this come to fruition. Curious, what's the use for the second Pico?

**Comment by cytronicoder** [comment]
@sampoder It's primarily to get my hands dirty with testing out the components before I build the actual controller. 💪

**Review by daisybanks — APPROVED** [review]
Hi @cytronicoder! I'm excited to be working with you for your WHW project!! I love that you're tying two Hack Club thing together and this sounds really awesome! I'm dming you now to talk about getting you your grant. :)

**Pull request merged**
